comit-network/comit-rs

.mergify.yml
Mergify currently does not merge because of that.
=> [fix mergify] Rename status check as per our Travis setup

api_tests/e2e/rfc003/btc_eth-erc20/test.js, api_tests/e2e/rfc003/btc_eth/test.js, api_tests/harness.js, api_tests/test_lib.js, application/comit_node/src/http_api/rfc003/swap.rs
Implemented some comments coming from #571.
Spent some time trying to make the bitcoin block generation work in the background but it does not seem to be possible with Mocha.
=> Test should not be controlling bitcoin blocks gen

api_tests/dry/rfc003/test.js, application/comit_node/src/bam_api/rfc003/swap.rs, application/comit_node/src/comit_client/bam.rs, application/comit_node/src/comit_client/mod.rs, application/comit_node/src/http_api/rfc003/action.rs, application/comit_node/src/http_api/route_factory.rs, application/comit_node/src/lib.rs, application/comit_node/src/swap_protocols/rfc003/actions/bob/mod.rs, application/comit_node/src/swap_protocols/rfc003/state_machine.rs, vendor/bam/src/json/response.rs
=> Bob can decline a swap request

api_tests/dry/rfc003/test.js, application/comit_node/src/bam_api/rfc003/swap.rs, application/comit_node/src/comit_client/bam.rs, application/comit_node/src/comit_client/mod.rs, application/comit_node/src/http_api/rfc003/action.rs, application/comit_node/src/http_api/route_factory.rs, application/comit_node/src/lib.rs, application/comit_node/src/swap_protocols/rfc003/actions/bob/mod.rs, application/comit_node/src/swap_protocols/rfc003/state_machine.rs, vendor/bam/src/json/response.rs
Reverts comit-network/comit-rs#572 because mergify was too fast
=> Revert "Bob can decline a swap request"

application/comit_node/src/swap_protocols/rfc003/bitcoin/htlc.rs, application/comit_node/src/swap_protocols/rfc003/ethereum/queries.rs, application/comit_node/src/swap_protocols/rfc003/mod.rs, application/comit_node/src/swap_protocols/rfc003/secret.rs, application/comit_node/tests/rfc003_bitcoin_htlc.rs
Almost done, just need to fix 2 tests once `bx` is installed.
Resolves #416
=> Check Secret Length in Bitcoin HTLC

vendor/bam/src/json/frame.rs, vendor/bam/src/json/response.rs
Reacting to some comments on #590.
---
=> Bob can decline post mortem

application/ledger_query_service/src/block_processor.rs
=> Missing feedback from last PR

README.md
=> Add instructions to install zeromq

README.md
=> Add libssl install and run `cargo make` at the end

CONTRIBUTING.md
Reference Emoji reviews to let external contributors know.
---
=> Cargo make + emoji reviews

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Adds a Contributor license agreement and update PR template
---
=> Add contributor license agreement

api_tests/e2e/rfc003/btc_eth-erc20/test.js, api_tests/e2e/rfc003/eth-erc20_btc/config.toml, api_tests/e2e/rfc003/eth-erc20_btc/test.js, api_tests/e2e/rfc003/eth_btc/test.js, application/comit_node/src/bam_api/rfc003/swap.rs, application/comit_node/src/http_api/rfc003/swap.rs, application/comit_node/src/http_api/rfc003/with_swap_types.rs, application/comit_node/src/swap_protocols/rfc003/alice/actions/erc20_btc.rs, application/comit_node/src/swap_protocols/rfc003/alice/actions/mod.rs, application/comit_node/src/swap_protocols/rfc003/alice/swap_request.rs, application/comit_node/src/swap_protocols/rfc003/bob/actions/erc20_btc.rs, application/comit_node/src/swap_protocols/rfc003/bob/actions/mod.rs, application/comit_node/src/swap_protocols/rfc003/bob/swap_request.rs
Implement Atomic Swap ERC20 for BTC.
Resolves #589
---
=> ERC20->BTC

api_tests/dry/rfc003/test.js, application/comit_node/src/bin/comit_node.rs, application/comit_node/src/comit_client/bam.rs, application/comit_node/src/comit_client/mod.rs, application/comit_node/src/http_api/mod.rs, application/comit_node/src/http_api/route_factory.rs
Add HTTP API endpoint to list all peers to which a comit node is connected to.
Resolves #620.
---
=> Add GET /peers to HTTP API

Cargo.lock, Makefile.toml, application/comit_node/src/comit_client/bam.rs, application/comit_node/src/comit_client/fake.rs, application/comit_node/src/http_api/rfc003/action.rs, application/comit_node/src/ledger_query_service/fetch_transaction_stream.rs, application/comit_node/src/swap_protocols/rfc003/bitcoin/htlc.rs, application/comit_node/src/swap_protocols/rfc003/bitcoin/validation.rs, application/comit_node/src/swap_protocols/rfc003/state_store.rs, application/ledger_query_service/src/route_factory.rs, vendor/bam/src/json/frame.rs, vendor/bitcoin_support/src/blocks.rs, vendor/bitcoin_support/src/lib.rs, vendor/bitcoin_support/src/pubkey.rs, vendor/bitcoin_support/src/transaction.rs, vendor/bitcoin_support/src/weight.rs, vendor/bitcoin_witness/Cargo.toml, vendor/bitcoin_witness/src/primed_transaction.rs, vendor/bitcoin_witness/tests/sign_with_rate.rs, vendor/key_gen/Cargo.toml, vendor/key_gen/src/main.rs
Added a few checks to clippy and fixed fixed them in the code.
Resolves #304 
---
=> Add a few checks to clippy

application/comit_node/src/swap_protocols/rfc003/bitcoin/htlc.rs, application/comit_node/src/swap_protocols/rfc003/secret.rs
=> Make `SecretHash` `Copy`

Makefile.toml, api_tests/lib/actor.js, api_tests/lib/ethereum.js
Use find to get all JavaScript files to format/check-format.
Resolves #628.
---
=> Format all JavaScript files

.github/PULL_REQUEST_TEMPLATE.md, .mergify.yml
=> Only mergify a pr if correct label is set

application/ledger_query_service/src/bitcoin/block_processor.rs, application/ledger_query_service/src/bitcoin/queries.rs, application/ledger_query_service/src/ethereum/queries.rs, application/ledger_query_service/src/lib.rs, application/ledger_query_service/src/route_factory.rs, application/ledger_query_service/src/routes.rs
=> Remove IsEmpty trait

api_tests/ledger_query_service/test.js, application/ledger_query_service/src/bin/ledger_query_service.rs, application/ledger_query_service/src/ethereum/block_processor.rs, application/ledger_query_service/src/ethereum/mod.rs, application/ledger_query_service/src/ethereum/queries.rs, application/ledger_query_service/src/ethereum/queries/block_query.rs, application/ledger_query_service/src/ethereum/queries/event_query.rs, application/ledger_query_service/src/ethereum/queries/mod.rs, application/ledger_query_service/src/ethereum/queries/transaction_query.rs
Add a new filter to verify erc20 funding.
Fixes #476
=> Verify erc20 funding using LQS

application/comit_node/src/swap_protocols/rfc003/bitcoin/actions.rs
With the implementation in #673, this question is now answered and
the answer is no.
=> Remove TODO

application/comit_node/src/bin/comit_node.rs
This TODO is thereby obsolete.
=> Settings no longer contain private keys

.githooks/pre-commit, Makefile.toml
=> Run JS check format before commit

Makefile.toml
=> Don't use --all-targets as it doesn't run doc tests

api_tests/dry/multiple_peers.js, api_tests/dry/rfc003_swap_reject.js, api_tests/e2e/rfc003/btc_eth-erc20/test.js, api_tests/e2e/rfc003/btc_eth/test.js, api_tests/e2e/rfc003/eth-erc20_btc/test.js, api_tests/e2e/rfc003/eth_btc/test.js, application/comit_node/src/http_api/rfc003/handlers/get_swap.rs, application/comit_node/src/http_api/rfc003/handlers/get_swaps.rs
=> Minor name changes in get swap/list swaps http api responses

api_tests/lib/bitcoin.js, api_tests/yarn.lock
=> Upgrade bitcoinjs-lib to make use of built-in regtest definition

Cargo.lock, api_tests/regtest/docker-compose.yml, application/btsieve/Cargo.toml, application/comit_node/Cargo.toml, vendor/bitcoin_rpc_test_helpers/Cargo.toml, vendor/bitcoin_witness/Cargo.toml, vendor/tc_bitcoincore_client/Cargo.toml, vendor/tc_web3_client/Cargo.toml
=> Deactivate bitcoind `-acceptnonstdtxn` in tests

application/comit_node/src/swap_protocols/ledger/bitcoin.rs
=> TODO already tracked with #376

Cargo.lock, application/btsieve/Cargo.toml, application/btsieve/src/bin/btsieve.rs
=> Fix loading settings in btsieve

api_tests/dry/rfc003_swap_reject.ts, application/comit_node/src/bam_api/mod.rs, application/comit_node/src/bam_api/rfc003/swap.rs, application/comit_node/src/http_api/mod.rs, application/comit_node/src/http_api/swap_resource.rs, application/comit_node/src/swap_protocols/dependencies/client_impl.rs, application/comit_node/src/swap_protocols/mod.rs
=> Link to protocol specification in GET /swaps and GET /swap/rfc003/:id

api_tests/dry/sanity.ts, application/btsieve/src/routes.rs, application/comit_node/src/http_api/problem.rs, application/comit_node/src/http_api/routes/rfc003/handlers/get_action.rs, application/comit_node/src/http_api/routes/rfc003/handlers/post_swap.rs, application/comit_node/src/http_api/with_swap_types_bob.rs
=> Build HttpApiProblems consistently

application/comit_node/src/http_api/problem.rs
Noticed we were using it sub-optimally while doing the refund code.
=> Use HttpApiProblem::new() to set the title

.mergify.yml
=> Update to match GitHub rules

api_tests/dry/rfc003_swap_reject.ts, application/comit_node/src/http_api/routes/rfc003/swap_state.rs
=> Add secret hash to the HTTP API

application/comit_node/Cargo.toml, application/comit_node/src/swap_protocols/metadata_store.rs, vendor/blockchain_contracts/Cargo.toml, vendor/blockchain_contracts/src/lib.rs
According to the crate maintainer: https://github.com/Peternator7/strum/issues/49#issuecomment-488783127
=> Use Strum correctly

api_tests/lib/actor.ts, api_tests/lib/comit.ts, application/comit_node/src/http_api/routes/rfc003/handlers/get_action.rs, application/comit_node/src/swap_protocols/rfc003/actions/erc20.rs, application/comit_node/src/swap_protocols/rfc003/actions/ether.rs, application/comit_node/src/swap_protocols/rfc003/alice/actions/erc20.rs, application/comit_node/src/swap_protocols/rfc003/bob/actions/erc20.rs, application/comit_node/src/swap_protocols/rfc003/ethereum/actions.rs
=> Renames SendTransaction to CallContract

vendor/comit_i/version
Pull the newest version of  comit-i in the comit-node.
=> Increment version after comit-i release.

application/comit_node/src/swap_protocols/rfc003/bitcoin/htlc_params.rs
=> Remove dead code

vendor/bitcoin_support/src/weight.rs
The task expressed in this TODO actually has some dependencies that I wanted to make explicit. Hence I created an issue (#990 ) to properly track it.
=> Replace TODO with ticket

api_tests/e2e/rfc003/btc_eth/happy.ts, api_tests/lib/ethereum.ts, api_tests/package.json, api_tests/yarn.lock
=> Update web3 to latest version and patch around receipt-bug

api_tests/webgui/webgui.ts, application/comit_node/src/http_api/route_factory.rs
=> Set CORS headers on error responses

api_tests/dry/multiple_peers.ts, api_tests/dry/peers_using_ip.ts, api_tests/dry/rfc003_schema.ts, api_tests/dry/rfc003_swap_with_ip.ts, api_tests/dry/sanity.ts, api_tests/e2e/test_creator.ts, api_tests/lib/actor.ts, api_tests/lib/comit.ts, api_tests/package.json, api_tests/webgui/webgui.ts, api_tests/yarn.lock, application/comit_node/src/comit_client.rs, application/comit_node/src/http_api/mod.rs, application/comit_node/src/http_api/routes/rfc003/handlers/post_swap.rs, application/comit_node/src/libp2p_bam/behaviour.rs, application/comit_node/src/network.rs, application/comit_node/src/swap_protocols/dependencies/client_impl.rs, application/comit_node/src/swap_protocols/rfc003/alice/communication_events.rs, application/comit_node/src/swap_protocols/rfc003/alice/mod.rs, application/comit_node/src/swap_protocols/rfc003/alice/spawner.rs
=> Allow multiaddress to be passed in swap request

application/comit_node/src/http_api/routes/rfc003/swap_state.rs, application/comit_node/src/swap_protocols/rfc003/ledger_state.rs
A minor cleanup I ran into while doing #994.
=> Derive Default implementations

Makefile.toml, api_tests/package.json, api_tests/tsconfig.json
Would have saved me some time :)
=> Run tsc to catch TypeScript syntax error early on

vendor/comit_i/version
- Uses new siren API
- Support address hint use
=> Upgrade embedded comit-i to v0.2.0-alpha

application/comit_node/tests/rfc003_bitcoin_htlc.rs, vendor/bitcoin_rpc_test_helpers/src/lib.rs, vendor/bitcoin_witness/tests/p2wpkh.rs, vendor/bitcoin_witness/tests/sign_with_rate.rs
Segwit is always activated on regtest:
https://github.com/bitcoin/bitcoin/pull/11389
However we need some bitcoins and coinbase Bitcoins can only be spent
after 100 confirmations.
=> Segwit is always activated but we need funds

vendor/blockchain_contracts/src/bin/calculate_offsets/bitcoin/rfc003/compile_contract.rs, vendor/blockchain_contracts/src/bin/calculate_offsets/bitcoin/rfc003/mod.rs, vendor/blockchain_contracts/src/bin/calculate_offsets/ethereum/rfc003/contract.rs, vendor/blockchain_contracts/src/bin/calculate_offsets/mod.rs
While reviewing https://github.com/comit-network/comit-rs/pull/1053, I noticed two things that could be simplified.
=> Minor simplifications for the offset calculations of the bitcoin HTLC

Cargo.toml
Saw this on another project and thought it was cool.
=> Simplify root Cargo.toml through catch-all * syntax

api_tests/e2e/rfc003/eth_btc/bitcoin_high_fee.ts, api_tests/lib/actor.ts, api_tests/lib/test_creator.ts, comit_node/src/http_api/action.rs, vendor/bitcoin_witness/src/primed_transaction.rs
=> Return 400 when fee is too high

api_tests/e2e/rfc003/eth_btc/bitcoin_high_fee.ts, api_tests/lib/actor.ts, api_tests/lib/test_creator.ts
I gave it a shot to fit the redeem/refund tests with high Bitcoin fees into our test framework.
=> Move override of Bitcoin fee to Actor class

README.md, btsieve/src/lib.rs, btsieve/src/main.rs, comit_node/src/lib.rs, comit_node/src/main.rs, vendor/bam/src/lib.rs, vendor/bitcoin_rpc_test_helpers/src/lib.rs, vendor/bitcoin_support/src/lib.rs, vendor/bitcoin_witness/src/lib.rs, vendor/blockchain_contracts/src/lib.rs, vendor/blockchain_contracts/tests/rfc003_bitcoin_htlc.rs, vendor/blockchain_contracts/tests/rfc003_erc20_htlc.rs, vendor/blockchain_contracts/tests/rfc003_ether_htlc.rs, vendor/comit_i/src/lib.rs, vendor/ethereum_support/src/lib.rs, vendor/key_gen/src/main.rs, vendor/secp256k1_support/src/lib.rs, vendor/siren/src/http_serde.rs, vendor/siren/src/lib.rs, vendor/tc_bitcoincore_client/src/lib.rs, vendor/tc_web3_client/src/lib.rs
https://www.youtube.com/watch?v=0QDKLglEP5Y
=> Do the safety dance!

api_tests/yarn.lock
Someone/something forgot to update the yarn lock after updating the dependencies
=> Update yarn lock

btsieve/src/bitcoin/mod.rs, btsieve/src/lib.rs, btsieve/src/main.rs, vendor/bitcoin_support/src/mined_block.rs
This is the first step towards lite clients.
I kept the change as small as possible, so this PR introduces: 
* `Bitcoin` and `Ethereum`-chain in https://github.com/comit-network/comit-rs/blob/a32b6cbf904e68c6bec8dad856fc6a24c98ff763/btsieve/src/lib.rs#L58-L60
* `BlockchainDAG` data-structure to model the blockchain as a _Directed Acylic Graph_ https://github.com/comit-network/comit-rs/blob/a32b6cbf904e68c6bec8dad856fc6a24c98ff763/btsieve/src/lib.rs#L44
* and an implementation to store incoming blocks and check for missed blocks in: https://github.com/comit-network/comit-rs/blob/a32b6cbf904e68c6bec8dad856fc6a24c98ff763/btsieve/src/bitcoin/mod.rs#L12-L43
--> The idea is to add the same abstraction for Ethereum next (TODO create new ticket) and then update the way of how blocks are being …
=> Detect missing block for bitcoin

btsieve/src/bitcoin/mod.rs, btsieve/src/ethereum/mod.rs, btsieve/src/lib.rs, btsieve/src/main.rs
=> Track blocks for ethereum

btsieve/src/ethereum/mod.rs
I split the changes into four commits with hopefully meaningful commit messages. Might be worth checking out to understand why I think it is now better :)
=> Minor simplifications to the recently added tests for implementation of the `Blockchain`-trait for Ethereum

Cargo.lock, vendor/blockchain_contracts/Cargo.toml, vendor/blockchain_contracts/src/bin/calculate_offsets/ethereum/mod.rs, vendor/blockchain_contracts/src/ethereum/mod.rs, vendor/blockchain_contracts/src/ethereum/to_ethereum_address.rs, vendor/blockchain_contracts/tests/ethereum_wallet/transaction.rs, vendor/blockchain_contracts/tests/ethereum_wallet/wallet.rs, vendor/blockchain_contracts/tests/htlc_harness/erc20_harness.rs, vendor/blockchain_contracts/tests/htlc_harness/ether_harness.rs, vendor/blockchain_contracts/tests/htlc_harness/mod.rs, vendor/blockchain_contracts/tests/parity_client/parity_client.rs, vendor/blockchain_contracts/tests/rfc003_erc20_htlc.rs, vendor/blockchain_contracts/tests/rfc003_ether_htlc.rs
Relates to coblox/blockchain-contracts#4
=> Remove ethereum_support dependency from blockchain_contracts

.circleci/config.yml
And wait for it to be dead, to avoid apt-lock issues.
Resolves #1231.
=> Kill apt-daily.service

cnd/src/config/file.rs
1. We already depend on tempfile, might as well use it
2. This makes sure we have a different tmp file for each test-run
3. We don't have to bother with the cleanup ourselves
=> Use tempfile library instead of hardcoded tmp file

api_tests/yarn.lock
Lockfile is out of sync for some reason
=> Fix lockfile

api_tests/harness.ts, api_tests/lib/actor.ts
=> Fix listen address and log if we fail to cleanup resources

.dependabot/config.yml
=> Fix invalid dependabot config

.mergify.yml
=> Fix mergify config

.mergify.yml
The PR #1352 updated the configuration only for dependabot PRs.
=> Update mergify config for 2nd rule

CHANGELOG.md, Cargo.lock, btsieve/Cargo.toml, cnd/Cargo.toml
We need this for the docker images in create-comit-app.
=> Release version 0.2.1

btsieve/src/bitcoin/bitcoind_connector.rs, btsieve/src/bitcoin/mod.rs, btsieve/src/bitcoin/quickcheck_impls.rs, btsieve/src/ethereum/mod.rs, btsieve/src/ethereum/queries/mod.rs, btsieve/src/ethereum/queries/transaction.rs, btsieve/src/ethereum/quickcheck_impls.rs, btsieve/src/lib.rs, btsieve/src/quickcheck.rs, internal/bitcoin_support/src/lib.rs
=> Fix flaky quickcheck test in btsieve module

CHANGELOG.md, cnd/src/bitcoin.rs, cnd/src/http_api/mod.rs, cnd/src/http_api/routes/rfc003/accept.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/lib.rs, cnd/src/swap_protocols/ledger/bitcoin.rs, cnd/src/swap_protocols/rfc003/bitcoin/mod.rs, cnd/src/swap_protocols/rfc003/state_store.rs, internal/bitcoin_support/src/lib.rs, internal/bitcoin_support/src/pubkey.rs
=> Replace PubkeyHash with PublicKey

.mergify/config.yml
=> Instruct bors to automatically merge dependabot PRs

.github/workflows/stale-bot.yml
Feel free to propose alternative timeouts
resolves: coblox/admin#93
=> Stale bot init

btsieve/src/bitcoin/blockchain_info_connector.rs
When doing property based testing on a hash data field (of type
`String`) quickcheck generates input that causes a panic.  The generated
input is not possible during normal program flow.  To inhibit quickcheck
from generating input that is not useful to us we can use a specific
type instead of a string.  We already have code in tree doing the same
sort of thing, we can do the same here.
Use `bitcoin_support::BlockId` instead of `String`.
Resolves: #1506
=> Use BlockId instead of String

.github/workflows/stale.yml
=> Yet another fix for stale action

.github/workflows/stale.yml
Let's try to fire it every hour for now. Same setup as in coblox/admin, just different timing.
=> Github stale actions - this should work now

cnd/src/comit_api/mod.rs
=> Add test for COMIT API Ledger headers

.mergify/config.yml
Work towards coblox/admin#118 (bring automatic merging back) + delete branches when PR is merged.
=> mergify: Tell bors to merge if there are 2 approvals

.circleci/config.yml, api_tests/lib/actor.ts, api_tests/lib/config.ts, cnd/src/main.rs
Fixes https://github.com/comit-network/comit-rs/issues/1265.
I didn't add it to `cargo make ci` because I would need to wait for the cache download down. I opted for failing as fast as possible.
=> Fail the CI if we find a TODO or FIXME in the code

cnd/src/db/load_swaps.rs, cnd/src/db/mod.rs
Add unimplemented skeleton for the `LoadAcceptedSwaps` interface.
=> Add LoadAcceptedSwaps interface

cnd/src/bitcoin.rs, cnd/src/db/custom_sql_types.rs, cnd/src/db/load_swaps.rs, cnd/src/db/new_types.rs, cnd/src/swap_protocols/rfc003/secret.rs
Implement `LoadAcceptedSwaps` for all supported combinations of Bitcoin/Ethereum - BTC/Ether/Erc20.
=> Implement LoadAcceptedSwaps for combinations

CHANGELOG.md, api_tests/lib/config.ts, cnd/src/config/file.rs, cnd/src/config/mod.rs, cnd/src/config/settings.rs, cnd/src/http_api/route_factory.rs, cnd/src/main.rs
=> Configure CORS

cnd/src/db/save_message.rs
@D4nte I thought about your feedback that the macro can complicate things and came to the conclusion that it is actually not worth having :)
=> Inline `impl_save_message` macro

CHANGELOG.md, api_tests/dry/sanity.ts, cnd/src/http_api/problem.rs
=> Identify error responses correctly as problems

CHANGELOG.md
No update to the changelog was done during any of the database PRs.  Now that the database implementation is merged we should mention it in the changelog.
=> Update CHANGELOG for recent database work

Makefile
=> Fix make install path

Cargo.lock, cnd/Cargo.toml, cnd/src/db/custom_sql_types.rs, libp2p-comit/Cargo.toml
=> Remove unused dependencies

Cargo.lock, api_tests/dry/rfc003_schema.ts, cnd/src/http_api/swap_resource.rs
=> Don't use invalid link relations in cnd's API

.circleci/config.yml
=> Skip CI build for non-source-code changes

.github/workflows/stale.yml
*for now once an hour. 
Once working we can change it to once a day.
Main change is that I use different intents now which seem to be working in another repository I found.
=> Run stale action once an hour

CHANGELOG.md, api_tests/dry/sanity.ts, cnd/src/http_api/route_factory.rs, cnd/src/http_api/routes/index/mod.rs
=> Return Siren links for /swaps and /swaps/rfc003 in index

.github/workflows/stale.yml
As of recommendation from https://github.community/t5/GitHub-Actions/Action-not-run-and-no-logs-available-action-stale/m-p/42810#M5125
=> Attempt to fix stale bot

.github/workflows/stale.yml
As of recommendation by: 
https://github.community/t5/GitHub-Actions/Action-not-run-and-no-logs-available-action-stale/m-p/42928#M5180
=> Trigger action manually by pushing to particular branch

libp2p-comit/src/handler.rs, libp2p-comit/src/substream/mod.rs, libp2p-comit/src/substream/outbound.rs
Fixes https://github.com/comit-network/comit-rs/issues/1210.
=> Remove WaitingOpen state

cnd/src/btsieve/bitcoin/mod.rs, cnd/src/btsieve/ethereum/mod.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/rfc003/bitcoin/htlc_events.rs, cnd/src/swap_protocols/rfc003/create_swap.rs, cnd/src/swap_protocols/rfc003/ethereum/htlc_events.rs, cnd/src/swap_protocols/rfc003/events/mod.rs, cnd/src/swap_protocols/rfc003/mod.rs, cnd/tests/bitcoin_helper/connector_mock.rs, cnd/tests/ethereum_missing_blocks.rs, cnd/tests/ethereum_old_blocks.rs, cnd/tests/ethereum_transaction_pattern_e2e.rs
=> Remove swap_protocols::rfc003::Error

api_tests/lib/config.ts, cnd/src/btsieve.rs, cnd/src/btsieve/bitcoin/bitcoind_connector.rs, cnd/src/btsieve/bitcoin/blockchain_info_connector.rs, cnd/src/btsieve/bitcoin/mod.rs, cnd/src/btsieve/ethereum/web3_connector.rs, cnd/src/config/settings.rs, cnd/src/http_api/problem.rs, cnd/src/http_api/routes/rfc003/handlers/action.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/init_swap.rs, cnd/src/libp2p_comit_ext.rs, cnd/src/logging/initialize.rs, cnd/src/main.rs, cnd/src/network/mod.rs, libp2p-comit/src/behaviour.rs, libp2p-comit/src/handler.rs
With this applied the alice logs for btc_eth happy path e2e test look like this:
```
cat api_tests/log/cnd-alice.log
Using config file /tmp/ce24b192-32ea-4ffa-808c-3d9527064279/config.toml
Initializing logging with base level TRACE
[2019-12-24 09:33:46.399][INFO][cnd::seed:75] No seed file found, creating at: /tmp/tmp-9341F4RJkyANdk51/seed.pem
[2019-12-24 09:33:46.497][INFO][cnd::db:66] SQLite database file: /tmp/tmp-9341F4RJkyANdk51/cnd.sqlite
[2019-12-24 09:33:46.500][INFO][cnd:68] Starting with peer_id: QmTH2GwivoaZzdeJ3MLFyxkrjh1uKMpa1j2wSCWQJYVUp8
[2019-12-24 09:33:46.504][DEBUG][cnd::load_swaps:32] loading swaps from database ...
[2019-12-24 09:33:46.505][INFO][cnd:153] Starting HTTP server on 0.0.0.0:45063
[2019-12-24 09:33:50.571][TRACE][cnd::http_api::routes::rfc003::handlers::pos …
```
=> Improve current logging

Cargo.lock, cnd/Cargo.toml, cnd/src/btsieve.rs, cnd/src/btsieve/bitcoin/bitcoind_connector.rs, cnd/src/btsieve/bitcoin/blockchain_info_connector.rs, cnd/src/btsieve/bitcoin/mod.rs, cnd/src/btsieve/ethereum/mod.rs, cnd/src/btsieve/ethereum/web3_connector.rs, cnd/tests/bitcoin_helper/connector_mock.rs, cnd/tests/ethereum_helper/connector_mock.rs
This PR submits a bunch of follow-up patches for https://github.com/comit-network/comit-rs/pull/1860.
They are best explained through their individual commit messages.
=> Follow-up PR for refactoring Ethereum's `matching_transaction` to use a generator

cnd/src/swap_protocols/ledger/bitcoin.rs, cnd/src/swap_protocols/ledger/ethereum.rs, cnd/src/swap_protocols/ledger/mod.rs, cnd/src/swap_protocols/mod.rs, cnd/src/swap_protocols/rfc003/bitcoin/mod.rs, cnd/src/swap_protocols/rfc003/ethereum/mod.rs, cnd/src/swap_protocols/rfc003/ledger.rs
* remove swap_protocols::Ledger
* add functionality to rfc003::Ledger
according to spike: 0019-domain-model
Fixes #1830.
=> merge the two ledger traits into one

api_tests/lib/ledger_runner.ts, cnd/src/asset/bitcoin.rs, cnd/src/asset/mod.rs, cnd/src/comit_api/mod.rs, cnd/src/db/integration_tests.rs, cnd/src/db/load_swaps.rs, cnd/src/db/save.rs, cnd/src/db/with_swap_types.rs, cnd/src/http_api/action.rs, cnd/src/http_api/mod.rs, cnd/src/http_api/swap_resource.rs, cnd/src/load_swaps.rs, cnd/src/quickcheck.rs, cnd/src/swap_protocols/actions.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/rfc003/actions/bitcoin.rs, cnd/src/swap_protocols/rfc003/bitcoin/htlc_events.rs, cnd/src/swap_protocols/rfc003/bitcoin/mod.rs, cnd/src/swap_protocols/rfc003/state_store.rs, cnd/tests/bitcoin_transaction_pattern_e2e.rs
wrap `bitcoin::Amount` in `asset::Bitcoin`
=> bitcoin asset

api_tests/lib/bitcoin.ts, api_tests/lib_sdk/actors/actor.ts, api_tests/lib_sdk/wallets/bitcoin.ts, api_tests/lib_sdk/wallets/ethereum.ts, api_tests/lib_sdk/wallets/index.ts, api_tests/types/bitcoin-core/index.d.ts
An attempt to fix our e2e tests :)
=> Wait for expiry time to pass before triggering refund

cnd/Cargo.toml, cnd/src/btsieve/ethereum/web3_connector.rs, cnd/src/ethereum.rs, cnd/src/main.rs, cnd/tests/ethereum_transaction_pattern_e2e.rs
Fixes #1718.
This is the MVP of #1718. It includes _some_ duplication. Can be removed in future iterations.
=> Replace web3 with reqwest

cnd/src/btsieve/ethereum/mod.rs
Time is a funny thing; when we talk about time it is not always precisely clear
what we mean, special care should be taken so as not to be ambiguous.
The term 'past' is ambiguous, it could mean the time has 'passed' or that a
certain time is past another (worse still, this can be in either direction).
We can use the term 'predates' when discussing two times, this term is
unambiguous.  If time A predates time B it means exactly that event that
occurred at time A occurred chronologically before an event that occurred at
time B - there is no other interpretation.
Use 'predates' in the code and documentation instead of 'past'.
=> Clarify direction of time

api_tests/harness.ts, api_tests/lib_sdk/actor_test.ts, api_tests/lib_sdk/actors/actor.ts, cnd/src/btsieve/ethereum/web3_connector.rs, cnd/src/swap_protocols/rfc003/create_swap.rs
Another attempt of making e2e test failures easier to debug.
=> Better logs

api_tests/lib_sdk/actors/actor.ts
Minor grammar fix in e2e tests.
=> Use correct word 'inexistent' -> 'non-existent'

cnd/src/btsieve/ethereum/mod.rs, cnd/src/lib.rs, cnd/src/swap_protocols/rfc003/create_swap.rs
This is safer than a potential panic branch.
=> Replace unreachable with never type

cnd/src/bitcoin.rs, cnd/src/db/save.rs, cnd/src/http_api/mod.rs, cnd/src/swap_protocols/rfc003/bitcoin/mod.rs, cnd/src/swap_protocols/rfc003/state_store.rs
Not sure I made it better.
For sure we need the tests in case rust-bitcoin change their serialisation behaviour.
=> Prefer usage of standard traits

cnd/src/db/load_swaps.rs
Trying to slightly alleviate the work for when I am going to multiple the number of variants by 3 (from Bitcoin to bitcoin::Mainnet, bitcoin::Regtest, bitcoin::Test.
=> Macro in load swaps

Cargo.lock, cnd/Cargo.toml, cnd/src/db/mod.rs, cnd/src/db/swap.rs, cnd/src/db/swap_types.rs, cnd/src/lib.rs, cnd/src/network/mod.rs, cnd/src/seed.rs, cnd/src/swap_protocols/facade.rs
Found this crate the other day. Support for generic traits is coming soon, so hopefully we will be able to remove all of this boilerplate eventually :)
What do you guys think of this?
Cool or too much magic?
=> Forward all non-generic traits in Facade using the ambassador crate

Cargo.lock, cnd/Cargo.toml
Fixes https://github.com/comit-network/comit-rs/issues/1940
=> Use native tls

Cargo.lock, cnd/Cargo.toml, cnd/src/db/wrapper_types/mod.rs, cnd/src/http_api/mod.rs, cnd/src/network/mod.rs, cnd/src/quickcheck.rs, cnd/src/seed.rs
See individual commit messages for more information.
=> Cleanup cnd dependencies

cnd/src/db/integration_tests/db_roundtrips.rs, cnd/src/db/load_swaps.rs, cnd/src/db/save.rs, cnd/src/db/swap_types.rs, cnd/src/db/with_swap_types.rs, cnd/src/db/wrapper_types/mod.rs, cnd/src/http_api/mod.rs, cnd/src/http_api/routes/rfc003/accept.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/network/mod.rs, cnd/src/quickcheck.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/ledger/bitcoin.rs, cnd/src/swap_protocols/rfc003/actions/bitcoin.rs, cnd/src/swap_protocols/rfc003/bitcoin/htlc_events.rs, cnd/src/swap_protocols/rfc003/bitcoin/mod.rs, cnd/src/swap_protocols/rfc003/ledger.rs
Follow-up of comments made on #1948
=> Ledgers represent Bitcoin networks: follow-up

Cargo.toml, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/init_swap.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/rfc003/bitcoin/htlc_events.rs, cnd/src/swap_protocols/rfc003/create_swap.rs, cnd/src/swap_protocols/rfc003/ethereum/htlc_events.rs, cnd/src/swap_protocols/rfc003/events/mod.rs
=> Split HtlcEvents

api_tests/lib_sdk/actors/actor.ts
Simple refactor, done as part of working on https://github.com/comit-network/comit-rs/issues/1951
=> Add helper function to get actor's role

CHANGELOG.md, Cargo.lock, cnd/Cargo.toml, cnd/src/asset/ethereum/erc20.rs, cnd/src/bitcoin.rs, cnd/src/btsieve/bitcoin/bitcoind_connector.rs, cnd/src/btsieve/bitcoin/cache.rs, cnd/src/btsieve/bitcoin/mod.rs, cnd/src/btsieve/bitcoin/transaction_ext.rs, cnd/src/btsieve/bitcoin/transaction_pattern.rs, cnd/src/btsieve/ethereum/transaction_pattern.rs, cnd/src/http_api/mod.rs, cnd/src/quickcheck.rs, cnd/src/swap_protocols/rfc003/actions/erc20.rs, cnd/src/swap_protocols/rfc003/actions/ether.rs, cnd/src/swap_protocols/rfc003/ethereum/htlc_events.rs, cnd/src/swap_protocols/rfc003/ethereum/mod.rs, cnd/tests/bitcoin_helper/connector_mock.rs
Resolves comit-network/blockchain-contracts#40
=> Upgrade blockchain-contracts to 0.3.1

Cargo.lock, cnd/Cargo.toml, cnd/src/db/load_swaps.rs, cnd/src/db/save.rs, cnd/src/http_api/swap_resource.rs, cnd/src/quickcheck.rs, cnd/src/swap_protocols/facade.rs
I've created a proc-macro on the plane as an experiment to explore ways on how we can cut down on some of the code duplication.
I don't know the situation of your PRs @D4nte but maybe my macro can help you in moving faster (by having to write/change less code)!
Feel free to close if it is inappropriate at this stage :)
=> Cut down duplication with impl-template and generics

.circleci/config.yml, CONTRIBUTING.md, README.md, api_tests/lib/bitcoind_instance.ts, api_tests/lib/cnd_runner.ts, api_tests/lib/config.ts, api_tests/lib/ledger_runner.ts, api_tests/lib/util.ts, api_tests/lib_sdk/actors/actor.ts, api_tests/lib_sdk/lnd.ts, api_tests/lib_sdk/utils.ts, api_tests/package.json, api_tests/sanity/basic_lnd_payment.ts, api_tests/sanity/config.toml, api_tests/types/ln-service/index.d.ts, api_tests/yarn.lock
The output of this PR:
- lnds are started for the actors
- lnd wallets are initialised
- RPC clients are ready
- lnds public keys are printed in logs
helps with #1951
=> Start lnd in e2e tests

CHANGELOG.md, Cargo.lock, cnd/Cargo.toml
This is to ensure we have the latest changelog in the dev branch.
=> Merge release branch of 0.6.0 back into dev

api_tests/lib/bitcoin.ts, api_tests/lib/ledger_runner.ts, api_tests/lib/util.ts, api_tests/lib_sdk/actors/actor.ts, api_tests/lib_sdk/ledger.ts, api_tests/lib_sdk/lnd.ts, api_tests/lib_sdk/wallets/bitcoin.ts, api_tests/lib_sdk/wallets/index.ts, api_tests/lib_sdk/wallets/lightning.ts, api_tests/sanity/basic_lnd_payment.ts, api_tests/sanity/config.toml, api_tests/types/ln-service/index.d.ts, cnd/src/btsieve/bitcoin/mod.rs
_99%_
Added minting and the connection to a peer as part of the infrastructure setup.
Works towards #1951.
next PR(s): Open channel, add invoice, send payment, assert payment.
=> e2e lnd: mint, addPeer

api_tests/lib_sdk/actors/actor.ts, api_tests/lib_sdk/asset.ts, api_tests/lib_sdk/lnd.ts, api_tests/lib_sdk/wallets/lightning.ts, api_tests/sanity/basic_lnd_payment.ts, api_tests/types/ln-service/index.d.ts
1. Automatically opens a channel in the right direction when doing `Actor.sendRequest()` with a `Lightning` ledger.
1. Bob adds an invoice
1. Alice pays the invoice
1. Bob verifies the invoice is paid
Resolves #1951.
=> e2e setup for lnd: open channel, add invoice, pay invoice, assert settlement

cnd/src/db/with_swap_types.rs, cnd/src/http_api/routes/rfc003/accept.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/http_api/routes/rfc003/swap_state.rs, cnd/src/http_api/swap_resource.rs, cnd/src/init_swap.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/rfc003/bitcoin/htlc_events.rs, cnd/src/swap_protocols/rfc003/create_swap.rs, cnd/src/swap_protocols/rfc003/ethereum/htlc_events.rs, cnd/src/swap_protocols/rfc003/events/mod.rs, cnd/src/swap_protocols/rfc003/ledger_state.rs
First PR, will try to find more after lunch. 100% review.
Works towards #2037
=> Relax trait bound on structs

api_tests/e2e/rfc003/eth_btc/bitcoin_high_fee.ts, api_tests/harness.ts, api_tests/lib/actor_test.ts, api_tests/lib/actors/actor.ts, api_tests/lib/bitcoin.ts, api_tests/lib/cnd/cnd_instance.ts, api_tests/lib/ethereum.ts, api_tests/lib/ledgers/bitcoind_instance.ts, api_tests/lib/ledgers/ledger_runner.ts, api_tests/lib/ledgers/lnd.ts, api_tests/lib/ledgers/parity_instance.ts, api_tests/lib/util.ts, api_tests/lib/utils.ts, api_tests/lib/wallets/bitcoin.ts, api_tests/lib/wallets/lightning.ts, api_tests/tslint.json
We've been bitten by bad usage of promises in the past (comparing them, not awaiting them, etc).
This PR activates several lints and fixes the respective problems. There are not that many but when reading through the [list of lints](https://palantir.github.io/tslint/rules/), several bugs crossed my mind that would have been caught by these lints.
This PR also inspired [a ticket on the SDK repo](https://github.com/comit-network/comit-js-sdk/issues/130), where we should likely do the same (probably even stricter).
=> Activate several lints in regards to promises and async fn

cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/rfc003/actions/bitcoin.rs, cnd/src/swap_protocols/rfc003/actions/erc20.rs, cnd/src/swap_protocols/rfc003/actions/ether.rs, cnd/src/swap_protocols/rfc003/actions/mod.rs, cnd/src/swap_protocols/rfc003/bitcoin/htlc_events.rs, cnd/src/swap_protocols/rfc003/bitcoin/mod.rs, cnd/src/swap_protocols/rfc003/create_swap.rs, cnd/src/swap_protocols/rfc003/ethereum/htlc_events.rs, cnd/src/swap_protocols/rfc003/ethereum/mod.rs, cnd/src/swap_protocols/rfc003/events/mod.rs
=> Relax trait bound htlc params

.github/workflows/cargo-audit.yml
=> Run `cargo-audit` on a schedule to report unmaintained dependencies

api_tests/dry/lightning_routes.ts, api_tests/dry/multiple_peers.ts, api_tests/dry/rfc003_swap_reject.ts, api_tests/lib/actors/actor.ts, api_tests/package.json, api_tests/yarn.lock, cnd/src/http_api/route_factory.rs, cnd/src/http_api/routes/index/mod.rs, cnd/src/main.rs
=> Add Lightning routes

logo.svg
Update logo to latest version from notion
=> Update logo to version without TM

api_tests/dry/multiple_peers.ts, api_tests/dry/peers_using_ip.ts, api_tests/dry/rfc003_schema.ts, api_tests/dry/rfc003_swap_reject.ts, api_tests/dry/sanity.ts, api_tests/lib/actor_test.ts
=> Update dry test names

cnd/src/btsieve/bitcoin/mod.rs, cnd/src/btsieve/bitcoin/transaction_pattern.rs, cnd/src/swap_protocols/rfc003/bitcoin/htlc_events.rs, cnd/tests/bitcoin_go_back_into_the_past.rs, cnd/tests/bitcoin_missed_previous_latest_block.rs, cnd/tests/bitcoin_transaction_pattern_e2e.rs
Reverts comit-network/comit-rs#2098
We are reverting this because it causes e2e test failures.
=> Revert "Bitcoin matching transactions refactor"

api_tests/dry/rfc003_swap_reject.ts
=> Make sure Bob processed the swaps before asserting on them

cnd/src/config/settings.rs
Generalise the macaroon location logic and add functions for locating the lnd tls cert and key.
Note, this also makes the assumption that all lnd files, if in the cnd data directory will be in a sub-directory called `lnd`.  This is done, as commented in the code, so we can use generic terms like `tls.cert` as are used by lnd.
Question: Are these functions defined in the right place?
=> 1952 follow up - Improve lnd helper functions

libp2p-comit/src/frame/codec.rs, libp2p-comit/src/frame/request.rs, libp2p-comit/src/frame/response.rs, libp2p-comit/src/handler.rs, libp2p-comit/src/lib.rs, libp2p-comit/src/protocol.rs, libp2p-comit/src/substream/inbound.rs, libp2p-comit/src/substream/outbound.rs
This clean up PR is a result of reading our libp2p code in preparation for the LN communication protocol epic.
=> Libp2p clean up

api_tests/lib/actors/actor.ts, api_tests/lib/wallets/index.ts, api_tests/lib/wallets/lightning.ts, api_tests/package.json, api_tests/sanity/hold_lnd_payment.ts, api_tests/yarn.lock
Also integrates changes from comit-network/comit-js-sdk#145.
=> Follow-up of #2107

.github/workflows/draft-new-release.yml, RELEASING.md
=> Add new release workflow based on creating GitHub issues

cnd/src/btsieve/bitcoin/mod.rs, cnd/src/btsieve/ethereum/cache.rs, cnd/src/btsieve/ethereum/mod.rs, cnd/src/btsieve/ethereum/web3_connector.rs, cnd/src/btsieve/mod.rs, cnd/tests/ethereum_helper/connector_mock.rs
This is a follow up of #1878  
You can take a look at the commits, I would leave these three steps and don't squash them together (all of them are clean). If you don't like that please comment.
=> Generic `find_relevant_blocks` for Bitcoin and Ethereum

Cargo.lock, cnd/Cargo.toml, cnd/src/btsieve/ethereum/web3_connector.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/jsonrpc.rs, cnd/src/lib.rs, cnd/src/main.rs, cnd/src/network/mod.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/rfc003/create_swap.rs, cnd/tests/ethereum_transaction_matching_smoke_test.rs
Resolves #2080 
Resolves #2156.
I couldn't remove the extended stack size unfortunately :(
=> Finalize async await

cnd/src/btsieve/bitcoin/bitcoind_connector.rs, cnd/src/btsieve/bitcoin/cache.rs, cnd/src/btsieve/ethereum/cache.rs, cnd/src/btsieve/ethereum/web3_connector.rs, cnd/src/btsieve/mod.rs, cnd/tests/bitcoin_helper/connector_mock.rs, cnd/tests/ethereum_helper/connector_mock.rs
This trait doesn't use this associated type, we can simply remove it.
Big LOL on this one :D
=> Remove unused BlockHash associated type from LatestBlock

cnd/src/swap_protocols/rfc003/ethereum/mod.rs
Found this while playing around with our new Ethereum types :)﻿
=> Remove dead code from inside Ethereum module

cnd/src/btsieve/mod.rs
None of the predicate implementations make use of the error case, meaning we can just remove this and simplify it to a bool.
=> Remove unnecessary Result type

cnd/src/btsieve/mod.rs
This patch improves the walk_back_until algorithm by removing the duplication at the beginning the function. With some simple re-orderings and re-assignments, we can remove a call to `clone` on the block and remove the duplication in the `stop_condition` check which is now named `should_stop_here` to be more descriptive.
=> Simplify the `walk_back_until` algorithm

cnd/src/http_api/routes/rfc003/handlers/action.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/http_api/swap_resource.rs, cnd/src/init_swap.rs, cnd/src/network/mod.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/rfc003/create_swap.rs, cnd/src/swap_protocols/state_store.rs
Fixes #2213.
Instead of StateStore there is Insert, Get, Update.
We did this as prep for https://github.com/comit-network/comit-rs/issues/2195
=> Split up the StateStore traits by function

CHANGELOG.md, Cargo.lock, cnd/Cargo.toml
The release failed because the workflow file had an error but we still need to merge this back in.
=> Merge release branch back into dev

.github/workflows/lint-workflow-files.yml, .github/workflows/publish-new-release.yml, .spectral.yml, CHANGELOG.md
Unfortunately, the GH release workflow was broken because yaml files are a fucking mess to work with.
Added a linter that catches basic mistakes.
THIS IS A HOTFIX RELEASE OF MASTER!
=> Release version 0.7.1

cnd/src/main.rs
This PR contains two patches with separate ideas for the config validation.
Not sure if the combinators are more readable than what was there before. To me, they seem to be superior because we don't have to manually `match` on the result but can just `?` as usual.
This works because `downcast` returns an error if the downcast fails, which in our case means the error was not a connection error but something else.
=> Small follow-up PR for the validation of the blockchain connectors

Makefile
Because I already almost did the mistake with PR #2226.
=> Do not keep track of Cargo.toml files to avoid missing new ones

.github/workflows/trigger-sync-labels.yml
Already tested on comit-js-sdk.
For coblox/admin#85
=> Add trigger to sync labels

api_tests/package.json, api_tests/src/actors/actor.ts, api_tests/src/actors/defaults.ts, api_tests/tests/dry/lightning_routes.ts, api_tests/yarn.lock
Draft until https://github.com/comit-network/comit-js-sdk/pull/169 is merged
=> Upgrade comit-sdk to 0.15.0

cnd/src/swap_protocols/ledger_states.rs, cnd/src/swap_protocols/rfc003/create_swap.rs, cnd/src/swap_protocols/state.rs
Some things I came across while we are hacking on the LN implementation :)
=> Simplify states and traits

cnd/src/network/protocols/announce/handler.rs
We currently have a mix of queue'ing logic in the handler.  Fix to use
`VecDeque` for both the `events` queue and the `dial_queue`.  Use these
queues as FIFO, push to the back and pop from the front.
Fixes: #2306
=> Fix handler queueing

cnd/src/network/protocols/announce/behaviour.rs
Add logic for managing connections from within the announce behaviour.
Fixes: #2311
=> Add connection logic

CHANGELOG.md, Cargo.lock, cnd/Cargo.toml
This PR merges the release branch for 0.7.2 back into dev.
=> Merge release 0.7.2 into dev branch

cnd/src/main.rs, cnd/src/network.rs
When starting cnd, if the HTTP port is in use, we would like to exit.  We can achieve this by checking if the port is available before trying to spawn the HTTP server.
This patch introduces a race condition between the call to `port_is_available()` and the actual spawn of the wrap server.  If we hit this race condition it is non-critical, it just means cnd will start without an HTTP server, the logs will still contain the bind error.
Fixes: #2290
=> Exit cnd if HTTP port is in use

api_tests/src/actors/swap_factory.ts, api_tests/tests/ether_halight.ts, api_tests/tests/lightning_routes.ts
=> Use swap factory for for all halight dry tests

cnd/src/btsieve/bitcoin/bitcoind_connector.rs
Fixes #2438 
Manually testing against a bitcoind testnet node worked.
=> Deserialization for networks main/test/regtest as retrieved by bitcoind

cnd/src/network/comit_ln.rs, cnd/src/swap_protocols.rs, cnd/src/swap_protocols/herc20.rs, cnd/src/swap_protocols/herc20/connector_impls.rs
=> Add herc20 protocol

api_tests/tests/lightning_routes.ts, cnd/src/http_api/route_factory.rs, cnd/src/http_api/routes.rs, cnd/src/http_api/routes/index.rs, cnd/src/network.rs, cnd/src/network/comit_ln.rs, cnd/src/swap_protocols/facade2.rs
=> Make `Body` for new routes generic

.github/workflows/ci.yml, CHANGELOG.md, cnd/src/lib.rs
=> Fix and enable windows builds

.github/workflows/ci.yml, README.md, api_tests/package.json, api_tests/src/actors/actor.ts, api_tests/src/ledgers/lnd_instance.ts, api_tests/tests/bitcoin_ethereum.ts, api_tests/tests/ethereum_bitcoin.ts, api_tests/yarn.lock
=> Use lnd binary instead of compiling it in the e2e tests

Makefile
Edit: Does not c.l.o.s.e #2474 due to debate present in the issue but does the foundation work.
Note: We still have few errors but I don't think it matters:
```
error: toolchain '1.42.0-x86_64-apple-darwin' is not installed
error: toolchain 'nightly-2020-01-15-x86_64-apple-darwin' is not installed
```
=> Do not install Rust if the executed task does not need it

cnd/src/main.rs, cnd/src/network.rs
Previously, we used a mix of `Runtime::block_on` and `Runtime::spawn`
to kick off all the important background worker processes that make
cnd work.
This patch harmonizes this usage by:
- Always using `Runtime::spawn` to spawn background workers
- Always using `Runtime::block_on` to execute code that should
run synchronously as we start up cnd.
To achieve this, we separate binding to the socket for the HTTP API
(something that should happen synchronously during startup because
we want to terminate if we fail) from the actual worker future
that handles the incoming requests.
We also separate creating an instance of `Swarm` from actually
spawning the background worker to align it with the HTTP API
background worker.
This introduces the `std::thread::park` function call again to idle
the main …
=> Harmonize usage of async fn when deal with HTTP and networking code

.github/workflows/ci.yml, .mergify.yml, bors.toml
Windows build is taking ages, this we can optimize the
run.
=> Start e2e tests as soon as ubuntu build is done

cnd/src/swap_protocols/halight/connector.rs
Resolves #2429 
Was trickier than expected... why does json have "null" values 🙄
=> Use custom deserializer for lightning r_preimage

.gitignore, api_tests/package.json, api_tests/src/setup_chai.ts, api_tests/tests/peers_using_ip.ts, api_tests/tests/rfc003_schema.ts, api_tests/tests/siren_schema.ts, api_tests/yarn.lock
- Migrate more chai expect to jest expect
- Remove chai-http and chai-as-promised deps
Helps with #2139
=> Remove chai-http

cnd/src/btsieve/ethereum.rs, cnd/src/btsieve/ethereum/cache.rs, cnd/src/btsieve/ethereum/web3_connector.rs, cnd/src/ethereum.rs, cnd/tests/ethereum_helper/connector_mock.rs
removed option from hash of eth block struct
=> removed option from hash of eth block struct

CHANGELOG.md, api_tests/src/config.ts, cnd/src/config.rs, cnd/src/config/file.rs, cnd/src/config/settings.rs, cnd/src/main.rs
=> Replace `parity` config section with `web3_url`

.github/workflows/publish-new-release.yml, Makefile
resolves: #2242 
Note that so far the commands were only tested locally on my machine, I did not run the action on github-actions yet.
=> Test that cnd is reachable in created docker image before releasing 

cnd/src/http_api/action.rs, cnd/src/http_api/routes.rs, cnd/src/network/comit_ln.rs, cnd/src/swap_protocols/actions.rs, cnd/src/swap_protocols/facade.rs, cnd/src/timestamp.rs
=> Lnd expiries

cnd/src/network.rs, cnd/src/swap_protocols/halight.rs, cnd/src/swap_protocols/halight/connector.rs, cnd/src/timestamp.rs
Check whether the parameters specified in the invoice and payment
returned by lnd match the parameters specified in the swap
parameters. Remove fields from the invoice that are no being used.
Resolves #2395, #2430
=> Validate lnd invoice and payment against swap params

cnd/src/http_api/routes.rs
Name cleanup - missed one when changing `Han` to `Herc20`
=> Rename created state to reflect Herc20

cnd/src/comit_api.rs, cnd/src/db/created_swap.rs, cnd/src/db/integration_tests/api.rs, cnd/src/db/integration_tests/db_roundtrips.rs, cnd/src/db/load_swaps.rs, cnd/src/db/save.rs, cnd/src/db/swap_types.rs, cnd/src/db/with_swap_types.rs, cnd/src/db/wrapper_types.rs, cnd/src/http_api.rs, cnd/src/http_api/routes/index.rs, cnd/src/http_api/routes/rfc003/accept.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/network.rs, cnd/src/network/comit_ln.rs, cnd/src/quickcheck.rs, cnd/src/swap_protocols/halight.rs, cnd/src/swap_protocols/ledger.rs, cnd/src/swap_protocols/ledger/bitcoin.rs, cnd/src/swap_protocols/ledger/lightning.rs, cnd/src/swap_protocols/rfc003/actions/bitcoin.rs, cnd/src/swap_protocols/rfc003/actions/ether.rs, cnd/src/swap_protocols/rfc003/bitcoin.rs, cnd/src/swap_protocols/rfc003/bitcoin/htlc_events.rs, cnd/src/swap_protocols/rfc003/ethereum/htlc_events.rs, cnd/src/swap_protocols/rfc003_facade.rs
=> Go back to modelling Bitcoin ledgers as enums

cnd/migrations/2020-05-19-052851_rename-address-book/down.sql, cnd/migrations/2020-05-19-052851_rename-address-book/up.sql, cnd/src/db.rs, cnd/src/db/integration_tests/db_roundtrips.rs, cnd/src/db/save_load_impls/created_swaps.rs, cnd/src/db/schema.rs, cnd/src/db/tables.rs
=> Refactor address_hint to address-book table

cnd/src/db/tables.rs
Resolves #2603
Unless I'm misunderstanding this, it looks like fk relations are enforced.
=> Ensure fk relation is enforced

cnd/src/db/tables.rs
=> 2648 validate table update

cnd/src/db/save_load_impls.rs, cnd/src/http_api/problem.rs, cnd/src/http_api/routes.rs, cnd/src/network.rs, cnd/src/swap_protocols.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/halight.rs, cnd/src/swap_protocols/herc20.rs, comit/src/btsieve/herc20_connector_impls.rs, comit/src/halight.rs, comit/src/herc20.rs, comit/src/lnd.rs
...by implementing a generic way that works for the single protocol pair `herc20-halight`.
=> Keep paving the way for handling multiple SwapKinds

cnd/src/http_api.rs, cnd/src/http_api/halight.rs, cnd/src/http_api/halight_herc20.rs, cnd/src/http_api/halight_herc20/alice.rs, cnd/src/http_api/halight_herc20/bob.rs, cnd/src/http_api/herc20.rs, cnd/src/http_api/herc20_halight.rs, cnd/src/http_api/herc20_halight/alice.rs, cnd/src/http_api/herc20_halight/bob.rs, cnd/src/http_api/problem.rs, cnd/src/http_api/protocol.rs, cnd/src/http_api/routes.rs, cnd/src/network/comit.rs, cnd/src/storage.rs, cnd/src/swap_protocols/halight.rs
Implement GET for herc20-halight and halight-herc20.
=> Introduce genericity into the controller

cnd/src/main.rs
=> Print panic messages using tracing

cnd/src/http_api/routes.rs
Because this is not javascript.
=> Use a typed enum instead of string slice

cnd/src/http_api/halight_herc20/alice.rs, cnd/src/http_api/halight_herc20/bob.rs, cnd/src/http_api/herc20_halight/alice.rs
I have spotted some inconsistencies in the matching arms.
See commit messages for more details.
=> Fix logic in actions

api_tests/tests/erc20_halight.ts, api_tests/tests/halight_erc20.ts
=> Await promises now that it returns when payment is in flight

CHANGELOG.md, cnd/src/http_api/halight_herc20/alice.rs, cnd/src/http_api/halight_herc20/bob.rs, cnd/src/http_api/herc20_halight/alice.rs, cnd/src/http_api/herc20_halight/bob.rs, cnd/src/http_api/protocol.rs, cnd/src/http_api/routes.rs
A couple of follow up patches to the recent RUA work.
- Patch 1: Use 'ledger' instead of 'blockchain'
- Patch 2: Update the changelog
=> Rua follow up

cnd/src/facade.rs, cnd/src/http_api/route_factory.rs, cnd/src/http_api/routes.rs, cnd/src/http_api/routes/index.rs, cnd/src/http_api/routes/post.rs, cnd/src/lib.rs, cnd/src/main.rs, cnd/src/swap_protocols.rs, cnd/src/swap_protocols/facade.rs
Clean up the facade by removing dead code (hbit digest stuff) and moving the facade module to the root cnd module. Each patch has a commit message justifying itself.
=> Facade clean up

api_tests/package.json, api_tests/src/actors/actor.ts, api_tests/tests/erc20_halight.ts, api_tests/tests/halight_erc20.ts, api_tests/tests/rfc003_schema.ts, api_tests/yarn.lock
Last PR for the Recommend Unique Action project.
=> Use `nextAction` from SDK

api_tests/src/actors/rfc003_actor.ts
This has been fixed with @types/jest@25.2.3
=> Remove unnecessary ts-ignore

api_tests/src/actors/actor.ts, api_tests/src/actors/swap_factory.ts, api_tests/tests/halight_herc20.ts, api_tests/tests/hbit_herc20.ts, api_tests/tests/herc20_halight.ts, api_tests/tests/herc20_hbit.ts, cnd/src/http_api/herc20_hbit/alice.rs
Almost exclusively TS changes after a little bit of debugging.
I would be happy to refine some e2e test suite APIs, because I probably modified things too fast.
Also, I believe there is no way to "refund" Halight, so I don't know if I should assert anything about lightning (or bitcoin) at the end of `alice-refunds-bob-refunds` tests.
=> Herc20 hbit refund

api_tests/tests/herc20_halight_respawn.ts, api_tests/tests/herc20_hbit_respawn.ts, cnd/migrations/2020-06-04-011540_swap_timestamp/down.sql, cnd/migrations/2020-06-04-011540_swap_timestamp/up.sql, cnd/src/db.rs, cnd/src/db/integration_tests/load_protocol_combination.rs, cnd/src/db/save_load_impls.rs, cnd/src/db/schema.rs, cnd/src/db/tables.rs, cnd/src/http_api.rs, cnd/src/http_api/routes.rs, cnd/src/http_api/routes/index.rs, cnd/src/lib.rs, cnd/src/network.rs, cnd/src/proptest.rs, cnd/src/respawn.rs, cnd/src/start_swap.rs, cnd/src/storage.rs, comit/src/lnd.rs
=> Respawn feature

api_tests/src/actors/actor.ts, api_tests/src/swap_response.ts, cnd/src/http_api/halight_herc20/alice.rs, cnd/src/http_api/halight_herc20/bob.rs, cnd/src/http_api/hbit_herc20/alice.rs, cnd/src/http_api/hbit_herc20/bob.rs, cnd/src/http_api/herc20_halight/alice.rs, cnd/src/http_api/herc20_halight/bob.rs, cnd/src/http_api/herc20_hbit/alice.rs, cnd/src/http_api/herc20_hbit/bob.rs, cnd/src/http_api/protocol.rs, cnd/src/http_api/routes.rs
I looked into it and did not find any reason to include ledger events for halight.
=> Return ledger events in swap response for hbit and herc20

cnd/migrations.sh
Decided to add this now because it helps when being offline.
=> Check if diesel-cli is available or install

.github/workflows/ci.yml
Turns out what I did in https://github.com/comit-network/comit-rs/pull/2830 was total garbage :D
This PR fixes that.
=> Make caches actually useful

api_tests/src/actor_test.ts, api_tests/src/actors/actor.ts, api_tests/src/actors/index.ts, api_tests/src/config.ts, api_tests/src/utils.ts, api_tests/tests/multiple_peers.ts, api_tests/tests/peers_using_ip.ts
One of the seminal words in the field of cryptography is Bruce
Schneier's Applied Cryptography. In this text the players involved in
cryptographic protocols are:
Alice, Bob, Carol, Dave: 1st, 2nd, 3rd, 4th participants respectively
Eve: Eavesdropper
Mallory: Malicious active attacker
Trent: Trusted arbitrator
Walter: Warden (guards Alice and Bob sometimes)
Peggy: Prover
Victor: Verifier
We use, by design or good fortune, Alice and Bob already. Our third
participant is currently name Charlie. We can tip our hat to Bruce
Schneier by using his player names.
Use Carol for the name of third participant instead of Charlie.
=> Use Carol for the name of third participant

.mergify.yml
For more context, see https://github.com/Mergifyio/mergify-engine/issues/1176.
=> Force delete head branches

cnd/src/http_api/herc20.rs, comit/src/herc20.rs
=> Stop using unnecessary Result types

cnd/src/storage.rs
Improve rustdoc in the storage module.
=> storage: Improve documentation

comit/src/network/comit.rs
Attempt to simplify the `finalize` logic by doing an early return any time a condition is not met (incl. code comment as to why).
If none of the return statements are hit then we are ready to finalize.
=> Refactor finalize logic

api_tests/src/actor_test.ts, api_tests/src/configure_jasmine.ts, api_tests/types/jasmine/index.d.ts
=> Remove ts-ignore directives

cnd/src/http_api/protocol.rs, cnd/src/storage.rs, cnd/src/storage/db/integration_tests/serialization_format_stability.rs, cnd/src/storage/db/tables.rs, cnd/src/storage/db/wrapper_types.rs, cnd/src/storage/http_api.rs, comit/src/btsieve/ethereum.rs, comit/src/btsieve/ethereum/cache.rs, comit/src/btsieve/ethereum/web3_connector.rs, comit/src/ethereum.rs, comit/src/lib.rs, comit/src/proptest.rs
The planned PR retargeting didn't quite work so I have to merge #2900 through a new PR.
=> Clone of #2900

Cargo.lock, cnd/Cargo.toml, cnd/src/http_api/action.rs, cnd/src/http_api/problem.rs, cnd/src/network.rs, comit/Cargo.toml
Removes an overall of 26 dependencies from our dependency chain :tada:
=> Optimize dependencies

CHANGELOG.md, cnd/src/lib.rs
Caused by https://github.com/comit-network/comit-rs/pull/2923.
=> Update changelog with new config dir

cnd/src/local_swap_id.rs, cnd/src/main.rs, cnd/src/network.rs, comit/src/lib.rs, comit/src/network.rs, comit/src/network/protocols/announce.rs, comit/src/network/shared_swap_id.rs
=> Replace LocalSwapId in Announce protocol with generic context

comit/src/hbit.rs, comit/src/herc20.rs, comit/src/network/protocols/orderbook.rs
Small changes to allow comit lib integration in nectar.
=> Nectar new orderbook

README.md
and in the blockchain swap them.
=> One chat to bring them all

.github/workflows/ci.yml
We are getting strange CI errors. The only know way to clear the cache
is by changing the cache key.
=> Change the cache key

Cargo.lock, comit/src/network/orderbook.rs, comit/src/network/orderbook/order.rs
This PR is some the initial pre-work patches from https://github.com/comit-network/comit-rs/pull/2983
This stuff is useful on its own even though the motivation comes from the forex work.
Please review carefully the functions added/modified in the `ethereum` module.
=> Pre-work from the forex terminology PR

comit/src/expiries.rs, comit/src/expiries/config.rs, comit/src/order.rs
Now with unit tests!
First patch re-designs the API inline with recent orderbook changes. Second patch adds unit tests, big up @D4nte for the inspiration.
=> Standardized COMIT Expiry Times

api_tests/src/actors/actor.ts, api_tests/src/payload.ts, api_tests/tests/orderbook_dry.ts, cnd/src/http_api/orders.rs, cnd/src/http_api/orders/get_single.rs, cnd/src/http_api/orders/list_open_orders.rs, cnd/src/http_api/route_factory.rs, cnd/src/storage/db/schema.rs, cnd/src/storage/db/tables.rs
This includes orders that are currently being settled. Those are
still returned but can not longer be cancelled.
=> Implement endpoint for listing all open orders

comit/src/network/orderbook.rs
needed for https://github.com/coblox/nectar/pull/112
=> Minor changes for nectar upgrade to latest comit

Cargo.lock, cnd/src/network/comit_node.rs, cnd/src/network/swarm.rs, cnd/src/storage/db/tables.rs, cnd/src/storage/db/tables/btc_dai_orders.rs, cnd/src/storage/db/tables/halbits.rs, cnd/src/storage/db/tables/hbits.rs, cnd/src/storage/db/tables/herc20s.rs, cnd/src/storage/db/tables/order_hbit_params.rs, cnd/src/storage/db/tables/order_herc20_params.rs, cnd/src/storage/db/tables/order_swaps.rs, cnd/src/storage/db/tables/orders.rs, cnd/src/storage/db/tables/secret_hashes.rs, cnd/src/storage/db/tables/swap_contexts.rs, cnd/src/storage/db/tables/swaps.rs
This patch doesn't change any functionality but just moves code
around.
=> Modularize `tables` module into one per database table

nectar/src/network.rs
The position impacts the protocol pair we use, not the role.
=> Nectar always acts as Bob

Cargo.lock, nectar/Cargo.toml, nectar/src/bitcoin/wallet.rs, nectar/src/config.rs, nectar/src/config/file.rs, nectar/src/history.rs, nectar/src/swap/db.rs
See https://rustsec.org/advisories/RUSTSEC-2018-0017.html
=> Replace deprecated `tempdir` with `tempfile`

Cargo.lock, comit/src/expiries.rs, comit/src/network/protocols/setup_swap.rs, comit/src/order.rs, comit/src/orderpool.rs, nectar/Cargo.toml, nectar/src/trace.rs
This series of patches improves logging in nectar and the orderbook.
=> Improve logging

nectar/src/command/trade.rs, nectar/src/network.rs, tests/package.json, tests/src/actor_test.ts, tests/src/actors/nectar_actor.ts, tests/src/environment/fake_treasury_service.ts, tests/src/environment/index.ts, tests/src/environment/nectar_config.ts, tests/src/environment/nectar_instance.ts, tests/tests/cnd_and_nectar.ts, tests/tests/nectar_instance.spec.ts
=> Add an e2e test between nectar and cnd

cnd/src/http_api/swaps.rs
Instead of pre-maturely fetching the current time from the blockchain
connectors, we pass the future along and only await it if we run
into a refund scenario and need to compare it to the expiry time.
This should significantly speed up calls to GET /swap in any other
case.
=> Only talk to the blockchain nodes if really necessary
