application/comit_node/src/swap_protocols/rfc003/ethereum/contract_templates/erc20_contract.asm, application/comit_node/src/swap_protocols/rfc003/ethereum/contract_templates/ether_contract.asm, application/comit_node/tests/htlc_harness/erc20_harness.rs, application/comit_node/tests/htlc_harness/ether_harness.rs, application/comit_node/tests/htlc_harness/mod.rs, application/comit_node/tests/rfc003_bitcoin_htlc.rs, application/comit_node/tests/rfc003_erc20_htlc.rs, application/comit_node/tests/rfc003_ether_htlc.rs
Ensure that the secret length sent to HTLC is as expected.
This mitigates a security issue where a shorter secret could be used to redeem.
See the commit the history where the security vulnerability is proven.
Resolves #433 
---
=> Check secret length in ERC20 & ETH HTLCs

CONTRIBUTING.md, README.md
As per feedback in #613, added more details on how to run tests.
Also explains the labels related to issues for wanna-be contributors
---
=> Adds commonly used `cargo make` tasks

api_tests/dry/rfc003/test.js, application/comit_node/src/bin/comit_node.rs, application/comit_node/src/comit_client/bam.rs, application/comit_node/src/comit_client/fake.rs, application/comit_node/src/comit_client/mod.rs, application/comit_node/src/comit_server.rs
=> Add inbound connections to client pool

Cargo.lock, Cargo.toml, Makefile.toml, application/comit_node/Cargo.toml, application/ledger_query_service/Cargo.toml, vendor/bitcoin_rpc_test_helpers/Cargo.toml, vendor/bitcoin_witness/Cargo.toml, vendor/tc_bitcoincore_client/Cargo.toml, vendor/tc_web3_client/Cargo.toml
testcontainers was updated to default to parity 2.1.3 and bitcoind 0.17.0.
Updating comit-rs to use latest testcontainers version.
=> Update testcontainers to use parity 2.1.3 across the board

application/comit_node/src/comit_client/bam.rs, application/comit_node/src/comit_server.rs, vendor/bam/src/api.rs, vendor/bam/src/connection.rs, vendor/bam/src/json/frame.rs, vendor/bam/tests/bi_directional.rs, vendor/bam/tests/common/alice_and_bob.rs
While doing #439, I noticed some things that were in my way, so here is a separate PR for them.
Main achievements:
- `Connection` struct is gone and is now a simple constructor function that returns `impl Future`
- the "connection` is decoupled from the actual frame types (request and response)
=> Decouple config from connection

Makefile.toml
Stop e2e script creating folders when passing invalid argument to `cargo make e2e`.
Resolves #596
=> Do not proceed if invalid e2e folder

.mergify.yml, README.md, application/comit_node/build.rs
Update README after compiling comit-rs in docker.
Also fix a mergify corner case where mergify would fail if there is no "review" label to remove.
No codecov as it looks like tarpaulin cannot compile with C-bindings (and codecov is not critical so we do not want to spend more time on this).
=> Update README + Fix mergify corner case

api_tests/ledger_query_service/test.js, application/ledger_query_service/src/bin/ledger_query_service.rs, application/ledger_query_service/src/bitcoin/block_processor.rs, application/ledger_query_service/src/bitcoin/mod.rs, application/ledger_query_service/src/bitcoin/queries.rs, application/ledger_query_service/src/ethereum/block_processor.rs, application/ledger_query_service/src/ethereum/queries.rs, application/ledger_query_service/src/lib.rs
With #647, the ledger query service has been split up into two, since the implementations for bitcoin and ethereum cannot be easily generalised anymore. This PR removes all the unnecessary traits that were still hanging around in `ledger_query_service/src/bitcoin`.
Additionally, `PendingTransaction` has been removed, because the feature was not being used and was poorly implemented to begin with.
Resolves #646.
=> Bitcoin LQS cleanup

application/comit_node/src/ledger_query_service/client.rs, application/comit_node/src/ledger_query_service/ethereum.rs, application/comit_node/src/swap_protocols/rfc003/ethereum/mod.rs, application/comit_node/src/swap_protocols/rfc003/ethereum/queries.rs, application/ledger_query_service/src/ethereum/queries/event_query.rs
With this PR the COMIT node makes use of the new LQS features. 
In detail:
* check for logs if ERC20/ETH HTLC has been redeemed
* check for logs if ERC20/ETH HTLC has been refunded
* check for logs if funded
for the first one I had to make a small change on the LQS side: the `expand` now returns a `Transaction` and not a `TransactionReceipt` as the secret is not yet emitted in the logs. 
This needs to be fixed when doing #638.
Fixes #563
=> 563 use new lqs features

application/comit_node/src/swap_protocols/rfc003/bitcoin/htlc.rs, application/comit_node/src/swap_protocols/rfc003/ethereum/erc20_htlc.rs, application/comit_node/src/swap_protocols/rfc003/ethereum/ether_htlc.rs
These log statements were introduced at a time where the COMIT node
would still deploy stuff by themselves. However, we no longer that.
Instead, we tell the user, what to do by returning "actions" over the
HTTP API. This means, whatever was logged here is actually returned
to the user and doesn't add any value in the log file.
Fixes #690.
=> Remove noisy log messages

application/comit_node/config/development.toml, application/comit_node/src/bin/comit_node.rs, application/comit_node/src/logging.rs, application/comit_node/src/settings/mod.rs, application/comit_node/src/settings/serde/log_level.rs, application/comit_node/src/settings/serde/mod.rs
Fixes #711 
Adds a log_level (default: debug) under each heading in the settings and uses that to determine the relevant LogFilter in `logging.rs`.
=> Add log_level option to settings

.idea/swap.iml, Cargo.lock, Cargo.toml, application/comit_node/Cargo.toml, vendor/noise_handshake/Cargo.toml, vendor/noise_handshake/src/handshake.rs, vendor/noise_handshake/src/lib.rs
=> Noise Handshake Future

application/comit_node/tests/ethereum_wallet/transaction.rs
Ethereum apparently expects that signature components do not start
with 0x00 (i.e be treated as RLP integers) Why? No body knows.
So we have to wrap the (R,s) values in U256s so they encode properly.
🤦
Fix #740.
=> Fix RLP encoding error

application/comit_node/src/ledger_query_service/client.rs
So as I expected, this is a bad idea:
See https://travis-ci.com/comit-network/comit-rs/builds/100021198
```
[2019-02-07 01:07:54.483][comit_node::ledger_query_service::fetch_transaction_stream][WARN] Falling back to empty list of transactions because FailedRequest("Failed to fetch full results for \"http://localhost:8080/queries/bitcoin/transactions/1?expand_results=true\" because Inner { kind: Json(Error(\"unknown field `query`, expected `matches`\", line: 1, column: 8)), url: None }")
```
I will not make deserialization stricter, issue updated.
Resolves #727
=> Fix LQS Client test

vendor/bam/src/json/frame.rs
As per RFC1, responses that fail to deserialize should simply be logged.
This is a follow-up to merging https://github.com/comit-network/RFCs/pull/29
=> Resolve TODO

vendor/bitcoin_rpc_test_helpers/src/lib.rs
It tried to duplicate the code as mentioned in #699, but it is actually too much of a hassle. The functions are quite helpful.
I just think that the TODO is actually not valid. It is perfectly fine to have crates that are only used in testing (see `testcontainers`) and they still are not under `#[cfg(test)]`.
#699 will be closed with this PR being merged by the TODO bot.
=> Remove TODO in bitcoin_rpc_test_helpers

.mergify.yml
We should use draft PRs instead of "WIP" in title.
Remove mergify rules that messes up with labels when "WIP" is in label
Resolves #780
=> Use draft PR instead of WIP title

Makefile.toml, api_tests/yarn.lock
Prettier ignores node_modules by default so we can just pass a
glob string for all .js files to it.
=> Use more-concise prettier configuration

Makefile.toml
`sh` does not support `[[`.
Also, better to just upgrade yarn as it's fast
=> Fix warning in build process

api_tests/dry/multiple_peers.js, api_tests/dry/rfc003_swap_reject.js, api_tests/e2e/rfc003/btc_eth-erc20/test.js, api_tests/e2e/rfc003/btc_eth/test.js, api_tests/e2e/rfc003/eth-erc20_btc/test.js, api_tests/e2e/rfc003/eth_btc/test.js, application/comit_node/src/http_api/mod.rs, application/comit_node/src/http_api/problem.rs, application/comit_node/src/http_api/rfc003/action.rs, application/comit_node/src/http_api/rfc003/handlers/get_action.rs, application/comit_node/src/http_api/rfc003/handlers/get_swap.rs, application/comit_node/src/http_api/rfc003/handlers/get_swaps.rs, application/comit_node/src/http_api/rfc003/handlers/mod.rs, application/comit_node/src/http_api/rfc003/handlers/post_action.rs, application/comit_node/src/http_api/rfc003/mod.rs, application/comit_node/src/http_api/rfc003/routes.rs, application/comit_node/src/http_api/route_factory.rs, application/comit_node/src/swap_protocols/rfc003/alice/actions/mod.rs, application/comit_node/src/swap_protocols/rfc003/bob/actions/mod.rs
Add parameters and actions to `GET swapS` response.
Also "fix" tests to test for type (using `===`).
Resolves #776
=> Add actions to GET swaps

api_tests/e2e/rfc003/btc_eth-erc20/test.js, api_tests/e2e/rfc003/btc_eth/test.js, api_tests/e2e/rfc003/eth-erc20_btc/test.js, api_tests/e2e/rfc003/eth_btc/test.js, api_tests/harness.js, api_tests/lib/bitcoin.js, api_tests/lib/ethereum.js, api_tests/lib/wallet.js, api_tests/package.json, api_tests/yarn.lock
When verifying that a redeem transaction has been successful, instead of watching the recipient's Bitcoin address using a Bitcoin RPC client we now look at the transaction itself using `getRawTransaction(txid)`.
Also test suite logs have been removed because no one is looking at them anymore.
Resolves #698.
Resolves #681.
=> Verify Bitcoin redeem transaction using transaction ID

.travis.yml, Makefile.toml, README.md, api_tests/npm_wrapper.sh, api_tests/package.json
This PR removes any usage of `nvm` from the project.
Instead, we fail the build if the available node version is not `11.10`. This means we now have to install that version in Travis.
This also means that *you* (@comit-network/rust-devs) have to setup your environment so that node version 11.10 is used inside the project directory. How you do that is left up to you :)
This hopefully fixes #802.
=> Make sure we always run against node 11.10

application/comit_node/src/swap_protocols/rfc003/bitcoin/htlc.rs, vendor/bitcoin_support/src/lib.rs, vendor/bitcoin_support/src/network.rs, vendor/bitcoin_support/src/pubkey.rs, vendor/key_gen/src/main.rs
Replace `rust-bitcoin::Network` with own `Network` enum so that mainnet is called mainnet and not bitcoin...
Resolves #644.
=> Use Network::Mainnet instead of Network::Bitcoin

api_tests/dry/sanity.js, application/comit_node/src/http_api/route_factory.rs
This allows any application to use the HTTP API of a COMIT node.
=> Add CORS headers to comit_node HTTP API

Cargo.lock, api_tests/btsieve/test.js, api_tests/harness.js, api_tests/regtest/alice/default.toml, api_tests/regtest/bob/default.toml, api_tests/regtest/btsieve/default.toml, api_tests/regtest/charlie/default.toml, application/btsieve/config/default.toml, application/btsieve/src/bin/btsieve.rs, application/btsieve/src/route_factory.rs, application/btsieve/src/routes.rs, application/btsieve/src/settings/mod.rs, application/comit_node/config/default.toml, application/comit_node/src/bin/comit_node.rs, application/comit_node/src/btsieve/client.rs, application/comit_node/src/settings/mod.rs, vendor/bitcoin_support/Cargo.toml, vendor/bitcoin_support/src/lib.rs, vendor/bitcoin_support/src/network.rs, vendor/ethereum_support/Cargo.toml, vendor/ethereum_support/src/lib.rs, vendor/ethereum_support/src/network.rs, vendor/tc_web3_client/Cargo.toml
btsieve supports now a ledger network e.g. 
`/queries/bitcoin/regtest/*` or `/queries/ethereum/regtest/*`, ... 
I decided for a path param as the `network` is part of the ledger and not part of the query, i.e. if you create a query for `/queries/ethereum/transactions` with an additional field or a query param, we would need to check on the btsieve side manually while using the path param a 404 is automatically returned if the network is not supported. 
This network is part of the ledger configuration in the config file of btsieve. 
Resolves #815
=> Add btsieve support for ledger networks

Cargo.lock, vendor/key_gen/Cargo.toml, vendor/key_gen/src/main.rs
Add ability to specify private key as hex as argument to keygen
And:
- Stop logging the output
- Remove a bunch of unused stuff
=> Add ability to specify private key as hex as argument to keygen

application/comit_node/src/bam_api/mod.rs, application/comit_node/src/bam_api/rfc003/swap.rs, application/comit_node/src/swap_protocols/dependencies/client_impl.rs
- Ledger and asset names to lowercase in BAM.
- `swap_protocol` BAM header to `protocol`.
Same was done for the HTTP API in #821.
Resolves #643.
=> Further align implementation with RFC002

Cargo.lock, Cargo.toml, application/btsieve/Cargo.toml, application/comit_node/Cargo.toml, vendor/bitcoin_rpc_test_helpers/Cargo.toml, vendor/bitcoin_witness/Cargo.toml, vendor/tc_bitcoincore_client/Cargo.toml
Change now possible that bitcoin_rpc_client 0.6.0 is published
=> Use override for bitcoin_rpc_client to avoid git branch everywhere

Makefile.toml
See https://github.com/sagiegurari/cargo-make/issues/217
Makefile alias should not contain `workspace` keyword.
Bug that allowed that was fixed with cargo-make 0.17
=> Fix Makefile

.circleci/config.yml, Makefile.toml
Simple circle ci setup.
Last build duration: 17:48 minutes
Currently we are only able to go for machine executors.
The reason is, we would need docker in docker. This is generally supported by circle ci, however, they only provide a remote docker host, which is currently not supported by testcontainer-rs. 
If we fix this in testcontainer-rs, we can probably optimize the build time.
=> Initial circle ci setup

README.md, application/btsieve/config/default.toml
Updates `Build & Run` section. 
Related fix for the `default.toml` of `btsieve`.
=> Update setup in README to current version

Cargo.lock, README.md, api_tests/harness.ts, api_tests/lib/actor.ts, application/comit_node/Cargo.toml, application/comit_node/src/bin/comit_node.rs, application/comit_node/src/lib.rs, application/comit_node/src/load_settings.rs
If no argument passed, it falls back to ~/.config/comit_node
Once this is approved/merged, I'll also do it for btsieve
Resolves #876
=> Allow config dir path to be passed via command line

vendor/blockchain_contracts/src/bin/calculate_offsets/ethereum/rfc003/offset.rs
Correct output now is:
```
** Ether on Ethereum **
Contract template:
6120026110016000396120026000f336156051576020361415605c57602060006000376020602160206000600060026048f17f1000000000000000000000000000000000000000000000000000000000000001602151141660625760006000f35b42632000000210609f575b60006000f35b7fb8cac300e37f03ad332e581dea21b2f0b84eaaadc184a295fef71e81f44a741360206000a1733000000000000000000000000000000000000003ff5b7f5d26862916391bf49478b2f5103b0720a842b45ef145a268f2cd1fb2aed5517860006000a1734000000000000000000000000000000000000004ff
| Name | Byte Range | Length (bytes) |
|:--- |:--- |:--- |
| `secret_hash` | 51..83 | 32 |
| `refund_timestamp` | 99..103 | 4 |
| `redeem_address` | 153..173 | 20 |
| `refund_address` | 214..234 | 20 |
** ERC20 on Ethereum **
Contract template: …
```
=> Fixes offset print order

application/comit_node/src/http_api/routes/index/handlers/get_swaps.rs, application/comit_node/src/http_api/swap_resource.rs, vendor/siren/src/types.rs
- Add method to `siren::Entity` which inserts an element in an entity's class property.
- Use new method when building `GET /swaps` and `GET /swaps/rfc003/:id` responses.
Added to be able to realise comit-network/comit-i#61.
=> Use class property in siren entities

.dependabot/config.yml
We are no longer using waffle and hence we deleted the label.
=> Remove `groomed` as the default label from dependabot

README.md
comit-rs depends on OpenSSL.  We recently removed the instruction, lets add it
back in.
Add setup instruction for Ubuntu to install OpenSSL.
=> Add setup instructions for SSL (Linux)

api_tests/dry/peers_using_ip.ts, application/comit_node/src/libp2p_bam/behaviour.rs, application/comit_node/src/network.rs
Introducing the "dial to IP feature" actually introduced a bug into the network layer where we are dropping connections because we dial twice to the same node.
By revising how we are using the address hint, we solve this problem and actually get the behavior @LLFourn was vouching for: Not connecting to a node if the we supply an address that doesn't resolve to the given ID.
=> No longer drop it like it's hot

application/comit_node/src/seed.rs
We don't want to display seeds (including debug output).   Implement dummy methods for
Display trait and Debug trait.  Add test to ensure the dummy implementations don't get
changed.
Fixes #722
=> Ensure seeds cannot be printed

.gitignore
Tooling (Emacs) generates an artifact 'TAGS'.  We don't want this in version
control, direct git to ignore it.
=> Add TAGS file to gitignore (emacs)

Cargo.lock, Cargo.toml, application/btsieve/Cargo.toml, application/btsieve/src/bin/btsieve.rs, application/btsieve/src/bitcoin/queries/block.rs, application/btsieve/src/bitcoin/queries/transaction.rs, application/btsieve/src/route_factory.rs, application/comit_node/Cargo.toml, application/comit_node/tests/rfc003_bitcoin_htlc.rs, vendor/bitcoin_rpc_test_helpers/Cargo.toml, vendor/bitcoin_rpc_test_helpers/src/lib.rs, vendor/bitcoin_support/src/network.rs, vendor/bitcoin_witness/Cargo.toml, vendor/bitcoin_witness/tests/p2wpkh.rs, vendor/bitcoin_witness/tests/sign_with_rate.rs, vendor/tc_bitcoincore_client/Cargo.toml, vendor/tc_bitcoincore_client/src/lib.rs
Fixes: #680.
Post-merge tasks:
=> Replace our bitcoin-rpc-client with bitcoincore-rpc

api_tests/regtest/btsieve/bitcoin_only/btsieve.toml, api_tests/regtest/btsieve/btsieve.toml, api_tests/regtest/btsieve/ethereum_only/btsieve.toml, api_tests/regtest/btsieve/no_ledger/btsieve.toml, application/btsieve/config/btsieve.toml, application/btsieve/src/logging.rs, application/btsieve/src/settings/mod.rs
The log level of btsieve was not parsed correctly due to the missing header.
=> Fix log_level parsing for btsieve

.dependabot/config.yml
Because if the tests pass and it is approved then there is no
reasons to not let mergify handle it.
=> Add automagically-mergify-this label by default

.githooks/pre-commit
Currently our git pre-commit hook runs the Typescript format checker and the Rust format checker.  The Typescript checker is slow because it invokes `yarn`.  If a commit only modifies Rust source files there is no need to run the Typescript checker.  Also when modifying only Typescript it is unnecessary to check the format of the Rust code.
Add clause to the pre-commit hook shell script to only run language specific format checkers if source files of that language were modified.
Only tested on Linux `GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)`
=> Check format based on file suffix

application/comit_node/src/http_api/impl_serialize_http.rs, application/comit_node/src/http_api/mod.rs
We currently have some duplicate code when implementing `Serialize` for `Http<T>` types in the REST API code.  We can reduce code duplication by defining a macro.
This PR renames the current `impl_serialize_http` to `impl_serialize_type_name_with_fields` then implements a new version of `impl_serialize_http` for the simple case where we just serialize `self.0`.
=> Implement HTTP serialization macro

application/comit_node/src/http_api/mod.rs
We would like to test that the HTTP API primitive types serialize as expected.  Here we add unit tests that test the serialization as it is now (i.e. passing tests).  This makes the format on the wire explicit and if the serialization code changes ever these tests will catch the change.
Fixes #766
=> Add unit tests for HTTP API primitive types

btsieve/src/load_settings.rs, comit_node/src/load_settings.rs
We should not use hard coded paths.  This makes assumptions about the operating
system that COMIT runs on.  Rust provides `PathBuf` construction mechanisms so as
to be OS independent, we should use them.
Remove hard coded paths i.e. "path/to/foo" and construct the path using a
`PathBuf`.
=> Remove hard coded paths

.githooks/pre-commit, Cargo.toml, Makefile.toml, vendor/bitcoin_rpc_test_helpers/Cargo.toml, vendor/bitcoin_support/Cargo.toml, vendor/bitcoin_witness/Cargo.toml, vendor/blockchain_contracts/Cargo.toml, vendor/comit_i/Cargo.toml, vendor/ethereum_support/Cargo.toml, vendor/siren/Cargo.toml, vendor/tc_bitcoincore_client/Cargo.toml
Formatting is good, in case of Cargo.toml it helps with PR merging
when 2 concurrent PRs add dependencies.
Stealing from #771. Now acceptable that the list in root Cargo.toml is short.
Please note I also tried out https://crates.io/crates/toml-fmt but it messes with deps and is a pain to use.
=> Introduce Cargo.toml formatting to avoid manual sorting

README.md
The configuration instructions for `btsieve` and and `comit_node` are
stale.  We should update them to match the code.
=> Update stale config file instructions

Cargo.toml, btsieve/Cargo.toml, comit_node/Cargo.toml, vendor/key_gen/Cargo.toml
Using the same notation for both, registry and path dependencies, allows us to:
1. Keep all of them alphabetically sorted
2. Reduce the length of the file
Both things should make it easier to maintain the manifest files.
=> Unify the way we specify dependencies in Cargo.toml

.dependabot/config.yml
Mainly to avoid having to do it manually.
Resolves #977
=> Configure dependabot to update e2e tests dependencies

api_tests/e2e/rfc003/btc_eth-erc20/happy.ts, api_tests/e2e/rfc003/btc_eth/happy.ts, api_tests/e2e/rfc003/btc_eth/inverted-refund.ts, api_tests/e2e/rfc003/btc_eth/refund.ts, api_tests/e2e/rfc003/eth-erc20_btc/happy.ts, api_tests/e2e/rfc003/eth-erc20_btc/refund.ts, api_tests/e2e/rfc003/eth_btc/happy.ts, api_tests/e2e/rfc003/eth_btc/refund_beta.ts, api_tests/e2e/test_creator.ts
While investigating #1026 (closed, found to be invalid) it was discovered that the e2e test runner did not correctly handle running tests due to an asynchronous call.   Commit 1 fixes this issue.  Commit 2 adds a passing test that verifies that Alice can refund first (even though this is _not_ the expected order of refunds).
=> Add test where Alice refunds first

api_tests/lib/actor.ts, api_tests/lib/ethereum.ts, comit_node/src/http_api/action.rs, comit_node/src/swap_protocols/actions.rs, comit_node/src/swap_protocols/rfc003/actions/erc20.rs, comit_node/src/swap_protocols/rfc003/actions/ether.rs
Currently we use `bytes.default()` to generate an empty value for byte array `data` member of the `CallContract` structure.  This results in the value `0x` being used (I do not know the exact reason why or where this `0x` is found, please see note below on testing).  Rust has options for such a case.
This needs testing, I have no idea what will now be expressed by the `None` in place of the original `0x`.
Fixes: #999
=> Use Option for CallContract member 'data'

comit_node/src/http_api/mod.rs, comit_node/src/swap_protocols/rfc003/alice/spawner.rs, comit_node/src/swap_protocols/rfc003/bob/spawner.rs, comit_node/src/swap_protocols/rfc003/secret.rs, comit_node/src/swap_protocols/rfc003/state_machine.rs, rustfmt.toml, vendor/blockchain_contracts/tests/rfc003_erc20_htlc.rs, vendor/blockchain_contracts/tests/rfc003_ether_htlc.rs
Formatting code this way seems to be more natural to me and also saves a few lines of code.
=> Enable the 'overflow_delimited_expr' rustfmt option

vendor/bitcoin_support/src/network.rs
Using the correct bitcoin network version in btsieve. 
Btsieve tries to bind its query URLs to the actual blockchain network. For that, it fetches `getblockchaininfo` and retrieves: 
```
{
"chain": "test",
"blocks": 1570022,
"headers": 1570022,
"bestblockhash": "0000000000000312fecacee42bf7197da55c3db7c9c0002972cc0df9419302ee",
"difficulty": 4729661.074040298,
"mediantime": 1563758058,
"verificationprogress": 0.9999930258427291,
"initialblockdownload": false,
"chainwork": "00000000000000000000000000000000000000000000011fc91b669192dd70b1",
"size_on_disk": 24779445613,
"pruned": false,
"softforks": [
{
"id": "bip34",
"version": 2,
"reject": {
"status": true
}
},
{
"id": "bip66",
"version": 3,
"reject": {
"status": true
}
},
{
"id": "bip65",
"version": 4,
"reject": {
"status": true
}
}
], …
```
=> Use correct bitcoin network names

api_tests/package.json, api_tests/yarn.lock
We needed that for LN but that is no longer part of the repository.
Replaces #1115.
=> Remove grpc dependency

comit_node/src/btsieve/client.rs, comit_node/src/main.rs, comit_node/src/settings/mod.rs, vendor/bitcoin_support/src/network.rs, vendor/ethereum_support/src/network.rs
Fixes the bug that btsieve client tried to get queries for bitcoin fro
`"queries/bitcoin/{}/transactions", ethereum_network` and ethereum from 
`"queries/ethereum/{}/transactions", bitcoin_network`. 
This wasn't an issue for regtest, but becomes critical for ropsten, i.e. we just had : get bitcoin transaction from `queries/bitcoin/ropsten/transactions` ... which obviously didn't work
=> Fix btsieve-client network bug

vendor/bitcoin_support/src/network.rs, vendor/bitcoin_support/src/pubkey.rs, vendor/key_gen/src/main.rs
Apparently serde and strum are using different ways for serialization, one was configured and one was derived from the enum variant
=> Second fix of network serialization for serde

vendor/bitcoin_support/src/network.rs, vendor/bitcoin_support/src/pubkey.rs, vendor/key_gen/src/main.rs
Reverts comit-network/comit-rs#1127
Because comit-i is not yet updated and we don't want to start the breaking of apis just now. 
Hence, start with updating the RFCs: https://github.com/comit-network/RFCs/issues/101
and continue with creating sub-sequential tickets for cnd and comit-i
=> Revert "Second fix of network serialization for serde"

.circleci/config.yml
We want to delay all the `apt` stuff as long as possible so that we don't run into issues with other parts of the system having a lock on it.
=> FIX CIRCLE-CI: Run `restore_caches` and `setup_rust` steps before `setup_system`

api_tests/regtest/alice/cnd.toml, api_tests/regtest/bob/cnd.toml, cnd/src/config/config_file.rs
The default port for comit_node is 8011 which is just "can't use 8000 so let's
add 10 and then 1".
Change the default port to 9939 which is the value for the utf-8 "chains" emoji:
chains Reason: COMIT is here to facilitate cross-chains applications.
Fixes: #1012
=> Use port 9939 for cnd

vendor/blockchain_contracts/src/bitcoin/rfc003/bitcoin_htlc.rs
Moving the RFCs to AsciiDoc broke the link to the Bitcoin contract template in RFC005.
=> Update link to contract template in RFC005

api_tests/e2e/rfc003/btc_eth-erc20/happy.ts, api_tests/e2e/rfc003/btc_eth-erc20/refund_beta.ts, api_tests/e2e/rfc003/btc_eth/happy.ts, api_tests/e2e/rfc003/btc_eth/inverted_refund.ts, api_tests/e2e/rfc003/btc_eth/overfunded_htlc.ts, api_tests/e2e/rfc003/btc_eth/refund.ts, api_tests/e2e/rfc003/btc_eth/underfunded_htlc.ts, api_tests/e2e/rfc003/eth-erc20_btc/happy.ts, api_tests/e2e/rfc003/eth-erc20_btc/refund.ts, api_tests/e2e/rfc003/eth_btc/bitcoin_high_fee.ts, api_tests/e2e/rfc003/eth_btc/happy.ts, api_tests/e2e/rfc003/eth_btc/refund_beta.ts, api_tests/swap.schema.json, cnd/src/swap_protocols/rfc003/ledger_state.rs
As described in the issue; the ledger status currently uses Pascal case (upper camel case).  This is not uniform with other fields in the HTTP API.  We should use SCREAMING_SNAKE_CASE so as to be uniform.
This PR also adds the recently added status field `IncorrectlyFunded` to the API test scheme (seems to have been omitted when added to cnd).  Next we change the API test scheme to use SCREAMING_SNAKE_CASE, making the dry tests fail.  We add a failing unit test.  Then in patch 4 we fix cnd to use SCREAMING_SNAKE_CASE.  Patch 5 updates the e2e tests to reflect the case change.
Fixes: #845 and feels good!
=> 845 Improve homogenous HTTP API naming

Cargo.lock, cnd/src/swap_protocols/rfc003/bitcoin/mod.rs, vendor/blockchain_contracts/Cargo.toml, vendor/blockchain_contracts/src/bitcoin/mod.rs, vendor/blockchain_contracts/src/bitcoin/pubkey_hash.rs, vendor/blockchain_contracts/src/bitcoin/rfc003/bitcoin_htlc.rs, vendor/blockchain_contracts/src/fit_into_placeholder_slice.rs, vendor/blockchain_contracts/tests/rfc003_bitcoin_htlc.rs, vendor/secp256k1_support/src/keypair.rs
Related to coblox/blockchain_contracts#4
Note: Issue to be open to contribute the TODOs back, see coblox/blockchain_contracts#4.
=> Remove bitcoin_support dependency from blockchain_contracts

vendor/comit_i/version
comit-i 0.5.0-alpha includes google analytics tracking.
=> Bump comit-i version

.mergify.yml
Two reasons:
- rebase destroys commit signatures
- rebases spam the history of pull requests on GitHub
- in most cases, there should only be one merge commit because mergify queues up PRs
Resolves https://github.com/comit-network/comit-rs/issues/1018.
=> Don't rebase to update a branch

btsieve/src/load_settings.rs
Currently we hard code the `.config/` path.  We can be cross platform if we use the `directories` crate instead.
Implements solution to #1074 for btsieve.  cnd coming as a separate PR.
=> Use cross platform config directory

internal/secp256k1_keypair/src/keypair.rs
It is unlikely that this is accepted upstream. See https://github.com/rust-bitcoin/rust-secp256k1/issues/149.
=> Remove TODO

api_tests/lib/actor.ts
The bug described in #1232 is most likely caused by Alice funding the ERC20 contract before Bob can create the btsieve query to watch for said action. Since ([for the time being](https://github.com/comit-network/comit-rs/issues/1289)) btsieve only considers incoming blocks for new queries, Bob will never learn that the contract on alpha ledger was funded, so the swap will not continue.
In our tests, to get around the possibility that a ledger action may happen before one of the parties has created the corresponding btsieve query, we sleep for 1 second before we perform any ledger action.
It is safe to assume that this will almost never happen outside of testing, since ledger actions on production blockchains generally take longer than creating a query on btsieve. Nevertheless, adding the …
=> Wait 1 second before ledger actions in tests

cnd/src/http_api/with_swap_types.rs, cnd/src/swap_protocols/metadata_store.rs, cnd/src/swap_protocols/rfc003/alice/spawner.rs, cnd/src/swap_protocols/rfc003/bob/spawner.rs
Currently we use `AssetKind` and `LedgerKind` from the ledger module within the `Metadata` structure.  These are defined as enums with associated invariant data.  `MetadataStore` however ignores the additional invariant data. 
This was found to be problematic for writing/reading to and from a `MetadataStore` SQL backed database.
This PR adds a `LedgerKind` and `AssetKind` enum within the `metadata_store` module.  We implement the `From` trait to convert from `ledger::LedgerKind` and `ledger::AssetKind` respectively.
Fixes: #1301
=> Define enums for `AssetKind` and `LedgerKind`

btsieve/src/cli.rs, btsieve/src/load_settings.rs, btsieve/src/main.rs, btsieve/src/settings/mod.rs, cnd/src/config/file.rs
For the first out-of-sprint-scope day I chose to spend some time learning the `btsieve` codebase.  This PR is a result of that time.  Refactoring is limited to the config file / settings code including command line options.
Stripped down after comments from @thomaseizinger offline.
Also fixes: #1259 (tested on Linux, needs testing on OSX please @D4nte @da-kami or @bonomat)
=> Refactor btsieve

Cargo.lock, btsieve/Cargo.toml, btsieve/src/ethereum/queries/mod.rs, btsieve/src/ethereum/queries/quickcheck.rs, btsieve/src/ethereum/queries/transaction.rs
This PR just introduces an approach to property-based testing for the codebase. It is tied to a library choice, in this case [quickcheck](https://github.com/BurntSushi/quickcheck).
It introduces a tests-only `Quickcheck<T>` struct which can wrap around any type `T` for which we want to implement a trait (`quickcheck::Arbitrary`) that allows us to generate random values. This is done to circumvent [Rust orphan rules](https://github.com/Ixrec/rust-orphan-rules), which prevent us from implementing foreign traits on foreign types.
It only modifies one test, but if we like the idea we can extend it to more tests within btsieve.
=> Rewrite one test using property-based testing principles

.circleci/config.yml
Instead of `release/` so that when doing something specific to the
release build, the branch can be named `release-foo-bar` and run the
release build instead of being named `release/foo-bar`.
=> Allow release build to be done on branches with `release` prefix

.circleci/config.yml
Fixes #1366
Please note openssl is the only problematic library.
ZMQ is also an issue but will be removed with #1131.
All other dynamically linked libraries are system libraries:
```
linux-vdso.so.1 =>  (0x00007fff7bfef000)
libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fe6cd8fd000)
libzmq.so.5 => /usr/lib/x86_64-linux-gnu/libzmq.so.5 (0x00007fe6cd697000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe6cd493000)
librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe6cd28b000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe6cd06e000)
libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe6cce58000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe6cca8e000)
/lib64/ld-linux-x86-64.so.2 (0x00007fe6ce7de000)
libm.so.6 => …
```
=> Statically link latest openssl lib in release binary

Cargo.lock, cnd/Cargo.toml
`testcontainers` is an unused dev dependency in cnd.
=> Remove testcontainers dev dependency from cnd

.circleci/config.yml, Cargo.lock, blockchain_contracts/Cargo.toml, btsieve/Cargo.toml, cnd/Cargo.toml, internal/comit_i/Cargo.toml, internal/ethereum_support/Cargo.toml, internal/tc_web3_client/Cargo.toml
It does not fully remove the dependency as `internal/comit_i` needs TLS to fetch the comit-i bundle.
For some reason, this makes `cnd` executable linked to openssl even though it's only needed in the build.
To resolve that, we use the `vendored-tls` feature of `reqwest` for `internal/comit_i` which statically link openssl.
For the rest, `web3` and other `reqwest` imports, we deactivate default features to not depend on openssl.
openssl is still needed to test of course, but the resulting release binaries do not link to openssl:
```
linux-vdso.so.1 (0x00007ffe03ef2000)
libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f441c73e000)
librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f441c536000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f441c317000) …
```
=> Remove openssl static build in release CI

Cargo.lock, internal/comit_i/Cargo.toml, internal/comit_i/build.rs
Removed dependency on openssl as ureq uses rustls.
On `ubuntu:latest` Docker image (19.04):
```
▶ du -sh ./target/release/{cnd,btsieve}
33M     ./target/release/cnd
12M     ./target/release/btsieve
▶ du -s ./target/release/{cnd,btsieve}
33544   ./target/release/cnd
12104   ./target/release/btsieve
▶ du -sh ./target/release/{cnd,btsieve}
31M     ./target/release/cnd
12M     ./target/release/btsieve
▶ du -s ./target/release/{cnd,btsieve}
30728   ./target/release/cnd
12088   ./target/release/btsieve
```
2M saved on `cnd`.
=> Replace Reqwest with ureq

btsieve/src/bitcoin/bitcoind_http_blocksource.rs
While reviewing #1371, I noticed a couple of things that could be optimized.
Here is my attempt in doing so! :)
My main motivation was the implementation of the `remove_trailing_newline` function because it can actually we be replaced with `.trim()` since newlines are whitespaces characters. However, that led to it no longer being tested or at least the tests were no longer useful. Hence I got example responses from bitcoind and extracted the whole response decoding into a function again which makes to test (because the test actually fails if we don't include the `trim`).
I am opening this PR directly against #1371, however, feel free to merge #1371 first and then re-target this to master! Whatever you prefer :)
The PR contains three commits, each explaining why I am suggesting certain …
=> Couple of improvements to the BitcoindHttpBlockSource

blockchain_contracts/Cargo.toml, internal/tc_web3_client/Cargo.toml
Without this, master currently fails for a clean build.
=> Activate web3 http feature

blockchain_contracts/tests/ethereum_helper/to_ethereum_address.rs
The reason why the TODO was added was because the code should be moved eventually. Hence I think it is better suited if we have a dedicated clean-up ticket that includes this instead of a TODO on this repository.
Here is the follow-up ticket: https://github.com/coblox/blockchain-contracts/issues/9
=> Remove TODO in favor of dedicated ticket

Cargo.lock, cnd/Cargo.toml
This avoids a compile-time dependency on libsqlite3-dev and a runtime dependency on the shared libsqlite3 library.
=> Use the bundled feature of libsqlite3-sys

CHANGELOG.md, Cargo.lock, cnd/Cargo.toml
- Embed btsieve as a library inside cnd: From now on, you'll only need to run cnd to use COMIT.
Resolves #1474.
=> Release 0.3.0

cnd/src/http_api/problem.rs, cnd/src/http_api/routes/mod.rs
Removes the custom adaptor struct for HttpApiProblem that is no longer needed.
Closes #1437
=> Remove unnecessary adaptor

Cargo.lock, internal/bitcoin_rpc_test_helpers/Cargo.toml, internal/bitcoin_rpc_test_helpers/src/lib.rs, internal/bitcoin_support/src/pubkey.rs, internal/key_gen/Cargo.toml, internal/key_gen/src/main.rs
The functionality was only used in test code and there is no harm in inlining it because we are simply delegating to downstream functionality.
=> Remove IntoP2wpkhAddress trait

.circleci/config.yml
It looks like our trial is finished.
Docker layer caching is not available in the free plan:
```
Blocked due to free-plan-docker-layer-caching-unavailable
```
See https://circleci.com/gh/comit-network/comit-rs/2167?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link.
=> Remove Circle CI docker layer caching

.dependabot/config.yml
I propose to run dependabot daily instead of weekly.
With the configuration of mergify (#1531) and bors, there should be no issue in terms of blocking the CI (it also runs at midnight, none should be working around that time). There is also always the hardlimit on how many PRs are open.
cc @bonomat I remember you having objections against this in the past. I would be keen to try of how much of a burden it actually is. Can always switch it back if it really annoys us / takes up too much time.
=> Run dependabot daily

btsieve/src/bitcoin/mod.rs, btsieve/src/ethereum/mod.rs
This comment has caused some confusion in the team; attempt to improve it.
- 'the machine' is ambiguous - the machine we are running on, the machine the
blockchain connector is connecting to?  Use 'the CPU' instead since
non-ambiguously refers to the CPU running the current process.
- 'given the assumption' - this is not an assumption since it does not always
hold true, better to say 'in the event that'.
=> Improve comment explaining the delay

cnd/src/config/file.rs
Our codebase is small enough to maintain uniformity across it for simple
things.  When creating a closure that takes an error as parameter
typically we use the identifier 'e'.  Replace uses of 'error' to make
the codebase uniform in this respect.
=> Use 'e' instead of 'error' in closures

btsieve/src/bitcoin/mod.rs, btsieve/src/bitcoin/transaction_pattern.rs, btsieve/src/ethereum/mod.rs, btsieve/src/ethereum/transaction_pattern.rs, btsieve/src/lib.rs, btsieve/tests/bitcoin.rs, btsieve/tests/bitcoin_missing_blocks.rs, btsieve/tests/ethereum.rs, cnd/src/logging/initialize.rs, cnd/src/swap_protocols/rfc003/bitcoin/htlc_events.rs, cnd/src/swap_protocols/rfc003/ethereum/htlc_events.rs
Current matching logic in btsieve uses a mutable variable and logical and (`&&`) statements to mutate this variable.  This is unnecessary, also idiomatic Rust typically only uses mutable variables when needed.  We should change this code to not use mutable variables.
While we are cleaning up also do:
- Rename `TransactionQuery` to `Pattern`: since this struct holds data used to pattern match against transactions.
- Add documentation to the newly named `Pattern` struct and the pattern matching function.
- Rename the queries modules (bitcoin and ethereum) to `pattern_matching`.
=> Make btsieve matching code clearer

Cargo.lock, cnd/Cargo.toml, cnd/src/http_api/mod.rs, cnd/src/http_api/problem.rs, cnd/src/http_api/route_factory.rs, cnd/src/http_api/routes/index/handlers/get_swaps.rs, cnd/src/http_api/routes/index/mod.rs, cnd/src/http_api/routes/peers/mod.rs, cnd/src/http_api/routes/rfc003/handlers/action.rs, cnd/src/http_api/routes/rfc003/handlers/get_swap.rs, cnd/src/http_api/routes/rfc003/mod.rs, cnd/src/main.rs, cnd/src/network.rs, cnd/src/swap_protocols/dependencies/mod.rs, cnd/src/swap_protocols/rfc003/actions/mod.rs, cnd/src/swap_protocols/rfc003/actor_state.rs, cnd/src/swap_protocols/rfc003/alice/mod.rs, cnd/src/swap_protocols/rfc003/alice/spawner.rs, cnd/src/swap_protocols/rfc003/bob/actions/erc20.rs, cnd/src/swap_protocols/rfc003/bob/actions/generic_impl.rs, cnd/src/swap_protocols/rfc003/bob/insert_state.rs, cnd/src/swap_protocols/rfc003/bob/mod.rs, cnd/src/swap_protocols/rfc003/bob/spawner.rs, cnd/src/swap_protocols/rfc003/secret_source.rs, cnd/src/swap_protocols/rfc003/state_machine.rs, cnd/src/swap_protocols/rfc003/state_store.rs
This PR is a combination of work done by @thomaseizinger and @tcharding.  It removes the communication from the state machine and changes the way the bob spawning is done.  With this when a swap request arrives from the peer node we save the channel in a hashmap and store the swap request in the state store but do **not** spawn bob until later when the action handler gets triggered by the client withe accept/decline.  We also use async/await when spawning bob.
Resolves #1507.
Resolves #1406.
Resolves #1508.
=> Simplify the data-flow when accepting & declining swap requests

cnd/src/config/file.rs
Small clean up of path parameters.  Use `&Path` instead of `PathBuf` since we do not need to consume the argument.
=> Refactor path parameters

cnd/src/config/file.rs
Currently we have log statements that are being lost.  At this stage of the program execution the logger has not been initialized, use the println macro instead.
=> Use println! before logger is ready

Cargo.lock, api_tests/lib/cnd_runner.ts, api_tests/lib/config.ts, api_tests/package.json, api_tests/yarn.lock, cnd/Cargo.toml, cnd/src/cli.rs, cnd/src/config/file.rs, cnd/src/config/settings.rs, cnd/src/main.rs, cnd/src/seed.rs
Remove secret key from the config file and put it in a pem file in the same default data directory used for the config file.  Add a config file option to specify the location and a command line option also.
WIP because e2e tests are failing.  Can someone please review the config file option choices made in this patch and the patch to `api_tests/lib/config.ts`.  I'm uncertain if I've updated the e2e test lib incorrectly or if he PR has bugs.
Thanks
Fixes: #948
=> Remove secret key

cnd/src/libp2p_comit_ext.rs, cnd/src/main.rs, cnd/src/network.rs
Recent work saved the channel (future) for an incoming swap request instead of
spawning the future.  At that time we still had a future for the error path.  It
was not noticed that this error path future was only there because of the now
removed spawning.  We can remove this error path future also, this means the
task executor is no longer needed in the ComitNode.
=> Remove task executor from ComitNode

cnd/src/http_api/route_factory.rs, cnd/src/main.rs
We are no longer embedding comit-i, hence there is no need (for now), to specify these cors headers for the arbitrary origin of localhost:3000.
=> Remove preflight

cnd/src/db/schema.rs
This patch adds 6 table declarations to our database module. To keep the writing and reading code simple, we add a table per combination of AL/BL/AA/BA that is currently supported by cnd.
This work was separated to allow for parallel work on the reading and writing code because the macros generate the glue code for accessing the database.
=> Add table declaration statements for request & response messages

bors.toml
Currently, one has to wait for a successful build before the PR can be handled to bors. However, sometimes we now upfront a build will succeed (textfile only changes for example). Hence, we can immediately delegate to bors without waiting for the build.
=> Allow for an eager `bors r+`

api_tests/e2e/rfc003/btc_eth/happy.ts
The 30 second timeout has caused problems on CI. 
It looks like transactions on the Bitcoin regtest node sometimes take a long time to be included in a block.
Fixes #1613. Reopen if it keeps happening.
=> Increase e2e test timeout

cnd/src/db/save_message.rs
This is 2 refactor patches followed by a bug fix; we are currently mixing up the redeem/refund identities when saving accept messages to the database.
=> Refactor save message

cnd/src/db/integration_tests.rs, cnd/src/db/mod.rs, cnd/src/main.rs
It doesn't make much sense to have it because of the way our DB code is setup.
In-memory DBs of SQLite only live as-long as the connection is open. This means, we drop the DB just after we ran the migrations. In order to properly support in-memory DBs, we'd have to rework the way our DB code handles the connections as we would need to keep them around. In-memory DBs would only be useful for testing and we don't need them for now, hence it is not worth supporting them properly and certainly not improperly.
=> Remove possibility for in-memory DB

Cargo.lock, btsieve/Cargo.toml, btsieve/src/bitcoin/mod.rs, cnd/Cargo.toml, cnd/src/http_api/asset.rs, cnd/src/http_api/ledger.rs, cnd/src/network/send_request.rs, cnd/src/seed.rs, cnd/src/swap_protocols/metadata_store.rs, cnd/src/swap_protocols/rfc003/mod.rs, cnd/src/swap_protocols/rfc003/secret.rs, cnd/src/swap_protocols/rfc003/state_store.rs, libp2p-comit/Cargo.toml, libp2p-comit/src/frame/codec.rs, libp2p-comit/src/handler.rs
Move the whole code base to use `thiserror` any where it is appropriate.  While some of the call sites appear to add extra code we are actually getting a lot of extras for free.  All errors now implement `std::error::Error` and have useful debugging output.
This is related to #1194, once I've hacked about with `anyhow` I will do brief write up for the team on error handling.
=> Use `thiserror` to derive std::error::Error

README.md
cnd has various command line options.  Add a comment to the README that `cnd --help` is available for usage help.
=> Add note to README indication availability of cnd --help

cnd/src/db/integration_tests.rs, cnd/src/db/mod.rs, cnd/src/db/save.rs, cnd/src/db/swap.rs, cnd/src/http_api/dependencies.rs, cnd/src/http_api/route_factory.rs, cnd/src/http_api/routes/rfc003/handlers/action.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/http_api/routes/rfc003/mod.rs, cnd/src/main.rs, cnd/src/network/mod.rs
Now that we have all the database saving implemented it is clear that the `Save` trait (used for saving what was swap metadata) is a a specific case of the generic `SaveMessage<M>` if 'message' was the more general 'anything'.
Merge the two traits together and remove reference to 'messages'.
Fixes: #1678
=> Merge `Save` and `SaveMessage` traits

cnd/src/http_api/action.rs, cnd/src/http_api/problem.rs, cnd/src/http_api/routes/index/handlers/get_swaps.rs, cnd/src/http_api/routes/index/mod.rs, cnd/src/http_api/routes/rfc003/handlers/action.rs, cnd/src/http_api/routes/rfc003/handlers/get_swap.rs, cnd/src/http_api/routes/rfc003/handlers/mod.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/http_api/routes/rfc003/mod.rs, cnd/src/http_api/swap_resource.rs, cnd/src/lib.rs, cnd/src/spectral_ext.rs
By making better use of anyhow and thiserror, we can question-mark
away many of the errors. We still have control of the error returned to the user through the custom recover function of warp.
Fixes #1683.
=> Simplify error handling in http routes

api_tests/lib/config.ts, api_tests/lib_sdk/actors/actor.ts
With the recent change to move to a data directory, we no longer use this seed. It seems like we never needed it because the tests also pass without explicitely controlling the seed.
=> Remove seed from e2e tests

cnd/Cargo.toml
For some reason, this did not fail on a regular `cargo build --release`,
but did cause trait bound errors on running `cargo install`.
Resolves #1740
=> Fix missing serde feature dependency

.githooks/pre-commit, Makefile
Instead of running all the commands all the time, we conditionally define rules based on the dev's machine and the files that need to be committed.
=> Massively improve Makefile performance

api_tests/lib/setup_chai.ts, api_tests/lib_sdk/actors/actor.ts, api_tests/package.json, api_tests/tslint.json, api_tests/types/bn-chai/index.d.ts, api_tests/yarn.lock
This improves the assertions in two ways:
1. Before we check the wallet balances, we wait until cnd reports the swap as 'SWAPPED'.
2. We use `bn-chai` to compare the balances to improve the error message. In case of failure, we now get:
Fixes #1719. (Hopefully)
=> Better wallet assertions

Cargo.lock, cnd/Cargo.toml, cnd/src/http_api/routes/rfc003/mod.rs
We depend on hyper implicitely through warp. Removing the explicit dependency avoids problems with dependabot wanting to update it even though the dependency needs to be kept in sync with the transitive one.
=> Remove explicit hyper dependency

cnd/src/comit_api/mod.rs, cnd/src/db/swap_types.rs, cnd/src/http_api/mod.rs, cnd/src/network/mod.rs, cnd/src/swap_protocols/asset.rs, cnd/src/swap_protocols/ledger/mod.rs, cnd/src/swap_protocols/mod.rs
Currently we have `Unknown` variants in `AssetKind`, `LedgerKind`, and
`SwapProtocol`.  These are unnecessary if we handle the errors during
de/serialization.
Resolves: #1330
=> Remove Unknown variants

CHANGELOG.md, cnd/src/logging/initialize.rs, cnd/src/main.rs
Print all diagnostics and log messages to stderr instead of stdout.  With this applied the only output that goes to stdout is the output from `cnd --dump-config`.
Verify with: `target/debug/cnd 2> /tmp/cnd.stderr`.
Resolves: #1586
=> 1586 stderr

api_tests/e2e/rfc003/btc_eth/cnd_can_be_restarted.ts, api_tests/e2e/rfc003/btc_eth/happy.ts, api_tests/lib_sdk/actors/actor.ts
In the new e2e format the cnd nodes are not terminated leaving us with unwanted running processes. Even worse, since we do not stop btsieve queries, these cnd nodes keep firing requests to the blockchain nodes. 
Note: 
This does not work as the test framework does not honor the final block, i.e. if the test times out, finally is not executed.
```javascript
it("after the swap was accepted", async function() {
const { alice, bob } = await createActors(
"cnd_can_be_restarted.log"
);
try {
await do_the_limbo_dance();
} finally {
if (alice) {
alice.stop();
}
if (bob) {
bob.stop();
}
}
}
```
=> Terminate cnd in new e2e format

cnd/build.rs, cnd/src/cli.rs, cnd/src/main.rs
Add a custom version string to the cnd executable.  With this applied version option form is unchanged.  Output includes first 12 characters of the latest commit hash.
```
$ cnd --version
COMIT network daemon 0.5.0 (8e5181c4bab3)
```
Resolves: #1417
=> Add a custom version string

cnd/tests/ethereum_pattern.rs
Currently we are testing the matching logic for ethereum transactions using
handcrafted data.  We could have more faith in the tests if we used real data.
We have an ethereum block extracted from mainnet.  Use this block to do testing
on the matching logic for ethereum transactions.
Resolves: #1459
=> ethereum: Test pattern matches using mainnet block

api_tests/harness.ts, api_tests/lib/actor.ts, api_tests/lib/cnd_runner.ts, api_tests/lib/ledger_runner.ts, api_tests/lib/util.ts, api_tests/lib_sdk/cnd_instance.ts
In an ongoing effort to improve the dev experience when end to end testing:
- Quieten down the e2e tests, no more:
```
Stopping cnds: alice, bob, charlie
Starting cnd for alice, bob, charlie
cnd charlie exited with signal SIGINT
cnd bob exited with signal SIGINT
cnd alice exited with signal SIGINT
```
- Add a command line flag `yarn test --verbose` to maintain the current behavior
=> Make e2e test quieter

api_tests/dry/sanity.ts
I had no network connection enabled and this test failed as my known network addresses were only 2: 
```
[ '/ip4/127.0.0.1/tcp/9939',
'/ip6/::1/tcp/9939']
```
=> Fix problem if no network connection is present

cnd/src/http_api/routes/rfc003/swap_state.rs, cnd/src/swap_protocols/rfc003/alice/actions/erc20.rs, cnd/src/swap_protocols/rfc003/alice/actions/generic_impl.rs, cnd/src/swap_protocols/rfc003/alice/mod.rs, cnd/src/swap_protocols/rfc003/bob/actions/erc20.rs, cnd/src/swap_protocols/rfc003/bob/actions/generic_impl.rs, cnd/src/swap_protocols/rfc003/bob/mod.rs, cnd/src/swap_protocols/rfc003/mod.rs
Currently the Bob and Alice SwapCommunication enums are identical, we
can merge them into a single definition.
Resolves #1680.
=> Remove duplicate SwapCommunication

cnd/src/btsieve/bitcoin/mod.rs
Function is quite complex, refactoring it into separate functions is not really a viable option because of the complexity of the types involved.  There are however a few small things we can do to reduce the cognitive load required when reading this function.
- Add verbose comments since the logic is complex.
- Refactor so that we get the initial 'latest_block' at the top of the
function, this makes the following loop easier to read.
- Refactor the final section so we do not depend on `continue`, this
aids maintainability as well as assisting understanding the logic.
Due to some github noobity I am unable to re-open the [original PR](https://github.com/comit-network/comit-rs/pull/1763) that was this work.
The ethereum connector refactor of `matching_transacitions` can be found …
=> Bitcoin: Refactor `matching_transactions()`

cnd/src/btsieve/ethereum/transaction_pattern.rs, cnd/src/config/file.rs, cnd/src/config/mod.rs, cnd/src/config/settings.rs, cnd/src/db/mod.rs, cnd/src/http_api/mod.rs, cnd/src/http_api/problem.rs, cnd/src/http_api/routes/rfc003/decline.rs, cnd/src/http_api/routes/rfc003/handlers/action.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/http_api/swap_resource.rs, cnd/src/lib.rs, cnd/src/network/mod.rs, cnd/src/swap_protocols/asset.rs, cnd/src/swap_protocols/ledger/mod.rs, cnd/src/swap_protocols/mod.rs, cnd/src/swap_protocols/rfc003/messages.rs, cnd/src/swap_protocols/rfc003/secret.rs, cnd/src/swap_protocols/rfc003/state_store.rs
If types can be copy, they should according to the docs:
https://doc.rust-lang.org/std/marker/trait.Copy.html#when-should-my-type-be-copy.
Implementing Copy on as many types as possible allows us to remove `.clone()` in some circumstances.
=> Implement Copy on as many types as possible

cnd/src/http_api/route_factory.rs, cnd/src/http_api/routes/rfc003/handlers/action.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/http_api/routes/rfc003/mod.rs, cnd/src/load_swaps.rs, cnd/src/main.rs, cnd/src/network/mod.rs, cnd/src/seed.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/init_swap.rs, cnd/src/swap_protocols/rfc003/secret_source.rs, cnd/src/swap_protocols/rfc003/state_store.rs
Currently we have a `Seed` type that is used as the root seed to derive
per swap seeds which are then used to derive identities (refund/redeem).
Using the same type for all of these seeds means the compiler cannot
give us type safety.  Since these two things are separate we can use
separate types to allow the compiler to differentiate the types and
provide safety.
Add `RootSeed` for the seed read in from the PEM file and derive a new
`SwapSeed` to use for identity derivation.
Note: I'm not totally happy with this one, open to any suggested improvements, thanks.
Done in preparation for #1682
=> Add two types `RootSeed` and `SwapSeed`

cnd/src/http_api/route_factory.rs, cnd/src/http_api/routes/index/handlers/get_swaps.rs, cnd/src/http_api/routes/index/mod.rs, cnd/src/http_api/routes/peers/mod.rs, cnd/src/http_api/routes/rfc003/handlers/action.rs, cnd/src/http_api/routes/rfc003/handlers/get_swap.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/http_api/routes/rfc003/mod.rs
Currently we pass the dependencies throughout the http_api module using trait bounds.  This is super verbose.  Also since we now this is only ever going to be an actual instance of the `Facade` and we are not trying to limit the callers usage of the facade it adds no real benefit using trait bounds.
=> http_api: Use Facade as arg instead of trait bounds

Cargo.lock, cnd/Cargo.toml, cnd/src/btsieve.rs, cnd/src/btsieve/bitcoin/bitcoind_connector.rs, cnd/src/btsieve/bitcoin/blockchain_info_connector.rs, cnd/src/btsieve/bitcoin/mod.rs, cnd/src/btsieve/ethereum/mod.rs, cnd/src/btsieve/ethereum/web3_connector.rs, cnd/src/config/mod.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/load_swaps.rs, cnd/src/main.rs, cnd/src/network/mod.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/init_swap.rs, cnd/tests/bitcoin_helper/connector_mock.rs, cnd/tests/bitcoin_missing_blocks.rs, cnd/tests/bitcoin_old_blocks.rs, cnd/tests/bitcoin_transaction_pattern_e2e.rs, cnd/tests/ethereum_helper/connector_mock.rs, cnd/tests/ethereum_missing_blocks.rs, cnd/tests/ethereum_old_blocks.rs, cnd/tests/ethereum_transaction_pattern_e2e.rs
Tokio-compat is compatibility shim for tokio 0.1 and tokio 0.2. It allows us to poll futures of tokio 0.1 and 0.2 at the same time.
=> Migrate to tokio 0.2

cnd/src/http_api/routes/rfc003/accept.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/swap_protocols/rfc003/actions/bitcoin.rs, cnd/src/swap_protocols/rfc003/actions/ether.rs, cnd/src/swap_protocols/rfc003/actions/mod.rs, cnd/src/swap_protocols/rfc003/alice/actions/erc20.rs, cnd/src/swap_protocols/rfc003/alice/actions/generic_impl.rs, cnd/src/swap_protocols/rfc003/alice/mod.rs, cnd/src/swap_protocols/rfc003/bob/actions/erc20.rs, cnd/src/swap_protocols/rfc003/bob/actions/generic_impl.rs, cnd/src/swap_protocols/rfc003/bob/mod.rs, cnd/src/swap_protocols/rfc003/messages.rs, cnd/src/swap_protocols/rfc003/mod.rs, cnd/src/swap_protocols/rfc003/secret_source.rs
Currently Bob can derive the secret from seed found in the state store.  This is logically incorrect.  With this applied Bob's functionality when using the `secret_source` is reduced to only deriving identities.
Resolves: #1682
=> Encode the capability of deriving a Secret into the type system so that only Alice can do that

Cargo.lock, cnd/Cargo.toml, cnd/src/btsieve/ethereum/mod.rs, cnd/src/db/integration_tests.rs, cnd/src/db/mod.rs
Fixes #1808.
The tokio channels return a `Result` contrary to the ones from `async-std`. Sending and receiving on those channels errors if the other half is dropped, so we can always safely ignore this.
=> Remove async-std

Cargo.lock, cnd/Cargo.toml, cnd/src/http_api/routes/rfc003/handlers/action.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/init_swap.rs, cnd/src/lib.rs, cnd/src/load_swaps.rs, cnd/src/main.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/mod.rs
Tokio 0.2 no longer provides an `Executor` trait. Instead, we use the `tokio::task::spawn` method to spawn an async task in the background.
This is not as explicit as calling `.spawn()` on dependencies, but as long as we only do this from application code (read cnd) and not from potential library code, this should be fine.
=> Migrate init_accepted_swap to tokio 0.2

api_tests/harness.ts, api_tests/lib/cnd_runner.ts, api_tests/lib_sdk/cnd_instance.ts, cnd/src/http_api/route_factory.rs, cnd/src/http_api/routes/index/handlers/get_swaps.rs, cnd/src/http_api/routes/index/mod.rs, cnd/src/http_api/routes/peers/mod.rs, cnd/src/http_api/routes/rfc003/handlers/action.rs, cnd/src/http_api/routes/rfc003/handlers/get_swap.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/http_api/routes/rfc003/mod.rs, cnd/src/main.rs, cnd/src/network/mod.rs, cnd/src/network/transport.rs, cnd/src/swap_protocols/facade.rs, libp2p-comit/src/lib.rs
Currently `main.rs` contains a bunch of networking code.  The root cause of much of this is due to libp2p types.  If we wrap the libp2p swarm in a struct then we can do a lot of cleaning up.
With this applied there is no more libp2p code in `main.rs` :)
Resolves: #1776
=> Clean up Network code

.github/workflows/stale.yml
The action was triggered by pushing to master... at least something :)
As of recommendation in https://github.community/t5/GitHub-Actions/Action-not-run-and-no-logs-available-action-stale/m-p/42928#M5180 I move it now back to cron.
=> Attempt to move back to cron for stale bot

.github/workflows/stale.yml
We want this bot to run, however, cron jobs does not seem to work at the moment. 
I've reached out to github support already, but in the meantime, let's run it on every push to master.
=> Run stale bot on push to master

Cargo.lock, cnd/Cargo.toml, cnd/src/btsieve/ethereum/mod.rs, cnd/tests/ethereum_helper/connector_mock.rs, cnd/tests/ethereum_missing_blocks.rs
- Stop spawning tasks using `tokio`'s executor in `matching_transaction`.
- Simplify the code and make the yielding of blocks more specific to our needs.
There is no need to fetch new and old blocks concurrently. Given that fetching old blocks by hash is fast (since they're all available) that work can always be done on demand, halting the fetching of new blocks in the meantime.
---
Fixes #1780.
Added @tcharding to reviewers so that he can eventually tell me whether he thinks this is a step forward in terms of clarity.
=> Yield blocks for Ethereum matching_transaction using a generator

Makefile, cnd/src/swap_protocols/rfc003/create_swap.rs
Our makefile only formats files that are staged. Formatting them
unstages them and hence, they need to be restaged again before they
can be committed.
A recent version of rustfmt added the option `--files-with-diff`
which outputs the files that were affected by the formatting.
We can use that information to automatically restage those files
and hence save a manual step for the developer. A usual workflow
would now be:
- write code
- stage the files ready for a commit
- make format
- commit
=> Automatically stage rust files after they have been formatted

Cargo.lock, Cargo.toml, cnd/Cargo.toml, cnd/src/http_api/problem.rs, cnd/src/http_api/route_factory.rs, cnd/src/http_api/routes/index/mod.rs, cnd/src/http_api/routes/peers/mod.rs, cnd/src/http_api/routes/rfc003/mod.rs, cnd/src/main.rs
To do this, we need to temporarily depend on a patched version of `http_api_problem` as that one is not released yet.
=> Update warp to 0.2

Cargo.lock, cnd/Cargo.toml, cnd/src/btsieve/ethereum/web3_connector.rs, cnd/src/seed.rs, cnd/src/swap_protocols/rfc003/secret.rs
I've ran `cargo audit` locally and found an unmaintained dependency (rust-crypto) in our dependency tree. Replaced with with `sha2`.
Also, there were some unused dependencies in our dependency tree. I've removed those as-well.
=> Remove unnecessary and unmaintained dependencies

api_tests/lib/bitcoin.ts, api_tests/lib/ledger_runner.ts, api_tests/lib_sdk/actors/actor.ts, api_tests/lib_sdk/wallets/bitcoin.ts, api_tests/types/bitcoin-core/index.d.ts
Previously, we generated 101 blocks _for each test_ to ensure we can spend the coinbase transactiosn and hence can send money to the wallet address.
We've also been using the `generate` RPC call which will be phased out in the future. It is recommended to use `generateToAddress` instead.
We should strictly avoid generating blocks from two different sources because it seems that it creates race conditions inside bitcoin of which "generate" RPC call wins and is actually able to produce a single chain. We generate a new block every second, hence it is likely that trying to generate 101 from a 2nd source causes problems.
To solve this, we move the ensureFunding call to the beginning of the test harness and simply fail inside the wallet if for some reason the wallet is used from a context that …
=> Don't generate unnecessary blocks

cnd/src/btsieve/bitcoin/mod.rs, cnd/src/btsieve/ethereum/mod.rs, cnd/src/btsieve/mod.rs, cnd/src/swap_protocols/rfc003/create_swap.rs
This allows for a more ergonomic usage because it avoids conversion at the callsite.
=> Use NaiveDateTime for Predates trait

api_tests/lib_sdk/actors/actor.ts
We only use this functionality internally, hence we can inline the method at the usage site.
=> Remove public cndIsRunning method

api_tests/lib_sdk/cnd_instance.ts
Using the process seems more natural because the process is dead anyway after it has been killed and hence, the reference to the object is worthless.
=> Use the process field instead of the config file check if cnd is running

Makefile, cnd/src/lib.rs, cnd/src/main.rs, libp2p-comit/src/frame/codec.rs, libp2p-comit/src/lib.rs
This aids integration with IDEs that allow to run clippy directly. Doing so makes it easier to navigate through the warnings provided by clippy which otherwise would need to be gone through manually on the commandline.
I thought I've done this at some point already but maybe that was a different repo :D
=> Move clippy lints to lib.rs and main.rs files

cnd/src/load_swaps.rs
The function load_swaps_from_database is an application concern. It can know about the Facade.
=> Use Facade instead of trait bounds

cnd/src/http_api/mod.rs, cnd/src/http_api/routes/index/handlers/get_swaps.rs, cnd/src/http_api/routes/rfc003/handlers/get_swap.rs, cnd/src/http_api/swap_resource.rs, cnd/src/swap_protocols/rfc003/actor_state.rs, cnd/src/swap_protocols/rfc003/alice/mod.rs, cnd/src/swap_protocols/rfc003/bob/mod.rs
Currently there is no indication on the `/swap/<foo>` endpoint if there
has been an error for a given swap.  This is not useful for a user.
This problem exists for `/swaps` endpoint also but needs to be handled
differently.
Do:
- For the `/swap/<foo>` endpoint return a 500 error if the swap has erred.
- For the `/swaps` endpoint return an erred swap but do not add any
actions.
**untested**
Fixes: #1945
=> Handle swap failure

api_tests/lib/log_reader.ts
There are issues on Mac where it waits undefinitely for the right light for both nodes despite the line being present in the file.
See https://github.com/nodejs/node/issues/5039 for more info.
=> api_test: Fix bitcoind/parity log wait

cnd/src/btsieve/ethereum/transaction_pattern.rs
saw these warning in our CI and removed them: 
```
error: character literal may only contain one codepoint
--> <doctest>:2:14
|
2 | [ { address: '0xe46FB33e4DB653De84cB0E0E8b810A6c4cD39d59',
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
help: if you meant to write a `str` literal, use double quotes
|
2 | [ { address: "0xe46FB33e4DB653De84cB0E0E8b810A6c4cD39d59",
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: character literal may only contain one codepoint
--> <doctest>:3:7
|
3 | data: '0x123',
|       ^^^^^^^
|
help: if you meant to write a `str` literal, use double quotes
|
3 | data: "0x123",
|       ^^^^^^^
error: character literal may only contain one codepoint
--> <doctest>:6:3
|
6 | [ '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b …
```
=> Remove compiler warnings

cnd/src/http_api/routes/rfc003/accept.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/quickcheck.rs, cnd/src/swap_protocols/facade.rs
If we want to split a comit crate out of cnd, we cannot abstract over a trait that is not defined in our crate.
This patch removes all the usages of the ledger::Bitcoin that are used in code that would be outside of the comit crate for abstracting over any bitcoin network.
Split out of #1970.
=> Unroll some implementations generic over ledger::Bitcoin

api_tests/lib/parity_instance.ts
I had problems with multiple parity instances being alive on my Mac.
This solves the problem, should not affect Linux.
I tested this by running single tests, i.e. `yarn run test e2e/rfc003/btc_eth/happy.ts` in `api_tests` folder and with `SIGINT` and `SIGTERM` the instance is almost never killed properly on my machine.
=> Use SIGKILL instead of SIGINT to kill parity node

CHANGELOG.md, api_tests/e2e/rfc003/eth_btc/ignore_fail_eth_transactions.ts, api_tests/lib_sdk/actors/actor.ts, api_tests/lib_sdk/utils.ts, api_tests/lib_sdk/wallets/ethereum.ts, cnd/src/btsieve/ethereum/mod.rs, cnd/src/btsieve/ethereum/transaction_pattern.rs, cnd/src/swap_protocols/rfc003/actions/erc20.rs, cnd/src/swap_protocols/rfc003/actions/ether.rs, cnd/src/swap_protocols/rfc003/ethereum/mod.rs, cnd/tests/ethereum_pattern.rs
_Replaces #2000 because the force pushes were starting to get ugly_
I found this bug because with #1985, I had a _out of gas_ issue at the htlc deployment but both Alice and Bob did "see" the deployment and could not see the redeem/refund.
Of course, redeem/refund was totally failing as the contract was not deployed at all.
Yes, this is a critical bug 🐛☠️☹️
Note: I believe this only applies to deploy as I don't think we would get the transaction in the block for a `revert` due to failed redeem/refund.
Note: Bug is proven with the [new test failing](https://github.com/comit-network/comit-rs/pull/2000/commits/623d846f287f89ebe5f105446080d383eee88881) at commit 623d846f287f89ebe5f105446080d383eee88881: Alpha ledger is marked as funded: …
=> Do not match failed Ethereum transaction

api_tests/lib_sdk/actor_test.ts, api_tests/lib_sdk/create_actor.ts
Remove nested it block. This allows for `console.log()` to print
in stdout and `log/tests` files to be written.
Also avoid nested log folder by doing `String.replace()`, `/` -> `_`
in log filenames.
=> Fix logging in e2e tests

CHANGELOG.md, Cargo.lock, api_tests/lib_sdk/actor_test.ts, api_tests/lib_sdk/create_actor.ts, api_tests/package.json, api_tests/yarn.lock, cnd/Cargo.toml
- Ensure that failed Ethereum transactions are ignored during a swap.
- Upgrade `blockchain-contracts` crate to 0.3.1. Ether and Erc20 HTLCs now use `revert` to fail the Ethereum transaction if the redeem or refund are unsuccessful.
=> Release 0.6.0

api_tests/e2e/rfc003/eth_btc/bitcoin_high_fee.ts, api_tests/lib_sdk/actors/actor.ts
Note, that the old test asserted the status (`400`). In order to achieve this in the new test framework, we have to configure axios properly in the SDK, as recorded here: https://github.com/comit-network/comit-js-sdk/issues/122
I added a follow up ticket for this: https://github.com/comit-network/comit-rs/issues/2046
=> Convert Bitcoin high fee test to new e2e test

.mergify.yml
We need to keep the head of release branches around to merge them back into dev.
=> Don't delete the head of release branches

api_tests/lib/actors/actor.ts, api_tests/lib/wallets/lightning.ts, api_tests/sanity/basic_lnd_payment.ts
See commit messages.
https://github.com/comit-network/comit-rs/commit/b4881718bbc704061ba514d3098f04236ae4b7ca may be controversial because I am removing the comparison of the `tokens`. I couldn't really figure out, what these tokens are.
@D4nte What was the reason for asserting them? I left them out because they would bloat the interface of `createInvoice` if I would return them as-well.
My assumption was: if I give an ID to LND and it tells me it is confirmed, I don't need to check anything else?
=> LND sanity test follow-up proposal

.mergify.yml
It seems that linking the team doesn't work, hence we request a review instead in order to trigger notifications.
=> Request review from team instead of commenting

cnd/src/db/integration_tests/db_roundtrips.rs, cnd/src/db/load_swaps.rs, cnd/src/db/save.rs, cnd/src/http_api/routes/rfc003/accept.rs, cnd/src/http_api/routes/rfc003/handlers/action.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/http_api/routes/rfc003/swap_state.rs, cnd/src/init_swap.rs, cnd/src/network/mod.rs, cnd/src/quickcheck.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/rfc003/actor_state.rs, cnd/src/swap_protocols/rfc003/alice/mod.rs, cnd/src/swap_protocols/rfc003/bitcoin/htlc_events.rs, cnd/src/swap_protocols/rfc003/bob/mod.rs, cnd/src/swap_protocols/rfc003/create_swap.rs, cnd/src/swap_protocols/rfc003/ethereum/htlc_events.rs, cnd/src/swap_protocols/rfc003/events/mod.rs, cnd/src/swap_protocols/rfc003/ledger_state.rs, cnd/src/swap_protocols/rfc003/messages.rs, cnd/src/swap_protocols/rfc003/mod.rs
Time for a new PR.
`Request` needs to keep the `Ledger` trait bounds due to the fact that it contains the ledger.
Hopefully, with the REST API routes we introduce with lightning, this will go away.
This will then free a bunch of other structs.
Works Towards #2037
=> Relax trait bounds on structs

cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/rfc003/create_swap.rs, cnd/src/swap_protocols/rfc003/state_store.rs
Doing a separate PR as this commit may be seen as controversial.
The complexity can be decreased by introducing types.
I think this is the way forward as ultimately, we want to remove the `Ledger` trait bound as with han/herc20 we will have separate (or no) `Ledger` traits.
Resolves #2037.
=> Relax trait bound `SwapEvent`

api_tests/lib/config.ts, cnd/src/config/file.rs, cnd/src/config/mod.rs, cnd/src/config/settings.rs, cnd/src/main.rs
Resolves #1844
As discussed in the ticket, the goal is to 
* let cnd come up with some smart defaults: 
* right now I default to regtest, in the future we might want to change this to mainnet
* let the user configure everything
* you can find a full example in the e2e tests (ignoring blockchain explorers right now)
* I propose to manually call verify once the configs were loaded 
* for this I'll create a follow-up ticket once this is merged.
What do you think?
=> 1844 simpler config

cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/network/mod.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/ledger/bitcoin.rs, cnd/src/swap_protocols/mod.rs, cnd/src/swap_protocols/rfc003/ledger.rs, cnd/src/swap_protocols/rfc003/messages.rs
We are in the process of attempting to remove the `Ledger` trait bound from various structs.  As a step towards that we can remove the `Into<LedgerKind>` trait bound from within the `Ledger` trait.
Doing so requires manually implementing conversion from an `rfc003::Request` to an `OutboundRequest` using concrete types.
Fixes: #2065
=> Remove the `Into<LedgeKind>` trait bound from Ledger

cnd/src/asset/mod.rs
Recently we removed the requirement for this trait bound and forgot to
remove the trait bound itself from the `Asset` trait.
Remove it now its unused.
=> Remove unused trait bound `Into<AssetKind>` from `Asset`

cnd/src/http_api/action.rs, cnd/src/identity.rs, cnd/src/lib.rs, cnd/src/swap_protocols/rfc003/actions/ether.rs
Our domain is cross chain.  We should have domain specific terms for
things in various chains.  We currently have the `asset` module and the
`ledger` module that do just this.
Add and `identity` module that defines an identity/address on a chain.
With this applied we can write
```
let address = identity::Ethereum::new(...)
```
Instead of
```
let address = ethereum::Address::new(...)
```
which is actually just a re-export of:
```
let address = web3::types::Address::new(...)
```
Similarly we have `identity::Bitcoin` for the Bitcoin addresses.
=> Add `identity` module

.circleci/config.yml, .github/workflows/publish-new-release.yml, RELEASING.md
I've tested this to my best ability by creating dummy releases on push events to this branch. You can see the final successful execution here: https://github.com/comit-network/comit-rs/actions/runs/45203040
I did have to make a bunch of changes afterwards to use the actual variables etc.
Please focus your review on finding mistakes in that regards:
- referencing outputs that don't exist
- referencing env variables that don't exist
- etc
The overall workflow works like this:
- macos and ubuntu runners build artifacts in parallel. they create archives and upload them to github artifacts
- two ubuntu jobs trigger after this: releasing the docker image and creating the github release
- the docker job downloads only the ubuntu artifact, builds the image and publishes it on dockerhub
- the GH …
=> Introduce new GH workflow for releases

cnd/src/btsieve/bitcoin/mod.rs, cnd/src/btsieve/ethereum/web3_connector.rs, cnd/src/http_api/action.rs, cnd/src/http_api/mod.rs, cnd/src/lib.rs, cnd/src/quickcheck.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/rfc003/bitcoin/htlc_events.rs, cnd/src/swap_protocols/rfc003/create_swap.rs, cnd/src/swap_protocols/rfc003/ethereum/mod.rs
Recently we added `identity::Bitcoin` and `transaction::Bitcoin`. Add `htlc_location::Bitcoin`.
Use these modules across the codebase.
Done while working on removing Ledger trait.
=> Use modules for domain terms

cnd/src/lib.rs
I had problems with Clippy because of
```
UserDirs::new().map(|d| d.home_dir().to_path_buf().join(".lnd"))
```
The `UserDirs` import is for Linux only and that causes Clippy to complain on Mac. 
Changed all directory imports to be fully qualified in this file.
=> Fully qualified import for os specific imports

cnd/src/db/with_swap_types.rs, cnd/src/http_api/routes/rfc003/handlers/action.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/http_api/routes/rfc003/swap_state.rs, cnd/src/http_api/swap_resource.rs, cnd/src/init_swap.rs, cnd/src/load_swaps.rs, cnd/src/network/mod.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/rfc003/actions/erc20.rs, cnd/src/swap_protocols/rfc003/actions/ether.rs, cnd/src/swap_protocols/rfc003/actor_state.rs, cnd/src/swap_protocols/rfc003/alice/actions/erc20.rs, cnd/src/swap_protocols/rfc003/alice/actions/generic_impl.rs, cnd/src/swap_protocols/rfc003/alice/mod.rs, cnd/src/swap_protocols/rfc003/bitcoin/htlc_events.rs, cnd/src/swap_protocols/rfc003/bitcoin/mod.rs, cnd/src/swap_protocols/rfc003/bob/actions/erc20.rs, cnd/src/swap_protocols/rfc003/bob/actions/generic_impl.rs, cnd/src/swap_protocols/rfc003/bob/mod.rs, cnd/src/swap_protocols/rfc003/create_swap.rs, cnd/src/swap_protocols/rfc003/ethereum/htlc_events.rs, cnd/src/swap_protocols/rfc003/ethereum/mod.rs, cnd/src/swap_protocols/rfc003/events/mod.rs, cnd/src/swap_protocols/rfc003/ledger.rs, cnd/src/swap_protocols/rfc003/ledger_state.rs, cnd/src/swap_protocols/rfc003/state_store.rs
Remove the HtlcLocation associated type from Ledger trait.
In preparation for removing the `Ledger` trait remove the `HtlcLocation` trait bound from `Ledger` trait.  This PR is split into 3 patches.
- Patch 1 does the bulk of the work (also implements idea presented in [comment below](https://github.com/comit-network/comit-rs/pull/2128#pullrequestreview-367521434))
- Patch 2 adds a type alias that is WIP i.e., will be removed once we remove `Transaction` from `Ledger`.  Kept separate because its a bit ugly.
- Patch 3 Removes the actual associated type i.e., this patch is a very small diff that explains why we do everything in patch 1.
Please see commit messages on each patch for more details, thanks.
Works towards: https://github.com/comit-network/comit-rs/issues/2081
=> Remove HtlcLocation from Ledger trait

.circleci/config.yml
We don't want to restore an outdated yarn cache.
=> Remove default yarn-cache

cnd/src/http_api/mod.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs
Prior to this patch, we manually mapped the enum variant of HttpLedger to an instance of the Bitcoin ledger in post_swap.rs
This is error prone and can lead to bugs where we are given one ledger in the enum variant but instantiate another one for the actual swap.
With this patch we make the Bitcoin ledger a field of the enum variant.
This way, we can just pass on the instance in post_swap.rs.
The mapping is now defined in a single place where bugs are theoretically still possible but easier to spot.
=> Don't manually map the given HttpLedger to a Bitcoin ledger

api_tests/lib/actors/actor.ts
Found this while debugging a test failure.
We now log the amounts to help debugging.
=> Log over and underfunded amounts

.circleci/config.yml, api_tests/package.json
@thomaseizinger found an issue describing incompatibility of the node version we are using on circleCI and jest: https://github.com/facebook/jest/issues/9453.
The tests are running locally. So let's upgrade circleCI as well.
=> Upgrade node to version 12

Cargo.lock, cnd/Cargo.toml, cnd/src/btsieve/ethereum/mod.rs, cnd/src/btsieve/ethereum/web3_connector.rs, cnd/src/ethereum/hex_serde/mod.rs, cnd/src/ethereum/mod.rs, cnd/src/quickcheck.rs, cnd/tests/ethereum_go_back_into_the_past.rs, cnd/tests/ethereum_helper/connector_mock.rs, cnd/tests/ethereum_missed_previous_latest_block.rs, cnd/tests/ethereum_transaction_matching_smoke_test.rs
Moved the web3 dependency to dev-dependencies and created copies of
those types in the ethereum module
I tried to remove the ethbloom and primitive type dependencies as well but it will require a fair bit of work to replace H256, ethbloom, H160, U128, U256.
=> Replaced web3 types without own ones #1938

api_tests/lib/cnd/cnd_instance.ts
Found this while debugging #2132. 
It is not fully going to solve it but help resilience of the test suite in general.
=> Properly wait for cnds to start up and accept requests

.dependabot/config.yml
We resolved most of the issues we had with dependencies forcing us to make extra entries in Cargo.toml. That caused failing dependency updates from dependabot.
We can now re-enable those entries :tada:
=> Re-enable most of the disabled dependencies for dependabot

Cargo.lock, cnd/Cargo.toml, libp2p-comit/Cargo.toml
We don't use these features and they bring in unmaintained dependencies:
https://github.com/comit-network/comit-rs/issues/2189
=> Remove libp2p-websocket and secp256k1 dependencies

cnd/src/http_api/routes/index/handlers/get_swaps.rs, cnd/src/http_api/routes/rfc003/handlers/action.rs, cnd/src/http_api/routes/rfc003/handlers/get_swap.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/http_api/swap_resource.rs, cnd/src/init_swap.rs, cnd/src/main.rs, cnd/src/network/mod.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/mod.rs, cnd/src/swap_protocols/rfc003/create_swap.rs, cnd/src/swap_protocols/rfc003/mod.rs, cnd/src/swap_protocols/state_store.rs
Pre-work towards re-modelling COMIT's core to account for `HAN` and `HErc20`.
The goal is to make it easier to split the state store into different ledgers (and eventually different single ledger protocols such as HAN and HErc20) in the near future.
=> Make StateStore trait generic over the state and events

cnd/src/btsieve/bitcoin/bitcoind_connector.rs, cnd/src/btsieve/bitcoin/cache.rs, cnd/src/btsieve/bitcoin/mod.rs, cnd/src/btsieve/ethereum/cache.rs, cnd/src/btsieve/ethereum/mod.rs, cnd/src/btsieve/ethereum/web3_connector.rs, cnd/src/btsieve/mod.rs, cnd/src/main.rs, cnd/src/network/mod.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/rfc003/bitcoin/htlc_events.rs, cnd/src/swap_protocols/rfc003/create_swap.rs, cnd/src/swap_protocols/rfc003/ethereum/htlc_events.rs, cnd/tests/bitcoin_go_back_into_the_past.rs, cnd/tests/bitcoin_helper/connector_mock.rs, cnd/tests/bitcoin_missed_previous_latest_block.rs, cnd/tests/bitcoin_transaction_pattern_e2e.rs, cnd/tests/ethereum_go_back_into_the_past.rs, cnd/tests/ethereum_helper/connector_mock.rs, cnd/tests/ethereum_missed_previous_latest_block.rs, cnd/tests/ethereum_transaction_matching_smoke_test.rs
Initially, we thought it was a good idea to make the traits BlockByHash and LatestBlock take &mut self. It turns out that we don't need this functionality for anything other than the tests and it actually forces us to clone the connector in many places.
Removing the mutable reference to self allows us to stop cloning the connector and simply pass references into all the functions.
=> Don't clone blockchain connectors

CHANGELOG.md, cnd/src/btsieve/bitcoin/bitcoind_connector.rs, cnd/src/btsieve/bitcoin/mod.rs, cnd/src/btsieve/ethereum/mod.rs, cnd/src/btsieve/ethereum/web3_connector.rs, cnd/src/config/mod.rs, cnd/src/config/validation.rs, cnd/src/main.rs
This PR checks to see if the bitcoin node network id and ethereum node chain id matches the id's specified in the config file. The check is performed at at startup. A warning is logged if the request to retrieve the id fails. Cnd will abort if the check finds that the actual id does not match the specified id.
Closes #2088.
=> Config validation

cnd/src/btsieve/bitcoin/mod.rs, cnd/src/btsieve/ethereum/mod.rs, cnd/src/btsieve/mod.rs
Type parameters are too powerful for what we need here. A single type will never have more than one BlockHash type, hence we can move those generics to the associated type level.
=> Move type parameter in BlockHash and PreviousBlockHash to assoc. type

.circleci/config.yml, cnd/src/btsieve/bitcoin/mod.rs, cnd/src/btsieve/ethereum/web3_connector.rs, cnd/src/config/validation.rs, cnd/src/main.rs
Run make format with the newly updated toolchain
Recently we updated the toolchain to 1.41.1, and also the nightly toolchain to `nightly-2020-01-15`.  CI is configured to run a different version of `rustfmt` so this got past CI.  However, this upgrade introduce a bunch of new formatting to our codebase.
- Run `make format`
- Configure CI to use the same nightly toolchain as the makefile
=> Use new rustfmt toolchain

cnd/src/btsieve/bitcoin/bitcoind_connector.rs, cnd/src/btsieve/bitcoin/mod.rs, cnd/src/btsieve/ethereum/mod.rs, cnd/src/btsieve/ethereum/web3_connector.rs, cnd/src/config/validation.rs, cnd/src/main.rs
The Ethereum and Bitcoin node config validation functions were
replaced with a generic one. A trait was added to provide a
cleaner API to the caller and reduce the amount of imports
required to call the the validation function in main. Error
handling was condensed and cnd will crash if a unspecified error
occurs when trying to contact the blockchain node to validate
the config.
=> Make config validation function generic and condense error handling

api_tests/lib/actor_test.ts, api_tests/tests/dry/lightning_routes.ts, api_tests/tests/dry/multiple_peers.ts, api_tests/tests/dry/peers_using_ip.ts, api_tests/tests/dry/rfc003_schema.ts, api_tests/tests/dry/sanity.ts, api_tests/tests/e2e/bitcoin_ethereum.ts
We have several layers of function calls here that can be reduced.
Unfortunately, it does not reduce the indentation yet but I think
this is a step in the right direction. Anyway, we can remove a layer
of indirection that is unnecessary.
=> Remove some noise from the e2e test declarations

api_tests/lib/ledgers/bitcoind_instance.ts
bitcoind was shutting down on my machine as it was trying and failing to bind to the default ports:
```
2020-03-16T01:40:38Z Binding RPC on address :: port 18443 failed.
2020-03-16T01:40:38Z Binding RPC on address 0.0.0.0 port 18443 failed.
2020-03-16T01:40:38Z Unable to bind any endpoint for RPC server
2020-03-16T01:40:38Z Error: Unable to start HTTP server. See debug log for details.
2020-03-16T01:40:38Z Shutdown: In progress...
2020-03-16T01:40:38Z scheduler thread interrupt
2020-03-16T01:40:38Z Shutdown: done
```
```
2020-03-16T01:40:38Z Warning: Config setting for -bind only applied on regtest network when in [regtest] section.
2020-03-16T01:40:38Z Warning: Config setting for -rpcbind only applied on regtest network when in [regtest] section.
```
=> Ensure that bitcoind binds to the custom ports

api_tests/lib/ledgers/bitcoind_instance.ts
We have one global logger for the whole test environment, hence we need to be explicit, which binary exited.
=> Make log statement about bitcoind exiting unambigous

api_tests/src/dry_test_environment.ts, api_tests/src/e2e_test_environment.ts
With the multiFile appender approach, every category is a different file. We don't need to print the category again the log files.
=> Remove category from log message

digest-macro-derive/src/lib.rs, digest/src/lib.rs, digest/tests/swap_digest.rs
3 traits:
- `IntoDigestInput`: The consumer must implement this trait on their basic data types. It basically allow them to tell the lib how they want such type to be transformed in a byte array
- `Digest`: The consumer must use `MacroDigest` derive macro to implement this trait on their data structures, using the `digest_prefix` attribute to specify the prefix applied to fields before hashing in hex
- `FieldDigest`: This is an internal sealed type, the consumer should not touch it.
1. Hash each field,
a. If the field is a basic data type: concatenate prefix + result of `into_digest_input`, hash it,
b. If the field is a data structure: concatenate prefix + result of `digest` (of the struct),
2. Order hash results,
3. Concatenate ordered hash results,
4. Hash them.
Note, if the field of an …
=> Swap digest: enum & nested structs

api_tests/package.json, api_tests/src/actors/actor.ts, api_tests/tests/dry/rfc003_schema.ts, api_tests/tests/dry/sanity.ts, api_tests/yarn.lock
We now have types in the SDK for Siren for quite a while. We can use them in our e2e tests instead of generating the types from the schema.
=> Don't generate siren type definitions automatically

.mergify.yml
Dependabot doesn't allow to recreate PRs from users that don't have write-access. Mergify doesn't have this so this always fails anyway. In addition, I checked with dependabot and it actually has a feature to automatically rebase on conflicts, which I now enabled.
=> Remove non-functional mergify rule

cnd/src/network/mod.rs
In order to be able to utilise the new communication protocol we need an interface between the controller and the swarm.
Add an API function that allows the controller (acting as Alice) to call the swarm (libp2p layer) and trigger execution of the new communication protocols (by calling through to the underlying swarm) in order to announce the created swap, send the known parameters, and receive the remaining required swap parameters back from Bob.
Fixes: #2170
=> Add skeleton API function for controller/swarm interface

cnd/src/network/protocols/announce/behaviour.rs, cnd/src/network/protocols/announce/handler.rs, cnd/src/network/protocols/announce/mod.rs, cnd/src/network/protocols/announce/protocol.rs, cnd/src/network/protocols/mod.rs
We think we have the overall structure and event propagation sorted. I think we should add tests at the network behaviour level like the chat example in libp2p to confirm everything is working how we expect.
=> Announce protocol using libp2p

cnd/src/btsieve/ethereum/web3_connector.rs, cnd/src/jsonrpc.rs
Add custom deserialisation to handle string returned from
Ethereum's "json-rpc" API. Log details of Ethereum connection
errors.
Closes #2256
=> Fix ethereum config validation

Dockerfile
Simply fix and resolves #2238 
Once merged I'll trigger a release to test it.
=> Install libssl-dev inside the container

CHANGELOG.md, cnd/src/config.rs, cnd/src/config/file.rs, cnd/src/config/settings.rs
The `Settings` struct need to always have a the lightning settings set even if not present in the file to allow the initialisation of a lnd connector in `main.rs`.
Also, we use `reqwest` to target the lnd REST API so best to have a URL in the file to avoid conversion later down the stream.
=> Ensure default is applied if lnd settings are not present

.github/workflows/ci.yml, Makefile, api_tests/package.json
Resolves #1407 
This PR introduces GitHub Action CI: 
Within this PR we execute the following targets: 
* `make build` on MacOS
* `make build` on Ubuntu
* `make test` on Ubuntu
* `make e2e` on Ubuntu
Note: 
I've added a new make target `ci_gha` (CI GitHubActions) so that we can keep circleCI running in parallel for some time. Once we decide to completely get rid of CircleCI we can remove/rename this field. I'll create a follow-up ticket on this
Not in this PR:
* `make test` on MacOS as GitHub Action MacOS does not provide Docker. Aperantly this will be provided in the future though. If so, we can run tests on MacOS as well (see here: https://github.com/actions/virtual-environments/issues/17#event-3067114887)
* `make build/test` on Windows as we do not have an implementation for …
=> Add GitHub Action CI Workflow

Cargo.lock, cnd/Cargo.toml, cnd/src/file_lock.rs, cnd/src/lib.rs, cnd/src/main.rs
Place a lock on the datadir specified in config. cnd aborts with
an error message if the specified datadir is already being used
by another cnd process.
Closes #2278
=> Lock datadir

Cargo.lock, digest-macro-derive/src/lib.rs, digest/Cargo.toml, digest/src/lib.rs, digest/tests/swap_digest.rs
Also several improvements:
- use unique `digest` attribute for fields and struct
- test compatibility with other struct & field attributes
=> Allow user to choose hash function in Digest macro

cnd/src/config.rs, cnd/src/config/file.rs, cnd/src/config/settings.rs
Improve the cnd configuration of LND by doing:
- Add the TLS certificate path and macaroon path to LND configuration.
- Don't use shared data structure for LND between `file.rs` and
`settings.rs`.
- Update unit tests.
Done as part of the LN squad.
=> Improve config for LND

cnd/src/bitcoin.rs, cnd/src/btsieve/bitcoin.rs, cnd/src/swap_protocols/rfc003/bitcoin/htlc_events.rs
Decide whether refund or redeem transaction using identity
rather than checking for a 1 or 0 on the witness stack.
Closes #2270
=> Check for redeem/refund spent outpoint using identity

cnd/src/btsieve/ethereum.rs, cnd/src/btsieve/ethereum/web3_connector.rs, cnd/src/comit_api.rs, cnd/src/ethereum.rs, cnd/src/http_api.rs, cnd/src/http_api/routes/rfc003/handlers/action.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/network.rs, cnd/src/network/protocols/ethereum_identity.rs, cnd/src/quickcheck.rs, cnd/src/swap_protocols/rfc003/ethereum.rs, cnd/src/swap_protocols/rfc003/ethereum/htlc_events.rs, cnd/tests/ethereum_helper/connector_mock.rs, libp2p-comit/src/frame/header.rs, libp2p-comit/src/frame/request.rs, libp2p-comit/src/substream/inbound.rs, libp2p-comit/src/substream/outbound.rs
`H256` (Hash) and `H160` (Address) are converted to our own types.
Note that for deserialization we always have to pass the Hash/Address by reference, otherwise we don't reach the right code-path in serde hex. @thomaseizinger already [tackled that problem](https://github.com/fspmarshall/serde-hex/pull/8). 
Unfortunately, the `U256` [value in Ethereum is not fixed hex](https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding) (although it actually is of fixed size, namely `[u8, 32]`). 
This leads to the problem, that we would have to implement our own `Serializer` and `Deserializer` because serde-hex does not implement `Compact` for `[u8, 32]`.
Implementing a custom `Serializer` and `Deserializer` is, however, not trivial, because our hex library does not support compacted hex …
=> Remove dependency on `primitive_types` for Ethereum types such as Address and TransactionHash

Cargo.lock, cnd/Cargo.toml, cnd/src/btsieve/ethereum.rs, cnd/src/ethereum.rs, cnd/src/swap_protocols/rfc003/ethereum/htlc_events.rs
Improve the diagnostics during Ethereum matching in btsieve.
Add a levenshtein distance calculation when matching and warn if we try to match against a transaction that is 'close'. 
Add appropriate tracing spans to improve debugging output.
Done as part of the LN squad.
=> Improve Ethereum diagnostics

.github/workflows/ci.yml
Added the e2e test for both OS similar to the build using matrix.
=> add matrix-os strategy to e2e job to run on mac-os

api_tests/src/wallets/ethereum.ts
an attempt to make more sense of our e2e tests logs. 
Sometimes a transaction get's _stuck_ but we don't know which one.
=> Add debug logs to e2e tests

bors.toml
This is to prevent absence-minded developers to trigger bors even
though they set a no-mergify label in purpose to do some clean up before
merging a pull request.
=> Stop bors to proceed if the `no-mergify` label is present

cnd/src/swap_protocols/halight/connector.rs
fixes #2464
needed to make `ether-halight` e2e test pass on macOS Catalina.
Questionable if this is a good fix, since it is a security concern.
=> add danger clause for ignoring invalid certificates

cnd/src/main.rs, cnd/src/network.rs, cnd/src/network/comit_ln.rs
This is in preparation for the libp2p tests, but it can be merged separately.
Pulls the "execution" (spawn watchers) code out of `ComitLn` into `ComitNode` and send an event after `finalize` from `ComitLn` to `ComitNode`. 
@D4nte @thomaseizinger decided to bring this in separate to avoid more brain-intense rebase on changes in `ComitLn` and `ComitNode`.
Note with `.danger_accept_invalid_certs(true)` on the reqwest client active the e2e tests pass locally for me. 
Note that the tests (to be added later) are planned like this in `ComitLn`:
```
#[cfg(test)]
mod tests {
#[test]
fn swap_communication_yields_correct_execution_parameters_for_alice() {
// -- Basic outline of the test for Alice --
// GIVEN a swap as Alice
// use CreateSwapParams to create a swap
// WHEN passed to the network …
```
=> pull execution code from `ComitLn` up to `ComitNode` 

.github/workflows/ci.yml, Makefile
Resolves #2353 
Two optimizations: 
1) caching node_modules
2) not installing rust-toolchain during e2e tests
For 2) I opted for going directly into `api_tests` to execute the e2e tests. 
The goal was to not install caro/toolchain for our e2e tests. 
The "problem" with our makefile is that we are using global variables.
Global variables in `make` are evaluated during makefile's "parsing" stage, not during execution stage. 
Give it a try and add this at the top of the makefile: 
```
$(warning A top-level warning)
$(warning Our toolchain is $(TOOLCHAIN))
```
The problem is that this is always executed. And hence, the toolchain is always installed for any make target.
We can go for optimizing the makefile but this is a whole other story. 
Next speedup will be done in: …
=> Cache api_tests/node_modules for GitHub Action CI

.github/workflows/ci.yml
Note: lnd are ignored for now. Not sure if there are useful logs in there. @D4nte : any thoughts? 
I opted against uploading the whole `api/log` folder due to its size: `api/log` contains `api/log/parity` and `api/log/bitcoind` which can get rather big. These folders contain the whole blockchain data. 
Uploaded files are auto-deleted after [90 days](https://github.community/t5/GitHub-Actions/Managing-Actions-storage-space/m-p/41424/highlight/true#M4618). 
I'm using a preview feature of the upload archive action. Afaik, eventually they will offer multi-file upload and we can merge the multiple steps into one. 
This plugin is not yet _stable_ hence I recommend to only use it for the logs for now and not for other actions such as binary or releases. If these uploads fail it's way more …
=> Upload e2e test logs

api_tests/src/bitcoin_miner.ts, api_tests/src/environment/kill_nodes.ts, api_tests/src/environment/setup.ts, api_tests/src/ledgers/bitcoin_miner_instance.ts, api_tests/src/ledgers/bitcoind_instance.ts, api_tests/src/ledgers/lnd_instance.ts, api_tests/src/ledgers/parity_instance.ts, api_tests/src/test_environment.ts, api_tests/src/utils.ts
We wrapped a number of node fs functions in promisify. There actually are promise version of such functions available so let's use them.
Also, exists API is deprecated so we'll replace it.
=> Use native node js API for fs

api_tests/package.json, api_tests/src/ledgers/lnd_instance.ts, api_tests/yarn.lock
When investigating the spawn ETXTBSY error I noticed
that both alice and bob try to download the lnd binary.
The spawn error happens for lnd and in the logs we see
alice's download finishing but it never does for bob.
Best case, it fixes the spawn issue, worst case, it
saves time and bandwidth.
=> Avoid double download of lnd binary

CHANGELOG.md, api_tests/tests/lightning_routes.ts, cnd/src/http_api/problem.rs, cnd/src/http_api/routes/index.rs, cnd/src/main.rs, cnd/src/network.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/halight/connector.rs
In the main, only the path to lnd certificate and macaroon
were passed. The files were read only during the finalize
step of the communication, leading to a panic if not
present or unreadable.
The logic has been modified to provide the following
functionality:
- An attempt is made to read the files when starting cnd,
the result is an `Option` passed down to the swarm.
- When a halight swap is created on the REST API,
the `Option` is checked and an error is returned to the
caller if it's `None`
- During the finalize phase, we assume that the check was
previously done so we should not be able to finalize a
halight swap if the `Option` is `None`. However, if there
is a bug, we log an error a do not finalize (nor panic).
Resolves #2489
=> Do not panic during halight communication if no lnd

api_tests/src/actors/actor.ts, api_tests/tests/ether_halight.ts, cnd/src/network/comit_ln.rs
resolves #2389
Note that I packed the rejection upon Bob providing an `address_hint` into a separate PR https://github.com/comit-network/comit-rs/pull/2507
I don't think we need this at the moment.
=> Add peer-id check for Bob

Cargo.lock, cnd/Cargo.toml, cnd/src/ethereum.rs, cnd/src/lightning.rs, cnd/src/network.rs, cnd/src/network/comit_ln.rs, cnd/src/network/test_swarm.rs
Add test to check announced ethereum lightning swap is finalized
Added a happy path integration test that checks if Alice and
Bob have agreed upon an Ethereum-Lightning swap to execute.
This test is used to check that the libp2p network behaviour
abstraction generates a SwapFinalized event as expected.
Closes #2303
I can't assert_eq on most of the fields because partial_eq is not implemented for the types
=> ComitLN Integration Test

cnd/src/http_api/problem.rs
Fix amusing comment typo
```
-// tracing trippers clippy warning, issue reported: https://github.com/tokio-rs/tracing/issues/553
+// tracing triggers clippy warning, issue reported: https://github.com/tokio-rs/tracing/issues/553
```
=> Fix comment typo - no trippers around here please

.github/workflows/ci.yml
Currently, we are only running the CI on branch pushes which prevents external contributors from triggering the CI for a PR they raised.
=> Run CI on pull-requests on selected push actions

api_tests/src/wallets/ethereum.ts, api_tests/tests/ether_halight.ts
Our Geth test node mines a block every second.  When sending a
transaction we set the nonce to be the value that we first read from the
blockchain, if we try to do this twice within a block it fails (Geth
thinks we are trying to do a transaction replacement).
Solution; after sending a transaction we wait until it has 1 confirmation. Only then we continue and release the lock.
Fixes: Your pain.
=> Wait for a transaction being included before releasing the lock

.mergify.yml
Changelog bot was added to help us remember to update the changelog, after time it seems it is not achieving the desired purpose and at times it goes hyper and nags many times on a single PR.
Remove the changelog bot.
Fixes: #2333
=> Remove the changelog bot

api_tests/tests/ether_halight.ts, cnd/src/http_api/problem.rs, cnd/src/network.rs, cnd/src/network/comit_ln.rs, cnd/src/swap_protocols/facade.rs
If a swap has already been initiated we do not want to initiate a second time otherwise there will be ambiguity in the system later during the communication protocols since the swap digest is based off of the created swap parameters.
There is more than one solution to this problem but for now just iterate over the current swaps and if one exists with these parameters already abort initiation.
Now with testing, patch 2 adds a failing e2e test, based on @thomaseizinger observation that patch 1 returns a 500 error.  Patch 3 fixes the tests.  PR is 'untested' because I cannot run e2e tests on my machine currently ...
Fixes: #2490
=>  Do not initiate a swap for identical parameters

CONTRIBUTING.md
As per my rule to update the documentation when noticing that it is outdated this quick PR, note that I added contribution guidelines to comit-js-sdk referencing the guidelines in comit-rs: https://github.com/comit-network/comit-js-sdk/pull/232
=> Update branching model in contribution guidelines

cnd/src/db.rs, cnd/src/db/save.rs, cnd/src/http_api/routes/index.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/halight.rs, cnd/src/swap_protocols/han.rs, cnd/src/swap_protocols/herc20.rs
Users can create an ether/lightning swap via the REST API.  We would
like a way to save the data that the user provides into the database.
As a first step in doing so define an interface between the controller
and the database.
(The logic in this PR was originally done in: #2513)
Fixes: #2158
=> Define the interface to save created swaps to the db

api_tests/src/actors/actor.ts, cnd/src/http_api/route_factory.rs, cnd/src/http_api/routes.rs, cnd/src/http_api/routes/rfc003.rs, cnd/src/http_api/swap_resource.rs
Currently we do not return any data when a user hits the newly created `/swaps/:id` endpoints.
The schema was designed in https://github.com/comit-network/comit-js-sdk/pull/185
Return the correct data as defined in the js-sdk for the ethereum-ether/lightning endpoint.
Please note: Does not include tests as described in the issue.
Resolves: #2387
=> Implement GET /swaps/:id (lightning)

CHANGELOG.md
`Fixed` is a 2nd level header but in changelogs, it should be 3rd level.
I had trouble test-releasing when working on https://github.com/comit-network/comit-rs/issues/2242
@thomaseizinger pointed me to the problem.
=> Fix changelog format to avoid release failure

api_tests/tests/lightning_routes.ts
I realized while taking a look at our current e2e tests that we are not always asserting error responses in the same way and also not all aspects of it.
I've played around with Jest a bit and I believe I've found a concise way of covering the whole error response.
Putting this PR up for people to take inspiration from.
Please use this format from now on when you assert error responses from cnd and migrate other tests to test format if you come across some as part of other work.
Thanks :)
Asking everyone for review so everyone knows!
=> Actually assert the full error response

.github/workflows/draft-new-release.yml
Fixes #2327.
- Remove trigger on labelling so that the flow is not triggered twice.
- Add reopened trigger in case mistakes are made when first opening
the draft-new-release issue.
---
Aligns it with what we already do in `comit-network/comit-js-sdk`, which @D4nte fixed a while back.
=> Trigger draft-new-release GitHub Action on issue open and re-open

api_tests/package.json, api_tests/src/actors/actor.ts, api_tests/tests/lnd_sanity.ts, api_tests/yarn.lock
Uses the change done in https://github.com/comit-network/comit-js-sdk/pull/229
The `sendPayment` API now resolves when the payment
is `in flight`, allowing us to await it.
We can then later await the returned function to wait
for the payment to be settled.
Related to comit-network/comit-sdk#180
=> Upgrade comit-sdk to 0.16.0

api_tests/src/actors/actor.ts, api_tests/tests/communication.ts, api_tests/tests/ether_halight.ts, cnd/src/http_api/routes.rs, cnd/src/network.rs, cnd/src/network/comit_ln.rs, cnd/src/swap_protocols/facade.rs
Bob now stores swaps announced by Alice even if they are not yet created.
When Bob creates a swap (via REST API), then it checks such swaps and proceed with confirmation and communication if present.
Please note I amended the current test to check this behaviour to avoid adding one more full swap e2e test.
Helps with #2488.
=> Bob does not reject announcement if the swap is not yet created

api_tests/src/actors/actor.ts, api_tests/src/swap_response.ts, api_tests/tests/communication.ts, api_tests/tests/ether_halight.ts, cnd/src/network.rs, cnd/src/network/comit_ln.rs, cnd/src/network/comit_ln/swaps.rs, cnd/src/timestamp.rs
Having several different hashmap for each swap information
and status creates complexity in `ComitLn` and also creates
the risk of having bugs that lead to discrepancy between
the different hashmaps.
By moving all hashmap to a given struct that has a consistent
interface, it allows the focus on avoiding discrepancy
to be localized to this new `Swaps` struct.
It also later allows the migration of this `Swaps` struct
to a state machine if we see it as a gain.
Old pending swaps are also cleaned up. For now I put a hardcoded 5 minutes time out. We can decide to make it configurable at a later stage.
Resolves #2488
=> Move all swap hashmaps to a dedicated struct

Cargo.lock, cnd/Cargo.toml, cnd/src/btsieve/bitcoin.rs, cnd/src/btsieve/bitcoin/bitcoind_connector.rs, cnd/src/jsonrpc.rs, cnd/src/main.rs, cnd/src/swap_protocols/halight/connector.rs, cnd/src/trace.rs
Fixes #2368.
Instead of using `tracing` like the original ticket suggests, we use `anyhow::Context`. It should be easier for a developer to get all the error information from the error stack, rather than having to cross-reference with cnd's logs.
Feel free to be nitpicky in terms of error messages, unnecessary errors, missing errors, etc.
=> Add context to ledger connector errors 

cnd/src/network/comit_ln.rs, cnd/src/network/comit_ln/swaps.rs, cnd/src/network/protocols/announce.rs, cnd/src/swap_protocols/facade.rs, digest-macro-derive/src/lib.rs, digest/src/lib.rs, digest/tests/swap_digest.rs
Saves having a clone every time `digest` is called.
=> Do not consume `self` on `digest`

cnd/migrations/2020-05-06-105000_tables/down.sql, cnd/migrations/2020-05-06-105000_tables/up.sql, cnd/src/db.rs, cnd/src/db/created_swap.rs, cnd/src/db/in_progress_swap.rs, cnd/src/db/integration_tests.rs, cnd/src/db/integration_tests/api.rs, cnd/src/db/load_swaps.rs, cnd/src/db/rfc003_schema.rs, cnd/src/db/save.rs, cnd/src/db/schema.rs, cnd/src/db/swap.rs, cnd/src/db/swap_types.rs, cnd/src/db/tables.rs, cnd/src/db/wrapper_types.rs, cnd/src/ethereum.rs, cnd/src/http_api.rs, cnd/src/http_api/routes/index.rs, cnd/src/lightning.rs, cnd/src/swap_protocols.rs, cnd/src/swap_protocols/halight.rs, cnd/src/swap_protocols/han.rs, cnd/src/swap_protocols/herc20.rs
Another attempt at implementing the new database model.
This time; limited to only touching the database module (where possible) i.e., this PR defines and implements an API for as well as implementing the database code for `herc20 -> halight` swaps.
In this PR we have:
- Individual tables incl. save/load and unit tests
- A type `CreatedSwap` for saving a swap when it comes in on the REST API. Load and Save APi methods for this type incl. roundtrip unit test.
- Database methods to save all the individual message data types shared during the communication protocols.
- A type `InProgressSwap` to load an in progress swap.
- An integration test that simulates the flow of a swap from creation, through finalization, and into the 'in progress' state.
=> Add new database model

api_tests/src/actors/actor.ts, api_tests/tests/communication.ts, api_tests/tests/erc20_halight.ts, api_tests/tests/lightning_routes.ts, cnd/src/asset/ethereum/erc20.rs, cnd/src/http_api/route_factory.rs, cnd/src/http_api/routes.rs, cnd/src/http_api/routes/index.rs, cnd/src/network.rs, cnd/src/network/comit_ln.rs, cnd/src/network/comit_ln/swaps.rs, cnd/src/swap_protocols.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/herc20_quickfix.rs, cnd/src/swap_protocols/herc20_rfc003_watcher.rs
In an attempt to get cnd into a state where we can bring the current db and the lightning swaps together this PR changes `HanEthereumEther-HalightLightningBitcoin` swaps to `Herc20EthereumErc20-HalightLightningBitcoin` swaps.
Note that I did not act upon the new `herc20` protocol code yet, but used the rfc003 watcher for monitoring Ethereum. 
Would get this merged asap and then finally connect use the new DB 😀
=> Switch ether to erc20 for halight swaps

cnd/src/network/comit_ln.rs, cnd/src/network/comit_ln/swaps.rs
Peer id check is done within `Swaps` already.
=> Remove redundant peer id check

api_tests/tests/communication.ts
The e2e test names are used as file names in the log output directory. Linux users twitch when there is whitespace in file names.
=> Remove spaces from test names

cnd/migrations/2020-05-06-105000_tables/down.sql, cnd/migrations/2020-05-06-105000_tables/up.sql, cnd/src/bitcoin.rs, cnd/src/db/schema.rs, cnd/src/db/tables.rs, cnd/src/http_api/route_factory.rs, cnd/src/http_api/routes.rs, cnd/src/http_api/routes/index.rs, cnd/src/http_api/routes/post.rs, cnd/src/main.rs, cnd/src/network.rs, cnd/src/network/comit_ln.rs, cnd/src/network/comit_ln/swaps.rs, cnd/src/swap_protocols.rs, cnd/src/swap_protocols/facade.rs, cnd/src/swap_protocols/hbit.rs, cnd/src/swap_protocols/hbit/events.rs, cnd/src/swap_protocols/hbit/extract_secret.rs, cnd/src/swap_protocols/hbit/htlc_events.rs, cnd/src/swap_protocols/hbit/ledger_state.rs, cnd/src/swap_protocols/hbit/ledger_states.rs, cnd/src/swap_protocols/secret.rs, cnd/src/swap_protocols/swap_id.rs
We have been trying to implement the newly designed split protocols for ages now; this PR is a change of approach. Instead of pushing forward with the LN stuff hoping that a nice split protocols implementation will fall out this PR adds the herc20/hbit protocol pair.
Add an `hbit` module under `swap_protocols/` with the following things in mind:
- Do not use rfc003 types, duplicate rfc003 code into `hbit` if needed.
- Try not to break any current working code.
This PR adds two new end points for both swaps of the trading pair hbit/herc20. Save of the created swap is fully implemented.  No retrieval for this data from the data base, also the REST actions are not done (these are heavy users of data retrieval so will be interesting to implement on top of the new database design, this can be …
=> Add hbit module

Cargo.lock, cnd/src/ethereum.rs, cnd/src/swap_protocols/facade.rs
Swaps that involve the Herc20 protocol should include the token contract address in the digest since there may be multiple swaps including different tokens.
- Patch 1 updates `proc-macro2`
- Patch 2 removes 'pub' from H64 
- Patch 3 adds the `token_contract` field to digest
Fixes: #2626
=> Add token_contract to the digest for herc20 swaps

comit/src/btsieve.rs, comit/src/btsieve/hbit_connector_impls.rs, comit/src/hbit.rs, comit/src/lib.rs
In Rust code is not built unless the module is declared in its parent module.
Add `hbit` to the root module so it is actually built. Fix the half baked effort I made when adding this module.
=> Actually build hbit

cnd/src/lib.rs, cnd/src/network.rs, cnd/src/swap_protocols/halight.rs, cnd/src/swap_protocols/herc20.rs, cnd/src/tracing_ext.rs
This allows us to conveniently create new instances of protocols without duplicating that code all over the place.
=> Introduce `new` functions in protocol modules

cnd/src/db/integration_tests/db_roundtrips.rs, cnd/src/db/save_load_impls/rfc003.rs, cnd/src/db/swap.rs, cnd/src/http_api/routes/rfc003/handlers/post_swap.rs, cnd/src/http_api/swap_resource.rs, cnd/src/network.rs, cnd/src/quickcheck.rs, cnd/src/swap_protocols/rfc003_facade.rs
The identifier `Swap` is in high demand, lets not waste it on rfc003 code.
Rename the rfc003 `Swap` to `Rfc003Swap`.
=> Rename Swap -> Rfc003Swap

cnd/src/main.rs, cnd/src/respawn.rs
We do not need access to the `Facade` when respawning, `Storage` is a
top level type, no need to call through to it via the facade.
Pass `Storage` directly to the `respawn()` function instead of
delegating to the `Facade`.
=> Pass Storage to respawn

cnd/src/db.rs, cnd/src/db/save_load_impls.rs, cnd/src/http_api/routes/index.rs, cnd/src/http_api/routes/post.rs, cnd/src/main.rs, cnd/src/network.rs, cnd/src/network/comit.rs, cnd/src/network/comit/swaps.rs, cnd/src/network/start_swap.rs, cnd/src/protocol_spawner.rs, cnd/src/storage.rs, cnd/src/swap_protocols/facade.rs, comit/src/network.rs, comit/src/network/swap_digest.rs
Builds on top of @D4nte's draft PR re-working the network module to make it easier to add more protocols.
The idea is to make the `Comit` (previously named `ComitLN`) `NetworkBehaviour` agnostic to the swap protocol that it is involved in i.e., within `Comit` there is no alpha/beta only data to be communicated with the peer node. One layer up, at the swarm (`ComitNode` `NetworkBehaviour`) the protocol and role are known.
All reads and writes to the database, which imply knowledge of the protocol, happen in the swarm. For this we add a reference to the new `Storage`.
Please note: This PR touches the network module, and call sites to the network module entry point `initiate_communication`, this includes the `Facade` and `index.rs`. Also, since this PR removes the now stale 'new' way to …
=> Improve the network module

cnd/src/network/comit.rs, cnd/src/network/comit/swaps.rs
The `expect` was called on received events, meaning a malicious party could send a message with an unknown shared swap id and panic our node.
Also little clean up where a tuple was returned but only one value used.
=> Do not panic on unexpected messages

cnd/src/http_api/halight.rs, cnd/src/http_api/halight_herc20/alice.rs, cnd/src/http_api/halight_herc20/bob.rs, cnd/src/http_api/herc20.rs, cnd/src/http_api/herc20_halight/alice.rs, cnd/src/http_api/herc20_halight/bob.rs, cnd/src/http_api/routes.rs, cnd/src/storage.rs
Re-export swap_protocols::{protocol} in http_api
Note: Bit weird now, because we always refer to what is in `swap_protocols` module as `http_api::{protocol}` - especially in the `db` I find that a bit awkward (there is no distinction between what is coming from `http_api` and what from the `swap_protocols` now...).
=> Rename struct name to Finalized

cnd/src/connectors.rs, cnd/src/lib.rs, cnd/src/main.rs, cnd/src/swap_protocols/facade.rs, comit/src/btsieve/bitcoin/cache.rs, comit/src/btsieve/ethereum/cache.rs, comit/src/lib.rs, comit/src/timestamp.rs
We would like to be able to determine whether an expiry time has elapsed i.e., whether a refund transaction would be accepted by the relevant blockchain.
In order to do this we add a trait `HasPassed` and then implement it for the layer 1 blockchain connectors.
We then add a new `Connectors` struct and add an instance of this to the `Facade`. Also add methods on the facade to call through to the appropriate connector to expose the required functionality.
=> Add facade 'can_refund' methods for layer 1 connectors

api_tests/src/actors/swap_factory.ts, cnd/src/http_api/halight_herc20/alice.rs, cnd/src/http_api/halight_herc20/bob.rs, cnd/src/http_api/herc20_halight/alice.rs, cnd/src/http_api/herc20_halight/bob.rs, cnd/src/http_api/protocol.rs, cnd/src/http_api/routes.rs, cnd/src/swap_protocols/facade.rs, comit/src/btsieve/bitcoin/cache.rs, comit/src/btsieve/ethereum/cache.rs, comit/src/lib.rs, comit/src/timestamp.rs
We want to recommend to the user what is the next action to take for a swap during the COMIT protocol.
Refund (and only refund) is returned once it is possible to refund, meaning that the HTLC has expired. This is done by checking the blockchain.
This PR is the result of the RUA shape up (@tcharding and @D4nte).
- Patch 1 and 2 are bug fixes to the actions logic
- Patch 3 fixes the e2e tests so that expiries are correct
- Patch 4 adds the RUA logic
- Patch 5 refactors the whole thing
Patch 5 is left separate to assist review, if this is not the case please say and we can squash 4 and 5 together.
This is v2 (total re-write) of https://github.com/comit-network/comit-rs/pull/2736.  Sorry for breaking the thread of context, seems we _still_ don't know how to use GitHub :)
This work is not …
=> Recommend Unique Action (RUA)

comit/src/btsieve.rs, comit/src/btsieve/bitcoin.rs, comit/src/btsieve/ethereum.rs
This function must be called inside a `Gen::new` closure because it relies on a `Co` struct to be passed in. We can simplify things for our callers and construct the generator inside instead.
=> Refactor `find_relevant_blocks` to return a generator

cnd/src/network.rs
During rebasing and merging 3 different PRs I managed to leave a line
of code in that was not intended, this is both wrong and is contrary
to what the code comment says.
This is a totally trivial oneline fix, first reviewer feel free to kick bors to save the next reviewer the time.
=> Actually do what the comment says

api_tests/src/ledgers/bitcoind_instance.ts
Due to the lack of transactions on the local blockchain, bitcoind cannot
estimate a fee. Hence, fallback fee should be set.
See bitcoind 0.20.0 Release notes for details.
=> Upgrade bitcoind to 0.20.0

cnd/src/db/integration_tests/load_protocol_combination.rs, cnd/src/db/save_load_impls.rs, cnd/src/http_api.rs, cnd/src/storage.rs
We have generic types alpha/beta on the http_api `Swap` type. These
are always set to `Protocol`, therefore the generics are unnecessary.
Overly generic code is harder to reason about and maintain.
Remove unnecessary generics from `http_api::Swap<comit::Protocol,
comit::Protocol>` so we have plain old `http_api::Swap`.
=> http_api: Remove unnecessary generics from Swap

cnd/src/db/tables.rs, cnd/src/db/wrapper_types.rs, cnd/src/http_api.rs, cnd/src/http_api/halight.rs, cnd/src/http_api/halight_herc20/alice.rs, cnd/src/http_api/halight_herc20/bob.rs, cnd/src/http_api/hbit.rs, cnd/src/http_api/hbit_herc20/alice.rs, cnd/src/http_api/hbit_herc20/bob.rs, cnd/src/http_api/herc20.rs, cnd/src/http_api/herc20_halight/alice.rs, cnd/src/http_api/herc20_halight/bob.rs, cnd/src/http_api/herc20_hbit/alice.rs, cnd/src/http_api/herc20_hbit/bob.rs, cnd/src/http_api/routes/index.rs, cnd/src/lib.rs, cnd/src/proptest.rs, cnd/src/storage.rs, comit/src/halight.rs, comit/src/herc20.rs, comit/src/ledger.rs
We have a bunch of places where we hard code the regtest network, for all three ledgers. We already have this network information in the database, all we need to do is expose it via the `Finalized` structs.
Add 'network' field, ether `ledger::Bitcoin` for Bitcoin and Lightning swaps or `ChainId` for Ethereum, to the `Finalized` family of structs.
Use new fields and remove hard code ledger types.
- Patch 1 is clean up; removes the `ledger::Lightning` struct.
- Patch 2 is the PR content described above.
=> Remove hard coded regtest network

cnd/src/facade.rs, comit/src/bitcoin.rs, comit/src/btsieve/bitcoin/cache.rs, comit/src/btsieve/ethereum/cache.rs
The `Cache` components are designed to be proxies. Hence, they
must not expose any APIs other than the ones from the component
they are proxying.
We achieve that by moving the calculation of Bitcoin's median-time
to the `bitcoin` module in the `comit` crate.
For Ethereum, the impl is so trivial that we just do it inline in
the facade.
=> Move time-related methods from cache to dedicated modules

.github/workflows/ci.yml
The `actions-rs/toolchain` action can handle the `rust-toolchain`
file just fine, meaning we don't have to explicitely read it and
pass the toolchain.
This simplifies our CI workflow.
=> Simplify CI workflow by not reading the toolchain fine directly

cnd/src/db/errors.rs, cnd/src/db/integration_tests/load_protocol_combination.rs, cnd/src/db/save_load_impls.rs, cnd/src/db/with_swap_types.rs, cnd/src/http_api.rs, cnd/src/http_api/action.rs, cnd/src/http_api/halight.rs, cnd/src/http_api/halight_herc20/alice.rs, cnd/src/http_api/halight_herc20/bob.rs, cnd/src/http_api/hbit.rs, cnd/src/http_api/hbit_herc20/alice.rs, cnd/src/http_api/hbit_herc20/bob.rs, cnd/src/http_api/herc20.rs, cnd/src/http_api/herc20_halight/alice.rs, cnd/src/http_api/herc20_halight/bob.rs, cnd/src/http_api/herc20_hbit/alice.rs, cnd/src/http_api/herc20_hbit/bob.rs, cnd/src/http_api/routes.rs, cnd/src/http_api/routes/index.rs, cnd/src/http_api/routes/rfc003/handlers/action.rs, cnd/src/http_api/swap_resource.rs, cnd/src/lib.rs, cnd/src/load_swaps.rs, cnd/src/network/comit.rs, cnd/src/spawn.rs, cnd/src/storage.rs, cnd/src/with_swap_types.rs, comit/src/bitcoin.rs
Tackling most of @thomaseizinger's suggestions from his review of PR #2776.
Patch af9643e could either be squashed with 2a44449 or reverted and replaced with the introduction of another macro for spawning swaps. This depends on your reviews.
=> Follow-up to PR #2776

.mergify.yml
GitHub recently released a feature called PR retargeting: https://github.blog/changelog/2020-05-19-pull-request-retargeting.
To use that efficiently, we tell mergify to only merge PRs that target `dev`.
Let's see if this works :)
=> Only automatically merge PRs that target dev

cnd/src/db.rs, cnd/src/db/integration_tests/load_protocol_combination.rs, cnd/src/network.rs, cnd/src/spawn.rs, cnd/src/storage.rs, cnd/src/with_swap_types.rs
We can simply filter the list in-memory for desired swap id. Unless
we have A LOT of entries, this should not be an issue.
In case we do, nothing else in the codebase currently deals with this
problem properly.
Draft until https://github.com/comit-network/comit-rs/pull/2829 merges to see if we our mergify configuration and the PR targeting works nicely :)
=> Don't repeat ourselves for loading a single or all swap contexts

CHANGELOG.md
Next release is the first to mention the new split protocols, lets not
muddy the water by using old terminology.
Use halbit in the CHANGELOG to refer to the new Lightning protocol.
=> Use halbit in the CHANGELOG

cnd/src/http_api/halbit_herc20/bob.rs, cnd/src/http_api/hbit.rs, cnd/src/http_api/hbit_herc20/bob.rs, cnd/src/http_api/herc20.rs, cnd/src/http_api/herc20_halbit/alice.rs, cnd/src/http_api/herc20_hbit/alice.rs, cnd/src/storage.rs, comit/src/hbit.rs, comit/src/herc20.rs
I think none of this should be contentious.
It turns out that, in Nectar, using the low-level API `watch_for_EVENT` enables better code composition than if we used `watch_ledger`. I don't think making it public could enable harmful patterns by consumers of the library. It appears to be a very useful building block.
Before patches https://github.com/comit-network/comit-rs/commit/45df400b8a6b39d6b91caf76cdf24ddf9e060d84 and https://github.com/comit-network/comit-rs/commit/6dd9fd48ca7b82e17d80a47ce678ee93847ffdb6, the action building logic lived in the HTTP API module of cnd (the only place where it was needed). Other applications will need this code, so moving it to the COMIT library is needed.
We don't need to get this merged soon, because we're just building against the branch anyway, but …
=> Add a couple things to COMIT lib for Nectar

comit/src/lib.rs
All current swaps involve Bitcoin and depend on the `rust-bitcoin` library. Consumers of COMIT lib can now rely on a specific version of `rust-bitcoin` through this re-exported dependency, avoiding problems with version incompatibility.
Is this all that needs to be done? Did I completely miss the point? :stuck_out_tongue:
=> Re-export rust-bitcoin from COMIT lib

Cargo.lock, cnd/Cargo.toml, comit/Cargo.toml, comit/src/asset/ethereum/ether.rs
Since the bigdecimal lib is not yet updated to num 0.3.0, we have
to implement Display for Ether ourselves.
Turns out to not be too complicated actually :)
This replaces #2844.
=> Bump num from 0.2.1 to 0.3.0

comit/src/lib.rs
What do you think about this approach @D4nte?
I added some documentation as well do emphasize on the trade offs of this approach in the hope that we spend our effort on minimizing the appearance of types from our dependencies in our public APIs :)
=> Replace differently named re-export with `export` module

Cargo.lock, cnd/Cargo.toml
We have a bunch of unused dependencies. Found using udeps.
````
cargo +nightly udeps
...
unused dependencies:
`cnd v0.8.0 (/home/tobin/SPOT/build/github.com/comit-network/comit-rs/cnd)`
└─── dependencies
├─── "bigdecimal"
├─── "fern"
├─── "impl-template"
└─── "paste"
````
Remove the unused dependencies from cnd crate.
=> cnd: Remove unused dependencies

cnd/migrations.sh
A few fixes to the `migrations.sh` script. The first minor the second fundamental, please review carefully to check I'm not missing something. 
- Patch one fixes the fact that the script does not run on Linux using `./migrations.sh`
- Patch two fixes the fact that the script does not get the current version correctly, it currently returns v0.7.3 and we are on v0.8.0
=> Few fixes to migrations.sh

cnd/src/main.rs, cnd/src/network.rs
When using the `Swarm` and `ComitNode` network behaviour for inspiration I noticed that the blockchain connectors and the database was never removed. 
With the concept of the `ProtocolSpawner` we don't need this anymore.
Since that is an easy quick fix I thought I just do it.
=> Remove unused connectors and database from network

cnd/src/http_api/action.rs, comit/src/actions.rs, comit/src/btsieve/ethereum.rs, comit/src/ethereum.rs, comit/src/herc20.rs
The main purpose of this wrapper was serialization to and from hex.
This is a concern of the respective API layer and should hence be
co-located with the consuming code in the REST API.
Resolves #2416.
=> Remove the ethereum::Bytes wrapper

.mergify.yml
We updated to the GitHub powered dependabot here: #2883.
Need to adapt the mergify configuration to make the automation work agian.
I also removed the rule for commenting on it which never really worked.
=> Update mergify configuration to use dependabot from GitHub

cnd/src/halbit.rs, cnd/src/hbit.rs, cnd/src/herc20.rs, cnd/src/proptest.rs, comit/src/halbit.rs, comit/src/hbit.rs, comit/src/herc20.rs
The struct is purely a cnd construct, nothing in `comit` relies on it so it can be safely moved over.
=> Move CreatedSwap to cnd

cnd/src/storage.rs, cnd/src/storage/db/tables.rs
We only use the provided trait in one place, there is no need for
this indirection.
=> Simplify assertion of the side property of a table

comit/src/network/protocols/ethereum_identity.rs, comit/src/network/protocols/secret_hash.rs
By using SerDebug for all of them, we get a nice hex-representation
instead of arrays of bytes in the logs.
=> Align Debug representation of identity messages

.github/workflows/ci.yml
Our caches are so big that they invalidate them constantly. Ubuntu
takes the longest to run with the e2e tests, so it would benefit
the most from caching.
=> Only cache target dir on ubuntu

cnd/src/http_api.rs, cnd/src/http_api/action.rs, cnd/src/http_api/halbit.rs, cnd/src/http_api/halbit_herc20.rs, cnd/src/http_api/hbit.rs, cnd/src/http_api/hbit_herc20.rs, cnd/src/http_api/herc20_halbit.rs, cnd/src/http_api/herc20_hbit.rs, cnd/src/http_api/orderbook.rs, comit/src/asset.rs, comit/src/asset/bitcoin.rs
This patch is meant to set an example on how to effectively deal with the need for repeated serialization needs without locking a type into one a specific one.
In addition, this allows users of the `comit` library to reuse these serialization strategies.
=> Deduplicate serialization efforts without locking in one a specific one

cnd/src/hbit.rs, cnd/src/http_api/problem.rs, cnd/src/http_api/protocol.rs, cnd/src/network.rs, comit/src/btsieve/ethereum.rs, comit/src/ethereum.rs, comit/src/lib.rs, comit/src/network/comit.rs, comit/src/network/protocols/announce.rs, comit/src/network/protocols/orderbook.rs, comit/src/network/protocols/take_order/protocol.rs
Noticed that we didn't have some of the lints enabled in the comit lib.
=> Introduce clippy lints to comit lib

cnd/migrations/2020-07-06-053142_release_0_9_0/down.sql, cnd/migrations/2020-07-06-053142_release_0_9_0/up.sql, cnd/migrations/2020-07-06-053142_remove_address_book/up.sql, cnd/src/facade.rs, cnd/src/main.rs, cnd/src/network.rs, cnd/src/spawn.rs, cnd/src/storage.rs, cnd/src/storage/db.rs, cnd/src/storage/db/integration_tests.rs, cnd/src/storage/db/integration_tests/swap_context.rs, cnd/src/storage/db/schema.rs, cnd/src/storage/db/tables.rs, cnd/src/storage/http_api.rs
This allows us to avoid inline SQL and instead use diesel's built-in abstractions to query and deal with this query.
Initially, I thought the benefit we would be getting out of this is that sqlite would complain if we make a mistake in the SQL query, for example, when a column is misspelled.
Unfortunately, that is not the case but I only realized after the change was done so I thought I put it up anyway :D
=> Make SwapContext query a view

api_tests/tests/orderbook.ts
Tests should be quiet when successful. The ordebook e2e test currently
logs a bunch of stuff to the console - remove it.
=> e2e: Remove orderbook test logging

cnd/src/http_api.rs, cnd/src/http_api/halbit.rs, comit/src/ledger.rs
The bitcoin networks have canonical names (bitcoin, testnet, regtest). As such we can implement serialization/deserialization on them within COMIT and users can simply use these implementations.
Done in preparation for adding networks to the orderbook.
Based on information learned in @thomaseizinger recent post about serialization. If I have mis-understood you Thomas please say so.
=> Add serialization/deserialization for Bitcoin network

cnd/src/http_api/orderbook.rs, comit/src/network/protocols/orderbook.rs
The `MakerId` only exists so we can implement serialization/deserialization on it. 
- Adds stability test
- Adds a roundtrip test
- Adds `From` and `Display` impls (not so sure if we want these)?
=> Add serialization tests for MakerId

api_tests/src/actors/order_factory.ts, cnd/src/http_api/orderbook.rs, comit/src/ledger.rs, comit/src/network/protocols/orderbook.rs
Currently we hardcode regtest in the orderbook. We would like to somehow be able to configure the network so this works on mainnet.
Support mainnet by doing:
- Add a field for both bitcoin and ethereum ledgers on the cnd order creation endpoint.
- Add the ledgers to the orderbook within comit crate.
- Add an assertion method on `NewOrder` to assert a valid ledger pair, defined as the 'same' network kind. Add infrastructure for this assertion.
- Add ser/deser tests for the `ledger` module.
=> Add configurable ledger to ordebook

cnd/src/facade.rs, cnd/src/http_api/orderbook.rs, cnd/src/network.rs, comit/src/network/protocols/orderbook.rs, comit/src/network/protocols/orderbook/order.rs
Refactor the order code (`Order` and `NewOrder`) by doing:
- Patch 1: Add an `order` module to the orderbook (move `Order`, `NewOrder`, `OrderId` into it)
- Patch 2: Use a struct instead of a type alias for `OrderId`
- Patch 3: Move the `NewOrder` type to cnd (it is only used to interface between the controller and the network layer in cnd)
- Patch 4: Use `asset::Bitcoin` in the `Order` struct instead of a u64
=> Refactor order code

api_tests/src/actors/actor.ts, api_tests/src/actors/order_factory.ts, api_tests/tests/orderbook.ts, cnd/src/http_api/orderbook.rs, cnd/src/network.rs, comit/src/asset/bitcoin.rs, comit/src/asset/ethereum/erc20.rs, comit/src/network/protocols/orderbook.rs, comit/src/network/protocols/orderbook/order.rs
A bunch of clean up work and additional features for the orderbook.  This work conflicts with https://github.com/comit-network/comit-rs/pull/2959 mainly due to different names, happy to find some common ground in order to get one of these in.
Does:
- Removes subscription handling
- Use domain term `Position` enabling trades in both directions
- Adds both expiries
- Removes a non-actionalble todos
- Removes unwraps (and associated todos)
- Adds ser/deser unit tests
Turns e2e test into a skeleton.
=> ordebook: field names and position

cnd/src/facade.rs, cnd/src/http_api/orderbook.rs, cnd/src/http_api/route_factory.rs, cnd/src/network.rs, comit/src/network/protocols/orderbook.rs, comit/src/network/protocols/orderbook/order.rs, comit/src/network/protocols/orderbook/take_order.rs
This PR does:
- Add todos from previous PR review
- Improve documentation of the order and orderbook
- Removes the announce trading pair logic from cnd and the orderbook
Reason for announce trading pair removal: We only support a single trading pair, all the announce logic is not needed, it adds unnecessary complexity, code to maintain and reason about.
=> Some more cleanup to the orderbook

api_tests/src/actors/actor.ts, api_tests/src/actors/order_factory.ts, api_tests/tests/orderbook.ts, cnd/src/http_api/orderbook.rs, cnd/src/network.rs, comit/src/network/protocols/orderbook.rs
Extended the orderbook test to execute the swap created from an order.
Various bug fixes in comit, cnd and the test code to get the extended test working.
There will be a follow up PR to cleanup the test code to make it more readable.
=> Extend orderbook test to include swap execution

cnd/src/facade.rs, cnd/src/http_api.rs, cnd/src/http_api/dial_addr.rs, cnd/src/http_api/orderbook.rs, cnd/src/http_api/route_factory.rs, cnd/src/network.rs, comit/src/network/protocols/orderbook.rs
A few cleanup to cnd orderbook code:
- Remove stale comment
- Simplify identifiers
- Move the dial peer/addr endpoint to its own module
- Add some todos for further cleanup work
- Add more assertions to the orderbook unit test
=> Orderbook cnd

comit/src/network/protocols/orderbook.rs
This is all conceptually clean up but changes logic.
Patch 1 - Whitespace, removes a non-actionable TODO
Patch 2 - Remove unused type `SwapType`
Patch 3 - Remove the "makers" topic.
The makers topic is currently not used apart from subscribing to it. Remove it.
=> Remove makers topic

cnd/src/facade.rs, cnd/src/http_api/dial_addr.rs, cnd/src/http_api/orderbook.rs
We do not want TODOs scattered around the codebase. Remove remaining TODOs from the orderbook code.
Patch 1 - TODO is incorrect, remove it
Patch 2 - These ones are not going to get actioned before project close so just remove them.
=> Remove orderbook TODOs

api_tests/src/actors/actor.ts, api_tests/src/actors/defaults.ts, api_tests/src/actors/order_factory.ts, api_tests/src/actors/swap_factory.ts, api_tests/tests/orderbook.ts, cnd/src/facade.rs, cnd/src/http_api/orderbook.rs, cnd/src/network.rs, comit/src/network/protocols/orderbook.rs
Added bidirectional test path in the orderbook e2e test. Refactored the test to improve code reuse and make the test less noisy and easier to understand.
In order to get bidirectional trades working happen the orderbook API was changed. Refund and redeem identity has been replaced bitcoin and ethereum identity. Derivation of transient identities has also changed to take into consideration the direction of the trade.
=> bidirectional e2e test for orderbook 

api_tests/src/actors/order_factory.ts, cnd/src/network.rs, cnd/src/network/peer_tracker.rs
The peer tracker is our component that takes care of peer and address discovery.
Currently when the `addresses_of_peers()` method is called we return a list of the addresses of peers we are connected to, this is not that useful if we are trying to find out an address to dial to make the connection in the first place.
Add a map of peer ids to address hints and return this hint if one exists when the `addresses_of_peer()` method is called (with other known addresses appended).
Fix other dial bug by dialing Bob from Alice in the orderbook e2e tests - just because.
=> Save address hint in the peer tracker

cnd/src/facade.rs, cnd/src/http_api/dial_addr.rs
We get an error back from `dial_addr`, no need to silently drop it. This error can only ever be returned if we hit the connection limit, this is useful information so log it.
=> log connection limit error

.github/workflows/ci.yml, bors.toml, comit/Cargo.toml
This prevents weird timeout errors in bors in case the macos job fails and therefore cancels the ubuntu build.
It does mean that we are now requiring all of those to pass before we can merge but I reckon that is ok. If we don't actually care about these jobs, we should remove them altogether.
=> Make bors listen on all CI jobs

api_tests/src/actors/actor.ts, api_tests/src/actors/order_factory.ts, api_tests/tests/orderbook.ts, comit/src/network/orderbook.rs
In order to debug gossipsub its useful to know when a message arrives at a node from the network.
This PR adds two log statements, merging without review.
=> Add debug statements for receipt of gossipsub messages

Cargo.lock, comit/src/network/protocols/announce.rs
With the release of libp2p-request-response 0.1.1, we no longer
need to work around closing the substream explicitely. Instead,
we can simply drop the response channel.
Note: Given that `take-order` was more or less copied from `announce`, we could make those changes there as well.
cc @rishflab @tcharding
=> Simplify announce error handling

.github/workflows/ci.yml, Cargo.lock, api_tests/package.json, api_tests/yarn.lock, cnd/Cargo.toml, comit/Cargo.toml, digest/Cargo.toml
To hopefully fix the lightning CI error `OpenStatusUpdate is malformed`.
Also fixed the `cannot find serde_derive crate` issue.
See https://github.com/comit-network/comit-js-sdk/pull/255
=> Upgrade to latest comit-sdk

api_tests/src/actors/actor.ts
`ts-ignore` statements should be justified so that the next dev knows why they are there.
- Patch 1: Justify usage of `ts-ignore` due to access of private `client` field.
- Patch 2: Remove unnecessary `ts-ignore` statements.
=> Clean up ts-ignore statements

Cargo.lock, comit/src/network/orderbook.rs
Instead of exporting the entire `take_order` module which leaks the internal structure of the `orderbook` module and is a recipe for
breaking changes.
=> Re-export take_order::Response as TakeOrderResponse

Cargo.lock, cnd/src/http_api.rs, cnd/src/http_api/orderbook.rs, cnd/src/http_api/serde_peer_id.rs, cnd/src/network.rs, cnd/src/trace.rs, comit/Cargo.toml, comit/src/asset/ethereum/ether.rs, comit/src/herc20.rs, comit/src/network/orderbook.rs, comit/src/network/orderbook/makerbook.rs, comit/src/network/orderbook/order.rs, comit/src/network/orderbook/order_source.rs, comit/src/network/orderbook/orders.rs, comit/src/network/orderbook/take_order.rs, digest-macro-derive/src/lib.rs
This allows us to fetch orders from nodes at whichever rate we want
and we are not restricted to the broadcast through the gossipsub
network.
We still use a pubsub-based approach for learning about other makers
but it is now independent from the actual exchange of orders.
=> Re-design orderbook to a pull-based approach

.mergify.yml
Now that bors is waiting for all 4 to succeed, we should also
include them here to avoid preemtive handover to bors in case
a build other than the ubuntu one fails.
=> Include all CI runs in mergify conditions

comit/src/btsieve/bitcoin.rs, comit/src/btsieve/bitcoin/bitcoind_connector.rs, comit/src/btsieve/ethereum.rs, comit/src/btsieve/ethereum/web3_connector.rs, comit/src/hbit.rs, comit/src/herc20.rs
1. Log btsieve functions on a consistent level (debug)
2. Reduce debug spam by moving some of the connectors logs to trace.
=> Small polish on our btsieve logs

Cargo.lock, comit/Cargo.toml, comit/src/expiries.rs, comit/src/lib.rs, comit/src/timestamp.rs
Add `expiries` module.
Ready for merge but not fully functional, reasoning is that this is a library module and the library module _is_ the project deliverable. I will of course attempt to use it after merge and before the project ends. I'd like to clearly separate the two phases described below, merge is how I propose to do that.
This PR completes the first phase, of primary concern are the two `transition_period` methods. The individual transition functions (TTI, TTL) are intended to be opaque (currently `todo!()`).  
The second phase is implementing all the period functions (represented in the spike by TTL, TTI, TTF etc.).
We would like to be able to manipulate timestamps and durations together. We use `time::Duration` because it is more suited to durations of the timeframes we expect …
=> Standardized COMIT Expiry Times

comit/src/network/protocols.rs, comit/src/network/protocols/setup_swap.rs
Add a "one shot" protocol to exchange identities and secret hash.
Built for use with order matching engine.
remake of #3067
=> Add setup-swap protocol

api_tests/src/actors/actor.ts, api_tests/src/actors/defaults.ts, api_tests/src/actors/swap_factory.ts, api_tests/src/create_actors.ts, api_tests/src/test_environment.ts, api_tests/src/utils.ts, api_tests/src/wallets/bitcoin.ts, api_tests/src/wallets/ethereum.ts, api_tests/src/wallets/index.ts, api_tests/src/wallets/lightning.ts, api_tests/tests/halbit_herc20.ts, api_tests/tests/hbit_herc20.ts, api_tests/tests/herc20_halbit.ts, api_tests/tests/herc20_halbit_respawn.ts, api_tests/tests/herc20_hbit.ts, api_tests/tests/herc20_hbit_respawn.ts, api_tests/tests/siren_schema.ts, cnd/src/http_api/problem.rs
This allows us to write DRY tests that for example only require an
address. It is also cleaner in the way that `Actor` is now less
mutable because everything gets initialized from the start.
=> Always initialize a wallet for each ledger within the Actor

comit/src/expiries.rs, comit/src/expiries/config.rs
Improve expiries based on review discussion. This is at a stage now where I'm happy with the research and output. I intend on spending some time now thinking further about how this new module may be used. It would be great to jump on a call with @thomaseizinger and/or @D4nte and walk through the code to see if there are any edge cases I've missed. 
- Use `Started` instead of `Created` (thanks Franck).
- Define periods based on user interaction or software only instead of human vs bot.
- Add checks that invariant beta_expiry <= alpha_expiry always holds.
- Add TODO comment about chain time disparity.
- Use term 'offset' for duration expiries
- Add Alpha/Beta Expiry and Offset types
- Use `cmd::min`
- Improve API, add `start_time`
- Adds a reporting method to show output of created expiries …
=> Improve expiries

comit/src/expiries.rs
Currently we use two statements to get the floor divisor and the
modulus, this can be done in a single statement using the
`num:integer` library.
=> Use num::integer::rem_dev()

CHANGELOG.md, cnd/src/hbit.rs, cnd/src/herc20.rs, cnd/src/protocol_spawner.rs, cnd/src/spawn.rs, cnd/src/storage.rs, comit/src/btsieve.rs, comit/src/btsieve/bitcoin.rs, comit/src/btsieve/ethereum.rs, comit/src/hbit.rs, comit/src/herc20.rs, comit/tests/bitcoin_go_back_into_the_past.rs, comit/tests/bitcoin_missed_previous_latest_block.rs, comit/tests/bitcoin_transaction_pattern_e2e.rs, comit/tests/ethereum_go_back_into_the_past.rs, comit/tests/ethereum_missed_previous_latest_block.rs
While one could argue that the domain dictate a use of UTC, we already
demonstrated that we are not impervious to mistakes coblox/nectar#111.
=> Use datetime type that includes timezone

.mergify.yml
Unfortunately, GH PR retargeting doesn't work if a bot deletes the
head branch. At the same time, if we force delete it the PR gets
closed and closed PRs can't be changed at all, forcing you to open
a new one.
FYI @comit-network/comit-devs.
=> Don't delete head branches if a PR is still open

api_tests/src/actors/actor.ts, api_tests/src/payload.ts, api_tests/tests/siren_schema.ts, cnd/src/http_api/halbit_herc20/alice.rs, cnd/src/http_api/halbit_herc20/bob.rs, cnd/src/http_api/hbit_herc20/alice.rs, cnd/src/http_api/hbit_herc20/bob.rs, cnd/src/http_api/herc20_halbit/alice.rs, cnd/src/http_api/herc20_halbit/bob.rs, cnd/src/http_api/herc20_hbit/alice.rs, cnd/src/http_api/herc20_hbit/bob.rs, cnd/src/http_api/protocol.rs, cnd/src/http_api/swaps.rs
This format favours a flat design in which events are appended
to a list as they are observed by cnd. Or that is at least what
we should do. With the current implementation in cnd, this is not
possible because we compute this state every time the user asks for
it.
In the long run however, we can enrich this format with timestamps
and other information and actually save those events to the database
so that we just need to read them.
This also radically simplifies the assertions in our test.
=> Implement new swap response format 

comit/src/expiries.rs, comit/src/expiries/config.rs
Add support for the deploy action.
Currently we do not take the deployment of the ERC20 contract into account. Do so by adding variants to the `AliceState` and `BobState` enums and conditional logic depending on the protocol in use when determining next action and next state.
Note: Re-introduces a `Protocol` type. Do we want this?
- Patch 1 is refactor: Add `use` statement to reduce noise.
- Patch 2 is the ERC20 support.
- Patch 3 is refactor: Use 'broadcast' uniformly throughout the module.
- Patch 4 is whitespace: audit TODOs and tidy up the TODO comments.
- Patch 5 adds units test for complete swaps in all directions.
=> Handle deploy for ERC20

cnd/src/main.rs
I believe the stack was due to our heavy use of traits which is now
gone. Let's see what the CI says.
=> Remove custom thread stack size

api_tests/tests/herc20_hbit_respawn.ts, api_tests/tests/orderbook.ts
Currently the hbit/herc20 respawn tests use the old create swap POST endpoints. Now that we have an orderbook for swap negotiation we can use it to test respawn functionality.
=> e2e: Use the orderbook for hbit/herc20 respawn tests

cnd/src/http_api.rs, cnd/src/network/comit_node.rs, cnd/src/network/swarm.rs, cnd/src/storage.rs, cnd/src/storage/db.rs, cnd/src/storage/db/tables.rs, cnd/src/storage/db/wrapper_types.rs, cnd/src/storage/db/wrapper_types/text.rs, cnd/src/storage/db/wrapper_types/u32.rs
This allows us directly use our desired type within all structs
that derive `Queryable` and are used to load data from the DB.
As a result, we get less usage of `.0` once the data is loaded
and for the `BtcDaiOrder` in particular, we can directly go into
a `Price` and `Quantity`!
=> Utilize diesel's `deserialize_as` feature of Queryable

comit/Cargo.toml
In semvar changing the PATCH version by definition should not break
the usage of the library.
In Nectar we depend on comit, if we use explicit patch versions for a
dependency that we have in common with cnd then the patch versions
have to match. This adds unnecessary maintenance burden on the two
repositories.
Remove the patch version number from all dependencies.
=> Remove PATCH semvar number from all libraries

cnd/src/http_api/markets/get_btc_dai.rs, cnd/src/network/swarm.rs
The GET markets/BTC-DAI endpoint in Cnd used to return all order including those that do not match the expiries determined by the expiry module. A filter has been added to remove orders that do not match these safe expiries.
=> Filter out market orders with "unsafe" expiries

.github/workflows/ci.yml, api_tests/package.json, api_tests/src/actors/balance_asserter.ts, api_tests/src/actors/cnd_actor.ts, api_tests/src/cnd_client/index.ts, api_tests/src/cnd_client/payload.ts, api_tests/src/environment/test_environment.ts, api_tests/src/swap_factory.ts, api_tests/src/wallets/bitcoin.ts, api_tests/src/wallets/index.ts, api_tests/src/wallets/lightning.ts, api_tests/tests/halbit_herc20.ts, api_tests/tests/herc20_halbit.ts, api_tests/tests/herc20_halbit_respawn.ts, api_tests/tsconfig.json
By targeting ES2020 we can use bigint literals. One can create those
by appending the letter `n` to a number.
To target ES2020, we bump the node version used for our tests to 14.x.
Unfortunately, bigints to serialize automatically to JSON, hence we
utility the `replacer` function of JSON.stringify to serialize all
bigints to strings.
FYI to all @comit-network/comit-devs: You will need to bump your local node version to 14.x after this PR lands.
=> Embrace JS bigint literals

Cargo.lock, api_tests/src/environment/lnd_instance.ts, api_tests/src/environment/test_environment.ts, api_tests/src/wallets/lightning.ts
This caused race conditions in CI. Conceptually, funding Lnd's wallet
during startup is also similar to how we treat the other ledgers.
They start with a single account that has a lot of money and can
distribute it to other accounts. Similarily, we start lnd with a lot
of money and distribute it to individual channels later for the actual
swap.
=> Only fund an LndInstance once

Cargo.lock, cnd/Cargo.toml, cnd/src/network/transport.rs, comit/Cargo.toml, comit/src/network/test.rs, nectar/Cargo.toml, nectar/src/network.rs
SECIO is now deprecated by libp2p (see ref). Use noise instead to build our transports.
ref: https://github.com/libp2p/rust-libp2p/pull/1729
https://blog.ipfs.io/2020-08-07-deprecating-secio/
=> Use noise instead of SECIO

Cargo.lock, api_tests/yarn.lock, nectar/Cargo.toml
This should hopefully sort out the security alert on GitHub.
We also slightly limit our dependency footprint by only opting into
the features we need.
=> Bump dependencies

api_tests/package.json, api_tests/src/environment/kill_nodes.ts, api_tests/src/wallets/lightning.ts, api_tests/yarn.lock
We've had a couple of CI failures that only occured because we
failed to kill the node in the end.
=> Stabilize CI

Cargo.lock, cnd/Cargo.toml, cnd/src/proptest.rs, comit/Cargo.toml, comit/src/btsieve/bitcoin.rs, comit/src/btsieve/bitcoin/cache.rs, comit/src/hbit.rs, comit/src/herc20.rs, comit/tests/bitcoin_helper/connector_mock.rs, comit/tests/bitcoin_transaction_pattern_e2e.rs, nectar/Cargo.toml
This implies an update of blockchain-contracts to 0.4.0 where rust-bitcoin
has already been bumped to 0.25.
Unfortunately, there isn't a recent version of bitcoincore-rpc available that
depends on rust-bitcoin 0.25. Hence, we have to do a to_string() and parse()
dance to make the tests pass again.
=> Upgrade rust-bitcoin version to 0.25

Cargo.lock, nectar/Cargo.toml, nectar/src/ethereum/wallet.rs
The only thing we were depending on wagyu for was for deriving an
Ethereum private key from the seed. We can do that with the
`ExtendedPrivKey` from `bitcoin` and avoid wagyu as a dependency.
~Draft until a new version of clarity is released.~
~The revision I am depending on is this PR: https://github.com/althea-net/clarity/pull/81~
Update: I only needed the clarity patch to use `.context` on clarity's errors. That is actually independent from the wagyu dependency so I quickly patched in an error conversion based on `Fail`'s `Display` impl.
=> Remove wagyu dependency from nectar

nectar/src/network.rs
We recently changed to using the noise protocol for authentication, the comment
didn't get updated.
Update comment to accurately state the authentication protocol.
=> Update stale comment

nectar/sample-config.toml, nectar/src/command/trade.rs, nectar/src/config.rs, nectar/src/config/file.rs, nectar/src/config/settings.rs, nectar/src/mid_market_rate.rs
We want e2e tests between nectar and cnd. For this, we will need to be able to control the rate at which nectar publishes orders.
We make the kraken API host configurable so that we can later plug in a local mock.
=> Make Kraken API host in nectar configurable

api_tests/src/actor_test.ts, api_tests/src/actors/cnd_actor.ts, api_tests/src/cnd_client/index.ts, api_tests/src/config.ts, api_tests/src/environment/cnd_instance.ts, api_tests/tests/sanity.ts, cnd/src/config.rs, cnd/src/config/file.rs, cnd/src/config/settings.rs, cnd/src/main.rs, cnd/src/network/peer_tracker.rs, cnd/src/network/swarm.rs
Add a new config option to pass an array of multiaddress to which the cnd node will try to connect when starting.
Went for addresses only because because at this stage the identification of the peers (via peer id) does not really matter. We just want to connect to another node to get order and execute trustless atomic swaps.
=> [cnd] add peer bootstrap configuration feature

Cargo.lock, nectar/Cargo.toml, nectar/src/command/resume_only.rs, nectar/src/command/trade.rs, nectar/src/command/trade/event_loop.rs, nectar/src/main.rs, nectar/src/swap.rs, nectar/src/swap/comit.rs, nectar/src/swap/comit/hbit.rs, nectar/src/swap/comit/hbit_herc20.rs, nectar/src/swap/comit/herc20.rs, nectar/src/swap/comit/herc20_hbit.rs
This patch serious refactors nectar's swap execution to more generally deal with scenarios in which we want to refund.
We also add logging so we can see what is going on.
Lastly, we refactor `SwapExecutor#execute` to no longer be an async function to avoid accidential blocking of the event-loop.
FYI: @luckysori
=> Refactor nectar swap execution

nectar/src/bitcoin/bitcoind.rs, nectar/src/bitcoin/wallet.rs, nectar/src/swap/bitcoin.rs
The implementation is not particularly pretty at the moment but at least it is contained :)
I opted for using PSBT's because it allows us to configure, where the change-output should be. I believe this is superior to taking the serialized transaction and "finding" the output again. Could be convinced otherwise though :)
=> Make sure we always put the HTLC on out-index 0

Cargo.lock, cnd/Cargo.toml, comit/Cargo.toml, nectar/Cargo.toml
Instead of requiring our users to have openssl installed, we can
compile it from scratch during the build time.
=> Use the native-tls-vendored feature flag from reqwest

nectar/src/bitcoin/bitcoind.rs, nectar/src/bitcoin/wallet.rs
@D4nte has pointed out that `rescan` might be counterproductive. This was added before to help us with the dev-blockchain environment.
In prod the address to be funded is only known after wallet creation.
The rescan was convenient for the dev-environment, but Nectar should not be responsible for rescanning. For now, the user has to take care of running `rescan` for the dev-env.
=> Remove Nectar wallet rescan because not needed in production

.github/workflows/ci.yml, tests/jest.config.js, tests/package.json, tests/src/environment/cnd_instance.ts, tests/src/environment/nectar_instance.ts
FYI @comit-network/comit-devs: With this patch, `cnd` and `nectar` are re-compiled automatically if needed for an e2e test run!
Given that this can take a long time, your initial test run might time out although I've set the timeout to 3 minutes now.
=> Compile cnd and nectar on demand

nectar/src/command/trade.rs, nectar/src/command/trade/event_loop.rs, nectar/src/ethereum/dai.rs, nectar/src/main.rs, nectar/src/maker.rs, nectar/src/maker/strategy.rs, nectar/src/mid_market_rate.rs, nectar/src/order.rs, nectar/src/rate.rs
The current trading strategy that takes for input:
- a spread
- mid-market rate
- available balances
Is now in a dedicated module. Allowing this concern to be removed from
the maker.
Some primitives such as the bitcoin fees and the reserved assets for
ongoing swaps are also moved in the strategy module. It could be argued
that they should stay with the maker or moved in yet another module.
I propose that such concern can be reviewed when another trading
strategy is implemented, validating the best scope for trading
strategies.
=> Segregate trading strategy

nectar/src/maker/strategy.rs, tests/tests/buy_and_sell_bitcoin_e2e_cnd_nectar.ts
The max_sell represents the maximum amount to be traded for each
currency. This should not be concerned by the fees. Fees are on top
of the maximum amount.
Note that checks for sufficient funds are already in place, so we just
remove the fee subtraction, add unit tests to show the bahavior and
adap existing integration and e2e tests.
=> Remove fee subtraction from sell order creation

Cargo.lock, cnd/src/http_api/hbit.rs, comit/src/actions.rs, comit/src/hbit.rs, nectar/Cargo.toml, nectar/sample-config.toml, nectar/src/bitcoin.rs, nectar/src/bitcoin/bitcoind.rs, nectar/src/bitcoin/fee.rs, nectar/src/bitcoin/wallet.rs, nectar/src/command/resume_only.rs, nectar/src/command/trade.rs, nectar/src/config.rs, nectar/src/config/file.rs, nectar/src/config/serde/bitcoin_amount.rs, nectar/src/config/settings.rs, nectar/src/jsonrpc.rs, nectar/src/main.rs, nectar/src/maker.rs, nectar/src/maker/strategy.rs, nectar/src/swap.rs, nectar/src/swap/bitcoin.rs, nectar/src/test_harness/bitcoin.rs, tests/tests/buy_and_sell_bitcoin_e2e_cnd_nectar.ts
Improve fee management for nectar. Two configurations options are offered:
- static fee in sat/byte
- Use bitcoind estimate mode
Please note the bitcoind mode is not tested because I was not able to get it to work in regtest despite injecting a bunch of transactions in the network.
Follow-up PRs:
- Make the `maximum_possible_fee` option take a sat/byte fee and calculate internally what that would be in total tx fee instead of expecting the user to know how big the COMIT transactions are.
=> [nectar] mainnet Bitcoin fee

nectar/sample-config.toml, nectar/src/bitcoin/fee.rs, nectar/src/command/resume_only.rs, nectar/src/command/trade.rs, nectar/src/command/withdraw.rs, nectar/src/config.rs, nectar/src/config/file.rs, nectar/src/config/settings.rs, nectar/src/ethereum.rs, nectar/src/ethereum/gas_price.rs, nectar/src/ethereum/gas_price/eth_gas_station.rs, nectar/src/ethereum/geth.rs, nectar/src/ethereum/wallet.rs, nectar/src/main.rs, nectar/src/swap.rs, nectar/src/swap/ethereum.rs, nectar/src/test_harness/ethereum.rs, tests/src/environment/nectar_config.ts
Allow the user to configure the usage of geth or ethgasstation for gas price.
When using eth gas station, the "safe low" value is chosen.
I introduce a number of TODOs related to the configuration design. I will tacle them in a separate PR once cnd is sorted.
=> Nectar eth gas price

cnd/src/main.rs, cnd/src/spawn.rs
Instead of spawning each protocol individually, we join them
together to a single swap and spawn that into the runtime.
This greatly simplifies the error handling.
To keep things DRY, we use a macro to define the `Swap::execute`
functions.
=> Directly join together the two protocols of a swap

cnd/src/http_api/route_factory.rs, cnd/src/trace.rs, comit/src/actions.rs, comit/src/bitcoin.rs, comit/src/btsieve.rs, comit/src/btsieve/bitcoin.rs, comit/src/btsieve/bitcoin/bitcoind_connector.rs, comit/src/btsieve/bitcoin/cache.rs, comit/src/btsieve/ethereum.rs, comit/src/btsieve/ethereum/cache.rs, comit/src/btsieve/ethereum/watch_for_contract_creation.rs, comit/src/btsieve/ethereum/watch_for_event.rs, comit/src/btsieve/ethereum/web3_connector.rs, comit/src/btsieve/jsonrpc.rs, comit/src/ethereum.rs, comit/src/halbit.rs, comit/src/hbit.rs, comit/src/herc20.rs, comit/src/lnd.rs
This PR presents a series of patches that eventually aim to reduce the logging noise of btsieve.
The biggest problem here is/was that we emitted several events for a single block / tx. All of these events were annotated with big spans, which made it quite hard to see relevant information in the logs.
Additionally, there were some issues were tracing spans were no correctly preserved within async functions.
Finally, we also make a change to btsieve where we yielded the same block several times. This also caused duplicated log messages.
The result is now only a single line per block that still contains a lot of relevant information:
- the block hash: this is useful if we want to check whether btsieve has checked a block
- protocol information: this is useful once btsieve processes several …
=> Reduce logging noise of btsieve without losing any of the information

comit/src/btsieve/jsonrpc.rs, nectar/src/jsonrpc.rs
Instead of using an untagged enum, we can model the JSON-RPC response
as a tagged enum that is flattened into another struct. This greatly
improves the error message we get from serde if we can't deserialize
a response.
This also allows us to directly go into JSON again within nectar's
RPC client because serde's error messages are actually pretty good
if we don't use untagged enums.
=> Improve JSON-RPC error reporting

cnd/CHANGELOG.md, comit/src/expiries.rs, comit/src/expiries/config.rs, nectar/CHANGELOG.md, nectar/src/config/file.rs
We expect Bitcoin's transactions to be included within 6 blocks and Ethereum's within 30 blocks.
Also fix an issue where Bob was told to abort too early.
=>  Update the expected network times to calculate the expiries

Cargo.lock, cnd/CHANGELOG.md, cnd/Cargo.toml
This PR merges the `release/cnd/0.9.0` branch back into `dev`.
This happens to ensure that the updates that happend on the release branch, i.e. CHANGELOG and manifest updates are also present on the dev branch.
=> Merge `release/cnd/0.9.0` into `dev`

nectar/src/command.rs, nectar/src/command/create_transaction.rs, nectar/src/database.rs, nectar/src/database/hbit.rs, nectar/src/database/herc20.rs, nectar/src/ethereum.rs, nectar/src/ethereum/wallet.rs, nectar/src/jsonrpc.rs, nectar/src/main.rs, nectar/src/swap_id.rs
Last patch introduces the commands, all previous patches are smaller refactorings to make it happen.
Here is an example invocation for creating a redeem transaction for the herc20 protocol:
> nectar create-transaction redeem 5c1c2771-4405-46a7-acbc-850ef80b3929 --secret abababababababababababababababababababababababababababababababab --address 0x0011001100110011001100110011001100110011
The hex output is written to stdout whereas all the logging to stderr, meaning one can directly pipe the output to a file or the clipboard if we one wants.
I was also thinking of adding a `--and-broadcast` option if it should be directly broadcasted to the network but refrained from doing so for now. We can add that later if we want to.
At the moment, we also depend on the connections to the wallet to be …
=> Commands for manually creating redeem/refund transactions for nectar

cnd/CHANGELOG.md, cnd/src/config/file.rs, nectar/CHANGELOG.md, nectar/sample-config.toml, nectar/src/config/file.rs, tests/src/environment/cnd_config.ts, tests/src/environment/nectar_config.ts
Align with the other configuration parameters.
=> Use lowercase for log levels

.github/workflows/merge-release-branch-back-into-dev.yml
Previously, we've only merged the release branch back into dev after
a release. That ensured that any commits to the release branch like
bumping the version in the manifest and updating the changelog were
also present in the dev branch.
Even though those changes were merged back into dev, GitHub still
considered a new release branch to be "out-of-date" with master because
it was missing the _merge_ commit that represents the actual release.
There is no semantic difference between merging the release branch
and merging the master branch back into dev.
We change the workflow to use the master branch to have the warning
go away and avoid developers being distracted by it, thinking the
have to action it somehow.
=> Merge master into dev instead of the release branch

cnd/src/bitcoin_fees.rs, cnd/src/config/validation.rs, comit/src/btsieve/jsonrpc.rs, nectar/src/ethereum/gas_price/eth_gas_station.rs
We don't need to define a struct for the error if we all we want
is to add more information to the error stacktrace. Addititionally,
if we were to define a struct for the error, we shouldn't print the
inner error as part of this error struct's message otherwise the
message will get printed twice once anyhow prints the error stacktrace.
More importantly, we want to include context that would otherwise
be lost like the URL we made the request to.
=> Replace dedicated error structs with anyhow's .context

cnd/src/connectors.rs, cnd/src/herc20.rs, comit/src/btsieve/ethereum.rs, comit/src/btsieve/ethereum/cache.rs, comit/src/btsieve/ethereum/watch_for_event.rs, comit/src/btsieve/ethereum/web3_connector.rs, comit/src/ethereum.rs, comit/src/herc20.rs, nectar/src/swap/comit/hbit_herc20.rs, nectar/src/swap/comit/herc20.rs, nectar/src/swap/comit/herc20_hbit.rs
Instead of scanning the blockchain manually, we can leverage the `eth_getLogs` web3 API of the Ethereum node.
This allows us to directly ask for logs emitted by a contract.
Technically, this functionality should no longer be within the `btsieve` module because it doesn't have anything to do with "sieving transactions". I would defer the fix to this to a later point though.
=> Replace btsieve's `watch_for_event` implementation with `eth_getLogs`
